Repository codesquad-members-2022/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#3 [Team-11] 프로젝트 생성 및 환경설정
  IssueTracker/.gitignore
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/AppDelegate.swift
  IssueTracker/IssueTracker/Assets.xcassets/AccentColor.colorset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/Contents.json
  IssueTracker/IssueTracker/Base.lproj/LaunchScreen.storyboard
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/SceneDelegate.swift
  IssueTracker/IssueTracker/ViewController.swift
  IssueTracker/IssueTrackerTests/IssueTrackerTests.swift
  IssueTracker/IssueTrackerUITests/IssueTrackerUITests.swift
  IssueTracker/IssueTrackerUITests/IssueTrackerUITestsLaunchTests.swift
Labels: review-iOS

#16 [Team33][BE][Jun, Jay] ERD, Entity, API 설계 PR
  Backend/.gitignore
  Backend/README.md
  Backend/build.gradle
  Backend/gradle/wrapper/gradle-wrapper.jar
  Backend/gradle/wrapper/gradle-wrapper.properties
  Backend/gradlew
  Backend/gradlew.bat
  Backend/settings.gradle
  Backend/src/main/java/com/team33/backend/BackendApplication.java
  Backend/src/main/java/com/team33/backend/domain/Assignee.java
  Backend/src/main/java/com/team33/backend/domain/Comment.java
  Backend/src/main/java/com/team33/backend/domain/CommonEntity.java
  Backend/src/main/java/com/team33/backend/domain/Emoji.java
  Backend/src/main/java/com/team33/backend/domain/Image.java
  Backend/src/main/java/com/team33/backend/domain/Issue.java
  Backend/src/main/java/com/team33/backend/domain/IssueGroup.java
  Backend/src/main/java/com/team33/backend/domain/IssueGroupMember.java
  Backend/src/main/java/com/team33/backend/domain/IssueStatus.java
  Backend/src/main/java/com/team33/backend/domain/Label.java
  Backend/src/main/java/com/team33/backend/domain/Member.java
  Backend/src/main/java/com/team33/backend/domain/Milestone.java
  Backend/src/main/resources/application-prod.yml
  Backend/src/main/resources/application.yml
  Backend/src/main/resources/schema/schema.sql
  Backend/src/test/java/com/team33/backend/BackendApplicationTests.java
Labels: review-BE

#35 [Team-24][FE][JS&S] 1주차 수요일 pr
  FE/issuetracker/.eslintrc.js
  FE/issuetracker/.gitignore
  FE/issuetracker/.prettierrc
  FE/issuetracker/package-lock.json
  FE/issuetracker/package.json
  FE/issuetracker/public/index.html
  FE/issuetracker/src/App.test.tsx
  FE/issuetracker/src/App.tsx
  FE/issuetracker/src/Router.tsx
  FE/issuetracker/src/assets/fonts/icomoon.eot
  FE/issuetracker/src/assets/fonts/icomoon.svg
  FE/issuetracker/src/assets/fonts/icomoon.ttf
  FE/issuetracker/src/assets/fonts/icomoon.woff
  FE/issuetracker/src/assets/style.css
  FE/issuetracker/src/components/IssueList/index.tsx
  FE/issuetracker/src/components/IssueList/styled.index.js
  FE/issuetracker/src/components/Login/Index.tsx
  FE/issuetracker/src/components/Login/styled.index.js
  FE/issuetracker/src/design/GlobalStyles.js
  FE/issuetracker/src/design/icons.js
  FE/issuetracker/src/design/theme.js
  FE/issuetracker/src/index.tsx
  FE/issuetracker/src/react-app-env.d.ts
  FE/issuetracker/src/setupTests.ts
  FE/issuetracker/tsconfig.json
Labels: review-FE

#15 [team-19][BE][루시드] IssueTracker 1주차 1차 PR
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/issueTracker/IssueTrackerApplication.java
  BE/src/main/java/com/codesquad/issueTracker/User/domain/User.java
  BE/src/main/java/com/codesquad/issueTracker/User/domain/UserRepository.java
  BE/src/main/java/com/codesquad/issueTracker/User/presentation/UserController.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/application/OAuthService.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/domain/RedisTokenRepository.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/GitHubOAuthClientServer.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/JwtTokenProvider.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/OAuthClientServer.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/dto/OAuthTokenRequest.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/dto/OAuthTokenResponse.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/dto/UserProfileResponse.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/presentation/OAuthController.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/presentation/dto/OAuthLoginTokenResponse.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/presentation/dto/OAuthorizationLoginUrlResponse.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/presentation/interceptor/AuthenticationInterceptor.java
  BE/src/main/java/com/codesquad/issueTracker/config/EmbeddedRedisConfig.java
  BE/src/main/java/com/codesquad/issueTracker/config/RedisConfig.java
  BE/src/main/java/com/codesquad/issueTracker/config/RestTemplateConfiguration.java
  BE/src/main/java/com/codesquad/issueTracker/config/WebConfig.java
  BE/src/main/resources/application.yml
  BE/src/test/java/com/codesquad/issueTracker/IssueTrackerApplicationTests.java
  BE/src/test/java/com/codesquad/issueTracker/authentication/presentation/OAuthControllerTest.java
  FE/README.md
Labels: review-BE

#31 [team-20][BE][타니 & 검봉] 1주차 첫번째 PR
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/team20/issuetracker/IssuetrackerApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/team20/issuetracker/IssuetrackerApplicationTests.java
Labels: review-BE

#12 [Team-08][iOS] 프로젝트 초기 설정 및 Coordinator, LoginScene ViewModel과 View 구현
  README.md
  ios/.gitignore
  ios/IssueTracker/.swiftformat
  ios/IssueTracker/.swiftlint.yml
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
  ios/IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/Release.xcscheme
  ios/IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  ios/IssueTracker/IssueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/IssueTracker/IssueTracker/Application/AppDelegate.swift
  ios/IssueTracker/IssueTracker/Application/AppFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  ios/IssueTracker/IssueTracker/Info.plist
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/Flow/LoginFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/View/LoginView.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/View/LoginViewController.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Extensions/Extension+UIColor.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Observable.swift
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/graybg.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/labelGray.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/lightBlue.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/line.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/primary.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/secondary2.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/secondary3.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Logo/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Logo/apple.imageset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Logo/apple.imageset/apple.png
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Logo/git.imageset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Logo/git.imageset/git.png
  ios/IssueTracker/IssueTracker/Resources/Base.lproj/LaunchScreen.storyboard
  ios/IssueTracker/IssueTracker/Resources/Info.plist
  ios/IssueTracker/Podfile
  ios/IssueTracker/Podfile.lock
Labels: review-iOS

#42 [Team-35][FE][BB, 럼카] 프로젝트 세팅, 요구사항 분석
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  README.md
  be/README.md
  fe/.gitignore
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/react-app-env.d.ts
  fe/src/reportWebVitals.ts
  fe/src/setupTests.ts
  fe/tsconfig.json
Labels: review-FE

#2 [Team-22 BE] Issue Tracker 프로젝트 1주차(수요일) 리뷰 요청
  be/.gitignore
  be/README.md
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/codesquad/issuetracker/IssueTrackerApplication.java
  be/src/main/java/codesquad/issuetracker/domain/Issue.java
  be/src/main/java/codesquad/issuetracker/domain/IssueAssignee.java
  be/src/main/java/codesquad/issuetracker/domain/IssueLabel.java
  be/src/main/java/codesquad/issuetracker/domain/IssueMilestone.java
  be/src/main/java/codesquad/issuetracker/domain/Label.java
  be/src/main/java/codesquad/issuetracker/domain/Member.java
  be/src/main/java/codesquad/issuetracker/domain/MileStone.java
  be/src/main/java/codesquad/issuetracker/domain/Reply.java
  be/src/main/java/codesquad/issuetracker/domain/enumtype/IssueStatus.java
  be/src/main/java/codesquad/issuetracker/domain/enumtype/MemberType.java
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/issuetracker/IssueTrackerApplicationTests.java
  fe/.gitignore
Labels: review-BE

#51 [team-31][FE] Maeve & JinJeon 1주차 첫 번째 PR
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  fe/.eslintignore
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/robots.txt
  fe/src/App.tsx
  fe/src/Component/FilterBar/FilterBar.styled.tsx
  fe/src/Component/FilterBar/index.tsx
  fe/src/Component/Header/Header.styled.tsx
  fe/src/Component/Header/index.tsx
  fe/src/Component/Home/FilterCategoryList/FilterCategory.styled.tsx
  fe/src/Component/Home/FilterCategoryList/FilterCategoryList.tsx
  fe/src/Component/Home/Home.styled.tsx
  fe/src/Component/Home/IssueCells/IssueCells.styled.tsx
  fe/src/Component/Home/IssueCells/IssueCells.tsx
  fe/src/Component/Home/index.tsx
  fe/src/Component/Login/Login.styled.tsx
  fe/src/Component/Login/index.tsx
  fe/src/Component/Main/Main.styled.tsx
  fe/src/Component/Main/index.tsx
  fe/src/Component/NewIssue/NewIssue.styled.tsx
  fe/src/Component/NewIssue/NewIssueContent.tsx
  fe/src/Component/NewIssue/NewIssueMain.tsx
  fe/src/Component/NewIssue/NewIssueOptions.tsx
  fe/src/Component/NewIssue/index.tsx
  fe/src/Component/NotFound/NotFound.styled.tsx
  fe/src/Component/NotFound/index.tsx
  fe/src/Component/OptionTabs/OptionsTabs.styled.tsx
  fe/src/Component/OptionTabs/index.tsx
  fe/src/Component/OptionsBox/OptionsBox.styled.tsx
  fe/src/Component/OptionsBox/index.tsx
  fe/src/Component/UserImg/UserImg.styled.tsx
  fe/src/Component/UserImg/index.tsx
  fe/src/Img/images.d.ts
  fe/src/Img/user.jpeg
  fe/src/Img/warning.png
  fe/src/Router/index.tsx
  fe/src/Styles/Normalize.tsx
  fe/src/Styles/Reset.tsx
  fe/src/Styles/index.tsx
  fe/src/Styles/theme.tsx
  fe/src/Util/Icons.tsx
  fe/src/index.tsx
  fe/tsconfig.json
Labels: review-FE

#9 [Team-33] [bang tae, 이든] 1주차 첫번째 PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  Frontend/.eslintrc.js
  Frontend/.gitignore
  Frontend/.prettierrc
  Frontend/README.md
  Frontend/babel.config.json
  Frontend/index.html
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/Title.tsx
  Frontend/src/index.tsx
  Frontend/tsconfig.json
  Frontend/webpack.config.js
Labels: review-FE

#44 [team-20][FE] Millie & J 1주차 1번째 PR
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  FE/.babelrc
  FE/.eslintignore
  FE/.eslintrc
  FE/.gitignore
  FE/.prettierrc
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/assets/favicon.svg
  FE/src/components/Header/index.tsx
  FE/src/components/Header/style.ts
  FE/src/components/ThemeSwitch/index.tsx
  FE/src/components/ThemeSwitch/style.ts
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Button/style.ts
  FE/src/components/common/CustomLink/index.tsx
  FE/src/icons/Logo.tsx
  FE/src/icons/UserProfile.ts
  FE/src/icons/themeSwitch.ts
  FE/src/index.tsx
  FE/src/layout/index.tsx
  FE/src/pages/NotFound/index.tsx
  FE/src/pages/NotFound/style.ts
  FE/src/styles/GlobalStyle.ts
  FE/src/styles/Normalize.ts
  FE/src/styles/color.ts
  FE/src/styles/common.ts
  FE/src/styles/font.ts
  FE/src/styles/mixins.ts
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
  FE/tsconfig.json
  FE/webpack.config.js
  FE/webpack/common.js
  FE/webpack/development.js
  FE/webpack/production.js
  issue-label.json
Labels: review-FE

#24 Team-18][BE] Issue Tracker 프로젝트 1주차 1차 리뷰 요청
  .github/ISSUE_TEMPLATE/feature_request.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/issuetracker/IssueTrackerApplicationTests.java
  FE/.keep
  README.md
Labels: review-BE

#49 [team-36] [BE] sally 1주차 1번째 PR
  .github/ISSUE_TEMPLATE/issue-template.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/sh/issuetracker/IssuetrackerApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/sh/issuetracker/IssuetrackerApplicationTests.java
Labels: review-BE

#23 [team-23(BE)] IssueTracker PR #1 프로젝트 환경 셋팅 및 issue 생성 및 조회 구현
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/ron2ader/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueCreateRequest.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueDetail.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueDetailResponse.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueSimpleResponse.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/memberdto/MemberDto.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/common/BaseEntity.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/Issue.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/member/MemberRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/service/IssueService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/sql/data.sql
  BE/src/test/java/com/ron2ader/issuetracker/IssueTrackerApplicationTest.java
  BE/src/test/java/com/ron2ader/issuetracker/service/IssueServiceTest.java
Labels: review-BE

#48 [team-26][FE] 호이 & 아울 1주차 1번째 PR
  .github/ISSUE_TEMPLATE/-be--issue-template.md
  .github/ISSUE_TEMPLATE/-fe--issue-template.md
  .github/ISSUE_TEMPLATE/commit-template.md
  README.md
  frontend/.gitignore
  frontend/README.md
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: review-FE

#11 [FE][team-32][Geon, Dori] 1주차 수요일 PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/babel.config.json
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/mockServiceWorker.js
  fe/src/App.tsx
  fe/src/assets/icons/pauseCircle.svg
  fe/src/components/Card/index.tsx
  fe/src/components/Card/style.ts
  fe/src/custom.d.ts
  fe/src/hoc/PrivateRoute.tsx
  fe/src/hoc/PublicRoute.tsx
  fe/src/index.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handler.ts
  fe/src/pages/IssueDetail/index.tsx
  fe/src/pages/Issues/index.tsx
  fe/src/pages/Labels/index.tsx
  fe/src/pages/Login/index.tsx
  fe/src/pages/Milestones/index.tsx
  fe/src/pages/NotAllow/index.tsx
  fe/src/pages/NotFound/index.tsx
  fe/src/pages/Signup/index.tsx
  fe/src/pages/index.ts
  fe/src/styles/GlobalStyles.ts
  fe/src/styles/Normalize.ts
  fe/src/styles/styled.d.ts
  fe/src/styles/theme.ts
  fe/tsconfig.json
  fe/webpack/webpack.common.js
  fe/webpack/webpack.development.js
  fe/webpack/webpack.production.js
Labels: review-FE

#27 [team29][BE][제리 & 후] 1주차 첫번째 PR
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/team29/hoorry/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team29/hoorry/issuetracker/config/SwaggerConfig.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueAssigneesUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueFilter.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueLabelsUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueMilestoneUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueStatusUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueTitleUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssuesSaveRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssuesStatusUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/CommentResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueDetailResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueLabelResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMemberResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMilestoneResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMilestoneSimpleResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssuesResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/ReactionResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/LabelController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/LabelMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/domain/Label.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/dto/LabelAddRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/dto/LabelUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/dto/LabelsResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/MilestoneController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/MilestoneMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/domain/Milestone.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneAddRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneDetailResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestonesResponse.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/team29/hoorry/issuetracker/IssueTrackerApplicationTests.java
  README.md
Labels: review-BE

#41 [Team-05] [Lee] 이슈트래커 BE 1주차 첫 번째 PR입니다.
  .github/ISSUE_TEMPLATE/issue-template.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/issuetraker/IssueTrakerApplication.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/user/OauthClient.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/user/User.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/issuetraker/IssueTrakerApplicationTests.java
  pull_request_template.md
Labels: review-BE

#45 [team-13][Eddy, Selina] 첫번째 PR
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/swiftlint.yml
  .github/workflows/xcode_test.yml
  .gitignore
  .gitmessage.txt
  .swiftlint.yml
  PRTracker.xcodeproj/project.pbxproj
  PRTracker.xcodeproj/xcshareddata/xcschemes/PRTracker.xcscheme
  PRTracker.xcworkspace/contents.xcworkspacedata
  PRTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  PRTracker/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  PRTracker/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  PRTracker/Resource/Assets.xcassets/Contents.json
  PRTracker/Resource/Assets.xcassets/Images/Contents.json
  PRTracker/Resource/Assets.xcassets/Images/img_logo.imageset/Contents.json
  PRTracker/Resource/Assets.xcassets/Images/img_logo.imageset/img_logo.png
  PRTracker/Resource/Base.lproj/LaunchScreen.storyboard
  PRTracker/Resource/Base.lproj/Main.storyboard
  PRTracker/Source/Common/Logger.swift
  PRTracker/Source/Common/Observable.swift
  PRTracker/Source/Common/ReplaceRootSegue.swift
  PRTracker/Source/Login/Model/KeyChainManger.swift
  PRTracker/Source/Login/Model/OAuthManger.swift
  PRTracker/Source/Login/Model/TokenResponse.swift
  PRTracker/Source/Login/View/LoginView.swift
  PRTracker/Source/Login/View/ViewController.swift
  PRTracker/Source/Login/ViewModel/LoginViewModel.swift
  PRTracker/Source/PR_Listing/Model/ListingManager.swift
  PRTracker/Source/PR_Listing/Model/Pull.swift
  PRTracker/Source/PR_Listing/View/ListingTableView.swift
  PRTracker/Source/PR_Listing/View/ListingViewController.swift
  PRTracker/Source/PR_Listing/ViewModel/LabelViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/ListingViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/PRTableCellViewModel.swift
  PRTracker/Supporting/AppDelegate.swift
  PRTracker/Supporting/Info.plist
  PRTracker/Supporting/SceneDelegate.swift
  PRTrackerTests/PRTrackerTests.swift
  Podfile
  Podfile.lock
  README.md
Labels: review-iOS

#21 [team-12][iOS][Mase-Ebony] 1주 수요일 PR
  .gitignore
  IssueTracker/.swiftlint.yml
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker/AppDelegate.swift
  IssueTracker/IssueTracker/Assets.xcassets/AccentColor.colorset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/applelogin.imageset/ButtonLarge (1).png
  IssueTracker/IssueTracker/Assets.xcassets/applelogin.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/githublogin.imageset/ButtonLarge.png
  IssueTracker/IssueTracker/Assets.xcassets/githublogin.imageset/Contents.json
  IssueTracker/IssueTracker/Base.lproj/LaunchScreen.storyboard
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/common/UserDefaultManager.swift
  IssueTracker/IssueTracker/common/ViewControllerType.swift
  IssueTracker/IssueTracker/extension/UIView+Extension.swift
  IssueTracker/IssueTracker/issue/IssueViewController.swift
  IssueTracker/IssueTracker/login/LoginReactor.swift
  IssueTracker/IssueTracker/login/LoginView.swift
  IssueTracker/IssueTracker/login/LoginViewController.swift
  IssueTracker/IssueTracker/network/GithubAPI.swift
  IssueTracker/IssueTracker/network/GithubTokenRepository.swift
  IssueTracker/IssueTracker/scene/SceneDelegate.swift
  IssueTracker/IssueTracker/scene/SceneReactor.swift
  IssueTracker/IssueTrackerTests/IssueTrackerTests.swift
  IssueTracker/IssueTrackerTests/mock/GithubRepositoryStub.swift
  IssueTracker/IssueTrackerUITests/IssueTrackerUITests.swift
  IssueTracker/IssueTrackerUITests/IssueTrackerUITestsLaunchTests.swift
  IssueTracker/MockAccessToken.json
  IssueTracker/Podfile
Labels: review-iOS

#26 [Team16][iOS] 1주차 수요일 Issue-Tracker PR
  .gitignore
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker/.swiftlint.yml
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/Resource/Issue.json
  IssueTracker/IssueTracker/Resource/NetworkService/DecodeManager.swift
  IssueTracker/IssueTracker/Resource/NetworkService/LoginManager.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/Issue.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/IssueResponse.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/IssueState.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/Milestone.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/Tag.swift
  IssueTracker/IssueTracker/Source/IssueList/View/IssueCell.swift
  IssueTracker/IssueTracker/Source/IssueList/View/IssueListViewController.swift
  IssueTracker/IssueTracker/Source/Support/AppDelegate.swift
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/AccentColor.colorset/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/AppIcon.appiconset/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/UserImageIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/UserImageIcon.imageset/User Image Small (1).png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/UserImageIcon.imageset/User Image Small.png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/filterIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/filterIcon.imageset/Icon (1).png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/filterIcon.imageset/Icon.png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/issueIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/issueIcon.imageset/Property 1=alert-circle (2).png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/milestoneIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/milestoneIcon.imageset/Vector (7).png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/milestoneIcon.imageset/Vector (8).png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/selectIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/selectIcon.imageset/Icon (2).png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/selectIcon.imageset/Icon (3).png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/tagIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/tagIcon.imageset/Vector (5).png
  IssueTracker/IssueTracker/Source/Support/Assets.xcassets/tagIcon.imageset/Vector (6).png
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
  IssueTracker/IssueTracker/Source/Support/ViewController.swift
  IssueTracker/IssueTracker/Source/TabBarViewController.swift
  IssueTracker/MockIssueTest/MockIssueTest.swift
  IssueTracker/Podfile
  IssueTracker/Podfile.lock
Labels: review-iOS

#43 [team-07] 로그인 화면 구현 (1주차 수요일 PR)
  iOS/.gitignore
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  iOS/IssueTracker/IssueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/IssueTracker/IssueTracker/AppDelegate.swift
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/NewColorSet/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/NewColorSet/LogSignInButton.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/NewColorSet/LoginBackground.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/NewColorSet/OAuthLoginButton.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/apple.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/apple.imageset/apple.png
  iOS/IssueTracker/IssueTracker/Assets.xcassets/github.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/github.imageset/github.png
  iOS/IssueTracker/IssueTracker/Base.lproj/LaunchScreen.storyboard
  iOS/IssueTracker/IssueTracker/ClientKey.plist
  iOS/IssueTracker/IssueTracker/Extension/UIColor+.swift
  iOS/IssueTracker/IssueTracker/Extension/UIImage+.swift
  iOS/IssueTracker/IssueTracker/Extension/UIView+.swift
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/IssueTracker.entitlements
  iOS/IssueTracker/IssueTracker/LoginScene/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/View/LoginInputView.swift
  iOS/IssueTracker/IssueTracker/LoginScene/View/OAuthButtonDelegate.swift
  iOS/IssueTracker/IssueTracker/LoginScene/View/OAuthLoginButton.swift
  iOS/IssueTracker/IssueTracker/LoginScene/View/OAuthLoginView.swift
  iOS/IssueTracker/IssueTracker/Network/EndPoint.swift
  iOS/IssueTracker/IssueTracker/Network/HTTPMethod.swift
  iOS/IssueTracker/IssueTracker/Network/NetworkService.swift
  iOS/IssueTracker/IssueTracker/Network/OauthNetworkManager.swift
  iOS/IssueTracker/IssueTracker/NotificationCenter.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/Podfile
  iOS/IssueTracker/Podfile.lock
Labels: review-iOS

#32 [Team-34][BE] 1주차 수요일 정기 PR
  BE/.gitignore
  BE/HELP.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/org/codesquad/team34/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthCredential.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthProperties.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthProviders.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubAccessToken.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubOAuthClient.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubOAuthController.java
  BE/src/main/resources/application.yml
  BE/src/test/java/org/codesquad/team34/issuetracker/IssueTrackerApplicationTests.java
Labels: review-BE

#36 [FE][team-25] Dott & Ver 1주차 PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/generic-issue.md
  .github/ISSUE_TEMPLATE/pr-template.md
  BE/README.md
  FE/.eslintrc
  FE/.gitignore
  FE/.prettierrc
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/public/mockServiceWorker.js
  FE/src/App.tsx
  FE/src/index.tsx
  FE/src/mocks/browser.js
  FE/src/mocks/handlers.js
  FE/tsconfig.json
  FE/webpack.common.js
  FE/webpack.dev.js
  FE/webpack.prod.js
Labels: review-FE

#56 [Team-30] [BE] 1주차 첫 번째 PR(2)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  BE/.gitignore
  BE/build.gradle
  BE/docker/README.md
  BE/docker/database-local.yml
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/backend/issuetracker/BeApplication.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/GithubOAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/JwtFactory.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/OAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/OAuthService.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubToken.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubUser.java
  BE/src/main/java/codesquad/backend/issuetracker/user/domain/User.java
  BE/src/main/java/codesquad/backend/issuetracker/user/infrastructure/UserRepository.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/backend/issuetracker/BeApplicationTests.java
  BE/src/test/java/codesquad/backend/issuetracker/oauth/AuthControllerTest.java
  BE/src/test/java/codesquad/backend/issuetracker/oauth/JwtTest.java
  FE/.keep
  README.md
Labels: review-BE

#55 [team-34 | dony & hemdi] 1주차 1번째 PR 요청드립니다.
  FE/.babelrc
  FE/.eslintrc.json
  FE/.gitignore
  FE/.prettierrc
  FE/.storybook/main.js
  FE/.storybook/preview.js
  FE/README.md
  FE/config/webpack.common.js
  FE/config/webpack.dev.js
  FE/config/webpack.prod.js
  FE/craco.config.js
  FE/package.json
  FE/src/App.tsx
  FE/src/assets/icons/icon_close.svg
  FE/src/assets/icons/icon_plus.svg
  FE/src/assets/icons/icon_search.svg
  FE/src/components/Icon/index.tsx
  FE/src/components/TextInput/TextInput.stories.tsx
  FE/src/components/TextInput/index.tsx
  FE/src/components/TextInput/style.ts
  FE/src/components/TextInput/type.ts
  FE/src/components/button/Button.stories.tsx
  FE/src/components/button/index.tsx
  FE/src/components/button/style.ts
  FE/src/components/button/type.ts
  FE/src/hooks/useInputTextValue.tsx
  FE/src/index.tsx
  FE/src/public/index.html
  FE/src/styles/GlobalStyle.tsx
  FE/src/styles/common/color.ts
  FE/src/styles/common/font.ts
  FE/src/styles/common/index.ts
  FE/src/types/custom.d.ts
  FE/src/utils/debounce.tsx
  FE/tsconfig.json
  FE/yarn.lock
  README.md
Labels: review-FE

#29 [Team-15][iOS] 앱 구조 정의, DI Container, Git issue 해결
  .gitignore
  IssueTracker15/ContainerUnitTest/ContainerUnitTest.swift
  IssueTracker15/ContainerUnitTest/MockContainer.swift
  IssueTracker15/ContainerUnitTest/MockData.swift
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  IssueTracker15/IssueTracker15.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker15/IssueTracker15.xcodeproj/xcshareddata/xcschemes/IssueTracker15.xcscheme
  IssueTracker15/IssueTracker15.xcworkspace/contents.xcworkspacedata
  IssueTracker15/IssueTracker15.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker15/IssueTracker15/.swiftlint.yml
  IssueTracker15/IssueTracker15/Info.plist
  IssueTracker15/IssueTracker15/RegularExpressionChecker/IDChecker.swift
  IssueTracker15/IssueTracker15/RegularExpressionChecker/PasswordChecker.swift
  IssueTracker15/IssueTracker15/SupportingFiles/AppDelegate.swift
  IssueTracker15/IssueTracker15/SupportingFiles/Assets.xcassets/AccentColor.colorset/Contents.json
  IssueTracker15/IssueTracker15/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  IssueTracker15/IssueTracker15/SupportingFiles/Assets.xcassets/Contents.json
  IssueTracker15/IssueTracker15/SupportingFiles/SceneDelegate.swift
  IssueTracker15/IssueTracker15/Test/Container/ContainerWrapper.swift
  IssueTracker15/IssueTracker15/Test/Container/Resolvable.swift
  IssueTracker15/IssueTracker15/Test/Container/UseCaseContainer.swift
  IssueTracker15/IssueTracker15/Test/UseCases/RequestModel.swift
  IssueTracker15/IssueTracker15/Test/UseCases/TestDecodableType.swift
  IssueTracker15/IssueTracker15/Test/UseCases/TestUseCase.swift
  IssueTracker15/IssueTracker15/Test/UseCases/UseCaseResponsible.swift
  IssueTracker15/IssueTracker15/Test/ViewModel/TestViewModel.swift
  IssueTracker15/IssueTracker15/Test/ViewTypes/BoldStringAdaptable.swift
  IssueTracker15/IssueTracker15/Test/ViewTypes/LargeStringAdaptable.swift
  IssueTracker15/IssueTracker15/Test/ViewTypes/ViewBindable.swift
  IssueTracker15/IssueTracker15/Test/ViewTypes/ViewTextBindable.swift
  IssueTracker15/IssueTracker15/Test/Views/TestButton.swift
  IssueTracker15/IssueTracker15/Test/Views/TestLabel.swift
  IssueTracker15/IssueTracker15/ViewController.swift
  IssueTracker15/Podfile
  IssueTracker15/RegularExpressionCheckerUnitTest/RegularExpressionCheckerUnitTest.swift
  README.md
Labels: review-iOS

#39 [Team-09][BE][테리&벅픽] 프로젝트 초기설정, 초기 API 설계, MockAPI 설정, 컨트롤러-도메인-DTO 초기 구성
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/docs/issue_tracker_erd.png
  BE/docs/issue_tracker_table_create.sql
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/team09/issue_tracker/IssueTrackerApplication.java
  BE/src/main/java/com/team09/issue_tracker/comment/Comment.java
  BE/src/main/java/com/team09/issue_tracker/comment/CommentController.java
  BE/src/main/java/com/team09/issue_tracker/comment/CommentEmogi.java
  BE/src/main/java/com/team09/issue_tracker/comment/Emogi.java
  BE/src/main/java/com/team09/issue_tracker/comment/EmogiController.java
  BE/src/main/java/com/team09/issue_tracker/comment/dto/CommentRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/comment/dto/CommentResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/comment/dto/EmogiRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/common/BaseTimeEntity.java
  BE/src/main/java/com/team09/issue_tracker/common/CommonResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/image/ImageController.java
  BE/src/main/java/com/team09/issue_tracker/issue/Issue.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueAssignee.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueLabel.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueCreateAndUpdateRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueFindAllResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueFindByIdResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueUpdateAllRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/label/Label.java
  BE/src/main/java/com/team09/issue_tracker/label/LabelController.java
  BE/src/main/java/com/team09/issue_tracker/label/dto/LabelRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/label/dto/LabelSelectResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/member/Member.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberController.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberType.java
  BE/src/main/java/com/team09/issue_tracker/milestone/Milestone.java
  BE/src/main/java/com/team09/issue_tracker/milestone/MilestoneController.java
  BE/src/main/java/com/team09/issue_tracker/milestone/dto/MilestoneRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/milestone/dto/MilestoneSelectResponseDto.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/logback-spring.xml
Labels: review-BE

#57 [TEAM-24][BE] 민지노 && 필 1주차 첫번째 PR
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/team24-issue-template.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/team24/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team24/issuetracker/domain/Assignee.java
  BE/src/main/java/team24/issuetracker/domain/Comment.java
  BE/src/main/java/team24/issuetracker/domain/Image.java
  BE/src/main/java/team24/issuetracker/domain/Issue.java
  BE/src/main/java/team24/issuetracker/domain/IssueLabel.java
  BE/src/main/java/team24/issuetracker/domain/Label.java
  BE/src/main/java/team24/issuetracker/domain/Milestone.java
  BE/src/main/java/team24/issuetracker/domain/User.java
  BE/src/main/java/team24/issuetracker/web/config/SwaggerConfig.java
  BE/src/main/java/team24/issuetracker/web/controller/IssueController.java
  BE/src/main/java/team24/issuetracker/web/dto/IssueListResponsse.java
  BE/src/main/java/team24/issuetracker/web/repository/IssueRepository.java
  BE/src/main/java/team24/issuetracker/web/service/IssueService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/team24/issuetracker/IssueTrackerApplicationTests.java
Labels: review-BE

#61 [Team-10][iOS][Dale,Sally] - 컨벤션 정리 및 로직 분리
  GitTuul/GitTuul.xcodeproj/project.pbxproj
  GitTuul/GitTuul/Source/Extension/NotificationName+extension.swift
  GitTuul/GitTuul/Source/Extension/UIColor+extension.swift
  GitTuul/GitTuul/Source/Extension/UIFont+extension.swift
  GitTuul/GitTuul/Source/LifeCycle/SceneDelegate.swift
  GitTuul/GitTuul/Source/Model/API/EndPoint/GithubEndPoint.swift
  GitTuul/GitTuul/Source/Model/API/EndPoint/GithubScope.swift
  GitTuul/GitTuul/Source/Model/API/EndPoint/NetworkError.swift
  GitTuul/GitTuul/Source/Model/API/NetworkManager.swift
  GitTuul/GitTuul/Source/Model/Entity/GithubEntity.swift
  GitTuul/GitTuul/Source/Model/Entity/IssueEntity.swift
  GitTuul/GitTuul/Source/Present/Common/PaddingLabel.swift
  GitTuul/GitTuul/Source/Present/GitTuulTabBarController.swift
  GitTuul/GitTuul/Source/Present/IssueView/IssueCell.swift
  GitTuul/GitTuul/Source/Present/IssueView/IssueHeader.swift
  GitTuul/GitTuul/Source/Present/IssueView/IssueViewController.swift
  GitTuul/GitTuul/Source/Present/IssueView/IssueViewDataSource.swift
  GitTuul/GitTuul/Source/Present/IssueView/LabelCollectionViewCell.swift
  GitTuul/GitTuul/Source/Present/IssueView/LabelCollectionViewDataSource.swift
  GitTuul/GitTuul/Source/Present/IssueView/ViewModel/IssueViewModel.swift
  GitTuul/GitTuul/Source/Present/LoginView/IdView.swift
  GitTuul/GitTuul/Source/Present/LoginView/LoginViewController.swift
  GitTuul/GitTuul/Source/Present/LoginView/ViewModel/LoginViewModel.swift
  GitTuul/GitTuul/Source/Present/Support/LayoutFactory.swift
  GitTuul/GitTuul/Source/Present/Support/ViewControllerFactory.swift
Labels: review-iOS

#77 [Team33][BE][Jun, Jay] ERD, Entity, API 설계 PR
  Backend/build.gradle
  Backend/src/main/java/com/team33/backend/comment/Comment.java
  Backend/src/main/java/com/team33/backend/common/CommonEntity.java
  Backend/src/main/java/com/team33/backend/common/exception/BaseExceptionType.java
  Backend/src/main/java/com/team33/backend/common/exception/BusinessException.java
  Backend/src/main/java/com/team33/backend/common/exception/ErrorResponse.java
  Backend/src/main/java/com/team33/backend/common/exception/GlobalExceptionHandler.java
  Backend/src/main/java/com/team33/backend/common/exception/member/MemberTypeException.java
  Backend/src/main/java/com/team33/backend/domain/Assignee.java
  Backend/src/main/java/com/team33/backend/domain/Comment.java
  Backend/src/main/java/com/team33/backend/domain/Emoji.java
  Backend/src/main/java/com/team33/backend/domain/Image.java
  Backend/src/main/java/com/team33/backend/domain/Issue.java
  Backend/src/main/java/com/team33/backend/domain/IssueGroupMember.java
  Backend/src/main/java/com/team33/backend/domain/Label.java
  Backend/src/main/java/com/team33/backend/domain/Member.java
  Backend/src/main/java/com/team33/backend/domain/Milestone.java
  Backend/src/main/java/com/team33/backend/emoji/Emoji.java
  Backend/src/main/java/com/team33/backend/emoji/EmojiController.java
  Backend/src/main/java/com/team33/backend/group/IssueGroup.java
  Backend/src/main/java/com/team33/backend/image/Image.java
  Backend/src/main/java/com/team33/backend/issue/domain/Assignee.java
  Backend/src/main/java/com/team33/backend/issue/domain/Issue.java
  Backend/src/main/java/com/team33/backend/issue/domain/IssueLabel.java
  Backend/src/main/java/com/team33/backend/issue/domain/IssueStatus.java
  Backend/src/main/java/com/team33/backend/issue/domain/Label.java
  Backend/src/main/java/com/team33/backend/issue/domain/Milestone.java
  Backend/src/main/java/com/team33/backend/member/IssueGroupMember.java
  Backend/src/main/java/com/team33/backend/member/Member.java
  Backend/src/test/java/com/team33/backend/domain/AssigneeRepository.java
  Backend/src/test/java/com/team33/backend/domain/IssueRepository.java
  Backend/src/test/java/com/team33/backend/domain/IssueTest.java
Labels: review-BE

#71 [Team-18][BE] Issue Tracker 프로젝트 1주차 2차 리뷰 요청
  BE/build.gradle
  BE/src/main/java/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/codesquad/issuetracker/domain/Assignee.java
  BE/src/main/java/codesquad/issuetracker/domain/Comment.java
  BE/src/main/java/codesquad/issuetracker/domain/CommonEntity.java
  BE/src/main/java/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/codesquad/issuetracker/domain/IssueStatus.java
  BE/src/main/java/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/codesquad/issuetracker/domain/Milestone.java
  BE/src/main/java/codesquad/issuetracker/domain/User.java
  BE/src/main/java/codesquad/issuetracker/service/OAuthService.java
  BE/src/main/java/codesquad/issuetracker/web/OAuthController.java
  BE/src/main/java/codesquad/issuetracker/web/dto/GithubAccessToken.java
  BE/src/main/java/codesquad/issuetracker/web/dto/GithubTokenRequestDto.java
  BE/src/main/java/codesquad/issuetracker/web/dto/GithubUserInformation.java
  BE/src/main/java/codesquad/issuetracker/web/jwt/JwtFactory.java
  BE/src/main/resources/application-dev.yml
Labels: review-BE

#91 [TEAM-33][bangtae, 이든][FE]1주차 금요일 PR
  Frontend/.eslintrc.js
  Frontend/.eslintrc.json
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/IssueTable/IssueItem/index.tsx
  Frontend/src/IssueTable/IssueItem/style.ts
  Frontend/src/IssueTable/IssueList/index.tsx
  Frontend/src/IssueTable/IssueList/style.ts
  Frontend/src/IssueTable/IssueMenuBar/index.tsx
  Frontend/src/IssueTable/IssueMenuBar/style.ts
  Frontend/src/IssueTable/index.tsx
  Frontend/src/IssueTable/style.ts
  Frontend/src/Title.tsx
  Frontend/src/common/Button/index.tsx
  Frontend/src/common/Button/style.ts
  Frontend/src/common/CheckBox/index.tsx
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Button/style.ts
  Frontend/src/components/DropBox/index.tsx
  Frontend/src/components/DropBox/style.ts
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/components/DropDown/style.ts
  Frontend/src/index.tsx
  Frontend/src/pages/Issue/index.tsx
  Frontend/src/pages/IssueCreate/index.tsx
  Frontend/src/pages/Label/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Login/style.ts
  Frontend/src/pages/Main/index.tsx
  Frontend/src/pages/Main/style.ts
  Frontend/src/pages/MileStone/index.tsx
  Frontend/src/style/global.ts
  Frontend/src/style/theme.ts
  Frontend/webpack.config.js
Labels: review-FE

#101 [team-20][FE] Millie & J 1주차 2번째 PR
  FE/.eslintrc
  FE/src/App.tsx
  FE/src/assets/fonts/NotoSans-Bold.woff
  FE/src/assets/fonts/NotoSans-Medium.woff
  FE/src/assets/fonts/NotoSans-Regular.woff
  FE/src/assets/fonts/index.ts
  FE/src/components/Header/style.ts
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Button/style.ts
  FE/src/components/common/Input/index.tsx
  FE/src/components/common/Input/style.ts
  FE/src/custom.d.ts
  FE/src/index.tsx
  FE/src/pages/Login/index.tsx
  FE/src/pages/Login/style.ts
  FE/src/pages/NotFound/index.tsx
  FE/src/styles/GlobalStyle.ts
  FE/src/styles/color.ts
  FE/src/styles/common.ts
  FE/src/styles/font.ts
  FE/src/styles/mixins.ts
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
  FE/webpack/common.js
Labels: review-FE

#89 [Team-34][BE] 1주차 금요일 정기 PR
  BE/build.gradle
  BE/src/main/java/org/codesquad/team34/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/LoginToken.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/LoginTokenFactory.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthCredential.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthProvider.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthProviders.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthService.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubAccessToken.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubOAuthClient.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubOAuthController.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubUserProfile.java
  BE/src/main/java/org/codesquad/team34/issuetracker/common/BaseEntity.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/Member.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/MemberRepository.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/sql/schema.sql
Labels: review-BE

#97 [Team-35][FE][BB, 럼카] 프로젝트 세팅, 요구사항 분석
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/@types/import-svg.d.ts
  fe/src/App.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/assets/alert-circle.svg
  fe/src/assets/archive.svg
  fe/src/assets/calendar.svg
  fe/src/assets/check-box-active.svg
  fe/src/assets/check-box-disable.svg
  fe/src/assets/check-box-initial.svg
  fe/src/assets/check-off-circle.svg
  fe/src/assets/check-on-circle.svg
  fe/src/assets/edit.svg
  fe/src/assets/milestone.svg
  fe/src/assets/paperclip.svg
  fe/src/assets/plus.svg
  fe/src/assets/refresh.svg
  fe/src/assets/search.svg
  fe/src/assets/smile.svg
  fe/src/assets/tag.svg
  fe/src/assets/trash.svg
  fe/src/assets/x-square.svg
  fe/src/components/common/Icon.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/react-app-env.d.ts
  fe/src/reportWebVitals.ts
  fe/src/setupTests.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/color.ts
  fe/src/styles/font.ts
  fe/tsconfig.json
Labels: review-FE

#58 [TEAM-02][BE][케이] 1주차 첫번째 PR
  .DS_Store
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/issuetracker/IssuetrackerApplication.java
  BE/src/main/java/kr/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueLabels.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueMembers.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/GitHubUser.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/LoginResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/TokenRequest.java
  BE/src/main/java/kr/codesquad/issuetracker/dto/TokenRespond.java
  BE/src/main/java/kr/codesquad/issuetracker/jwt/Jwt.java
  BE/src/main/java/kr/codesquad/issuetracker/jwt/JwtInterceptor.java
  BE/src/main/java/kr/codesquad/issuetracker/jwt/JwtProvider.java
  BE/src/main/java/kr/codesquad/issuetracker/jwt/OAuthUtils.java
  BE/src/main/java/kr/codesquad/issuetracker/repository/MemberRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/service/GithubOAuthService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MemberService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/oauth.yml
  BE/src/main/resources/templates/index.html
  BE/src/test/java/kr/codesquad/issuetracker/IssuetrackerApplicationTests.java
Labels: review-BE

#92 [Team-05] [Lee] 이슈트래커 BE 1주차 2번째: DB 연관관계 수정, Issue 관련 API 구현
  BE/src/main/java/kr/codesquad/issuetraker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/Comment.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/label/LabelRepository.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/milestone/MilestoneRepository.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/user/User.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/user/UserRepository.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/IssueDetailResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/IssueListResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/MilestoneInfoDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/NewIssueRequestDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/NewIssueResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/UserInfoDto.java
  BE/src/main/java/kr/codesquad/issuetraker/sevice/IssueService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
Labels: review-BE

#78 [team29][BE][제리 & 후] 1주차 두번째 PR
  BE/src/main/java/team29/hoorry/issuetracker/core/common/embeddable/DateTimeTracker.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Comment.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/CommentReaction.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Issue.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/IssueAssignee.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/IssueLabel.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Reaction.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Status.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueLabelResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/domain/Label.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/domain/Member.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/domain/Milestone.java
Labels: review-BE

#83 [team-23(BE)] IssueTracker - OAuth, 환경설정파일 분리, CORS 매핑
  BE/build.gradle
  BE/src/main/java/com/ron2ader/issuetracker/auth/AuthorizationExtractor.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/Login.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/LoginArgumentResolver.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/github/GithubProperties.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/github/GithubToken.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/github/GithubTokenRequest.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/github/GithubUserInfo.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/JwtProperties.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/JwtProvider.java
  BE/src/main/java/com/ron2ader/issuetracker/config/GithubConfig.java
  BE/src/main/java/com/ron2ader/issuetracker/config/JwtConfig.java
  BE/src/main/java/com/ron2ader/issuetracker/config/WebConfig.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/AuthController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/authdto/Tokens.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
  BE/src/main/java/com/ron2ader/issuetracker/service/AuthService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/IssueService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/auth.yml
  BE/src/test/java/com/ron2ader/issuetracker/service/IssueServiceTest.java
Labels: review-BE

#104 [team-25][FE] Dott & Ver 1주차 2번째 PR
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/assets/LogoIMG.svg
  FE/src/components/common/Badge/index.tsx
  FE/src/components/common/Badge/style.ts
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Button/style.ts
  FE/src/components/common/Icon/index.tsx
  FE/src/components/common/Icon/style.ts
  FE/src/components/common/Logo/index.tsx
  FE/src/components/common/Logo/style.ts
  FE/src/components/common/Text/index.tsx
  FE/src/components/common/Text/style.ts
  FE/src/index.tsx
  FE/src/pages/Callback/index.tsx
  FE/src/pages/Callback/style.ts
  FE/src/pages/IssueList/index.tsx
  FE/src/pages/IssueList/style.ts
  FE/src/pages/Login/index.tsx
  FE/src/pages/Login/style.ts
  FE/src/styles/GlobalStyle.ts
  FE/src/styles/style.d.ts
  FE/src/styles/theme.ts
  FE/src/templates/LoginSection/index.tsx
  FE/src/templates/LoginSection/style.ts
  FE/src/types.d.ts
  FE/src/utils/constants.ts
  FE/tsconfig.json
  FE/webpack.common.js
Labels: review-FE

#80 [team-23][FE] nick & otter 이번주 PR
  FE/.babelrc
  FE/.eslintrc.js
  FE/.gitignore
  FE/.prettier.js
  FE/config/webpack.common.js
  FE/config/webpack.dev.js
  FE/config/webpack.prod.js
  FE/package-lock.json
  FE/package.json
  FE/public/assets/img/LogotypeLarge.png
  FE/public/assets/img/LogotypeMedium.png
  FE/public/assets/img/UserImage.png
  FE/public/assets/img/Ximage.png
  FE/public/assets/img/clip.png
  FE/public/index.html
  FE/src/App.tsx
  FE/src/UI/Input.tsx
  FE/src/components/Auth/AuthForm.module.scss
  FE/src/components/Auth/AuthForm.tsx
  FE/src/components/Auth/GithubLoginBtn.module.scss
  FE/src/components/Auth/GithubLoginBtn.tsx
  FE/src/components/Auth/LoginCallback.tsx
  FE/src/components/addIssue/addIssueForm.module.scss
  FE/src/components/addIssue/addIssueForm.tsx
  FE/src/components/addIssue/addIssueInputs.tsx
  FE/src/components/addIssue/commentInput.module.scss
  FE/src/components/addIssue/commentInput.tsx
  FE/src/components/addIssue/index.ts
  FE/src/components/addIssue/titleInput.module.scss
  FE/src/components/addIssue/titleInput.tsx
  FE/src/components/header/header.module.scss
  FE/src/components/header/header.tsx
  FE/src/components/header/index.ts
  FE/src/components/issue/Issue.module.scss
  FE/src/components/issue/Issue.tsx
  FE/src/components/issue/Issues.tsx
  FE/src/components/issue/IssuesNav.module.scss
  FE/src/components/issue/IssuesNav.tsx
  FE/src/components/issue/_layout.scss
  FE/src/components/issueFilter/IssuesFilter.module.scss
  FE/src/components/issueFilter/IssuesFilter.tsx
  FE/src/global.d.ts
  FE/src/index.tsx
  FE/src/pages/addIssue/addIssue.module.scss
  FE/src/pages/addIssue/addIssue.tsx
  FE/src/pages/addIssue/index.ts
  FE/src/pages/auth/AuthPage.module.scss
  FE/src/pages/auth/authPage.tsx
  FE/src/pages/issueList/IssueList.tsx
  FE/src/store/authStore.ts
  FE/src/store/store.ts
  FE/src/styles/_buttons.scss
  FE/src/styles/_utils.scss
  FE/src/styles/_variables.scss
  FE/src/styles/reset.css
  FE/tsconfig.json
Labels: review-FE

#103 [team-34 | dony & hemdi] 1주차 2번째 PR 요청드립니다.
  FE/craco.config.js
  FE/package.json
  FE/src/App.tsx
  FE/src/components/InputMessage/InputMessage.stories.tsx
  FE/src/components/InputMessage/index.tsx
  FE/src/components/InputMessage/style.ts
  FE/src/components/InputMessage/type.ts
  FE/src/components/Logo/Logo.stories.tsx
  FE/src/components/Logo/index.tsx
  FE/src/components/Logo/style.ts
  FE/src/components/TextInput/TextInput.stories.tsx
  FE/src/components/TextInput/index.tsx
  FE/src/components/TextInput/style.ts
  FE/src/components/TextInput/type.ts
  FE/src/components/button/style.ts
  FE/src/components/button/type.ts
  FE/src/hooks/useInputTextValue.tsx
  FE/src/index.tsx
  FE/src/layout/Layout.stories.tsx
  FE/src/layout/index.tsx
  FE/src/layout/style.ts
  FE/src/pages/Login/Login.stories.tsx
  FE/src/pages/Login/index.tsx
  FE/src/pages/Login/style.ts
  FE/src/pages/Login/type.ts
  FE/src/pages/NotFound/NotFound.stories.tsx
  FE/src/pages/NotFound/index.tsx
  FE/src/pages/NotFound/style.ts
  FE/src/router/index.tsx
  FE/src/router/routeUrl.ts
  FE/src/styles/common/color.ts
  FE/yarn.lock
Labels: review-FE

#59 [Team-22 BE] Issue Tracker 프로젝트 1주차(금요일) 리뷰 요청
  be/README.md
  be/build.gradle
  be/src/main/java/codesquad/issuetracker/IssueTrackerApplication.java
  be/src/main/java/codesquad/issuetracker/controller/IssueController.java
  be/src/main/java/codesquad/issuetracker/controller/LabelController.java
  be/src/main/java/codesquad/issuetracker/controller/MemberController.java
  be/src/main/java/codesquad/issuetracker/controller/MileStoneController.java
  be/src/main/java/codesquad/issuetracker/domain/Assignee.java
  be/src/main/java/codesquad/issuetracker/domain/Image.java
  be/src/main/java/codesquad/issuetracker/domain/Issue.java
  be/src/main/java/codesquad/issuetracker/domain/IssueLabel.java
  be/src/main/java/codesquad/issuetracker/domain/IssueStatus.java
  be/src/main/java/codesquad/issuetracker/domain/Label.java
  be/src/main/java/codesquad/issuetracker/domain/Member.java
  be/src/main/java/codesquad/issuetracker/domain/MemberType.java
  be/src/main/java/codesquad/issuetracker/domain/MileStone.java
  be/src/main/java/codesquad/issuetracker/domain/Reply.java
  be/src/main/java/codesquad/issuetracker/domain/enumtype/IssueStatus.java
  be/src/main/java/codesquad/issuetracker/domain/enumtype/MemberType.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueDto.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueDtoList.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueSearchCondition.java
  be/src/main/java/codesquad/issuetracker/dto/label/LabelDto.java
  be/src/main/java/codesquad/issuetracker/dto/label/LabelDtoList.java
  be/src/main/java/codesquad/issuetracker/dto/member/MemberDto.java
  be/src/main/java/codesquad/issuetracker/dto/member/MemberDtoList.java
  be/src/main/java/codesquad/issuetracker/dto/milestone/MileStoneDto.java
  be/src/main/java/codesquad/issuetracker/dto/milestone/MileStoneDtoList.java
  be/src/main/java/codesquad/issuetracker/repository/IssueRepository.java
  be/src/main/java/codesquad/issuetracker/repository/LabelRepository.java
  be/src/main/java/codesquad/issuetracker/repository/MemberRepository.java
  be/src/main/java/codesquad/issuetracker/repository/MileStoneRepository.java
  be/src/main/java/codesquad/issuetracker/service/IssueService.java
  be/src/main/java/codesquad/issuetracker/service/LabelService.java
  be/src/main/java/codesquad/issuetracker/service/MemberService.java
  be/src/main/java/codesquad/issuetracker/service/MileStoneService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: review-BE

#105 [Team18, Sonya] Login(SignIn) 페이지, IssueList 페이지 구현
  FE/tracker/.gitignore
  FE/tracker/README.md
  FE/tracker/package-lock.json
  FE/tracker/package.json
  FE/tracker/public/cuticon.ico
  FE/tracker/public/index.html
  FE/tracker/public/manifest.json
  FE/tracker/public/robots.txt
  FE/tracker/src/App.css
  FE/tracker/src/App.js
  FE/tracker/src/App.test.js
  FE/tracker/src/components/context/AuthContext.jsx
  FE/tracker/src/components/issueList/issueList.tsx
  FE/tracker/src/components/signIn/canvas.jsx
  FE/tracker/src/components/signIn/copyright.jsx
  FE/tracker/src/components/signIn/signIn.jsx
  FE/tracker/src/index.css
  FE/tracker/src/index.js
  FE/tracker/src/logo.svg
  FE/tracker/src/mui-style/theme.jsx
  FE/tracker/src/reportWebVitals.js
  FE/tracker/src/setupTests.js
  FE/tracker/src/store/init.js
Labels: review-FE

#70 [Team-28][BE][Yan] 1주차 두번째 PR
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/auth/GithubOauth.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/dto/AccessTokenRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/dto/AccessTokenResponseDto.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/dto/UserProfile.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/service/GithubService.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/utils/OauthUtils.java
  BE/src/main/java/kr/codesquad/issuetracker/config/JpaConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/BaseTimeEntity.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueLabels.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/IssueMembers.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/image/CommentImage.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Status.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Color.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/member/MemberRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/service/UserService.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/UserController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/user/UserResponseDto.java
  BE/src/main/resources/application-oauth.yml
  BE/src/main/resources/application.yml
Labels: review-BE

#76 [team-19][BE][루시드] IssueTracker 1주차 2차 PR
  .github/workflows/main.yml
  BE/.gitignore
  BE/appspec.yml
  BE/scripts/deploy_was.sh
  BE/scripts/health_check.sh
  BE/scripts/run_new_was.sh
  BE/scripts/switch.sh
  BE/src/main/java/com/codesquad/issueTracker/User/presentation/UserController.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/application/OAuthService.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/domain/RedisTokenRepository.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/GitHubOAuthClientServer.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/JwtTokenProvider.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/dto/OAuthTokenRequest.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/infrastructure/dto/OAuthTokenResponse.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/presentation/OAuthController.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/presentation/dto/OAuthLoginResponse.java
  BE/src/main/java/com/codesquad/issueTracker/authentication/presentation/interceptor/AuthenticationInterceptor.java
  BE/src/main/java/com/codesquad/issueTracker/config/WebConfig.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/issueTracker/authentication/presentation/OAuthControllerTest.java
Labels: review-BE

#93 [FE][team-19] 칸 & 제이미 1주차 두번째 PR
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/src/assets/icons/index.tsx
  FE/src/assets/images/index.tsx
  FE/src/assets/styles/mixin.ts
  FE/src/assets/styles/styled.d.ts
  FE/src/assets/styles/theme.ts
  FE/src/components/common/Button/Button.style.ts
  FE/src/components/common/Button/constants.ts
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Icon/Icon.style.ts
  FE/src/components/common/Icon/constants.ts
  FE/src/components/common/Icon/index.tsx
  FE/src/components/common/Image/constants.ts
  FE/src/components/common/Image/index.tsx
  FE/src/constants/api.ts
  FE/src/constants/errorMessage.ts
  FE/src/hooks/useAxios.ts
  FE/src/hooks/useLocalStorage.ts
  FE/src/pages/Error/Error.style.ts
  FE/src/pages/Error/NotFound.tsx
  FE/src/pages/Error/index.tsx
  FE/src/pages/Loading/Loading.style.ts
  FE/src/pages/Loading/index.tsx
  FE/src/pages/Login/Login.style.ts
  FE/src/pages/Login/constants.ts
  FE/src/pages/Login/index.tsx
  FE/src/pages/LoginCallback/index.tsx
  FE/src/pages/NotFound/index.tsx
  FE/src/router/ProtectedRoute.tsx
  FE/src/router/RedirectRoute.tsx
  FE/src/router/index.tsx
  FE/src/setupProxy.js
  FE/src/type/index.ts
Labels: review-FE

#82 [team-31][FE] Maeve & JinJeon 1주차 두 번째 PR
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/Component/Header/index.tsx
  fe/src/Component/Home/IssueCell/IssueCell.styled.tsx
  fe/src/Component/Home/IssueCell/IssueCell.tsx
  fe/src/Component/Home/IssueCells/IssueCells.tsx
  fe/src/Component/Home/index.tsx
  fe/src/Component/Loading/Loading.styled.tsx
  fe/src/Component/Loading/index.tsx
  fe/src/Component/Login/Login.styled.tsx
  fe/src/Component/Login/index.tsx
  fe/src/Component/Main/index.tsx
  fe/src/Component/NewIssue/NewIssue.styled.tsx
  fe/src/Component/NewIssue/NewIssueContent/NewIssueContent.styled.tsx
  fe/src/Component/NewIssue/NewIssueContent/index.tsx
  fe/src/Component/NewIssue/NewIssueMain.tsx
  fe/src/Component/NewIssue/NewIssueOptions/NewIssueOptions.styled.tsx
  fe/src/Component/NewIssue/NewIssueOptions/index.tsx
  fe/src/Component/NewIssue/index.tsx
  fe/src/Component/UserImg/UserImg.styled.tsx
  fe/src/Component/UserImg/index.tsx
  fe/src/Img/user2.jpeg
  fe/src/Router/index.tsx
  fe/src/Styles/theme.tsx
  fe/src/index.tsx
Labels: review-FE

#63 [FE][Geon, Dori] 1주차 2번째 PR
  fe/src/App.tsx
  fe/src/assets/icons/angle-down.svg
  fe/src/assets/icons/box-close-issue.svg
  fe/src/assets/icons/cancel-x.svg
  fe/src/assets/icons/circle-check.svg
  fe/src/assets/icons/circle-empty.svg
  fe/src/assets/icons/edit.svg
  fe/src/assets/icons/exclamation-blue.svg
  fe/src/assets/icons/exclamation-normal.svg
  fe/src/assets/icons/label.svg
  fe/src/assets/icons/milestone.svg
  fe/src/assets/icons/paperclip.svg
  fe/src/assets/icons/pauseCircle.svg
  fe/src/assets/icons/plus.svg
  fe/src/assets/icons/refresh.svg
  fe/src/assets/icons/search.svg
  fe/src/assets/icons/smile-emoji.svg
  fe/src/assets/icons/trash.svg
  fe/src/components/Card/index.tsx
  fe/src/components/Card/style.ts
  fe/src/components/Common/Button/index.tsx
  fe/src/components/Common/Button/style.ts
  fe/src/hoc/PrivateRoute.tsx
  fe/src/hoc/PublicRoute.tsx
  fe/src/hooks/useForm.ts
  fe/src/pages/Login/LoginForm.tsx
  fe/src/pages/Login/index.tsx
  fe/src/pages/Login/stlye.ts
  fe/src/pages/NotAllow/index.tsx
  fe/src/pages/Signup/SignUpForm.tsx
  fe/src/pages/Signup/index.tsx
  fe/src/pages/index.ts
  fe/src/styles/GlobalStyles.ts
  fe/src/styles/styled.d.ts
  fe/src/styles/theme.ts
  fe/src/styles/theme/color.ts
  fe/src/styles/theme/font.ts
  fe/src/styles/theme/icon.ts
  fe/src/styles/theme/index.ts
Labels: review-FE

#102 [Team-35][BE][쿠킴] PR 리뷰 적용과 로그인 구현
  .github/workflows/back-deploy.yaml
  be/build.gradle
  be/deploy.sh
  be/src/main/java/dev/kukim/issues/IssuesApplication.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/LoginController.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/request/TokenRequest.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/response/GithubUserResponse.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/response/LoginResponse.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/response/TokenResponse.java
  be/src/main/java/dev/kukim/issues/user/auth/mapper/LoginResponseMapper.java
  be/src/main/java/dev/kukim/issues/user/auth/property/GithubProperty.java
  be/src/main/java/dev/kukim/issues/user/auth/service/GithubOAuth.java
  be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
  be/src/main/java/dev/kukim/issues/user/auth/service/LoginTokenGenerator.java
  be/src/main/java/dev/kukim/issues/user/user/domain/User.java
  be/src/main/java/dev/kukim/issues/user/user/domain/repository/UserRepository.java
  be/src/main/java/dev/kukim/issues/user/user/mapper/UserMapper.java
  be/src/main/resources/application-local.yml
  be/src/main/resources/application-prod.yml
  be/src/main/resources/application.yml
  be/src/main/resources/auth/auth.yml
  be/src/main/resources/logback-spring.xml
Labels: review-BE

#87 [team-07] [Hwi & 땃쥐] issuetracker 2차 PR
  BE/build.gradle
  BE/src/main/java/com/codesquad/issuetracker/domain/Comment.java
  BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
  BE/src/test/java/com/codesquad/issuetracker/domain/LabelColorTest.java
Labels: review-BE

#73 [team-08][BE] Issue Tracker 요구사항 분석, 프로젝트 세팅, OAuth JWT를 이용한 로그인 기능 구현 (미완)
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/be/codesquad/issuetracker/IssuetrackerApplication.java
  src/main/java/be/codesquad/issuetracker/oauth/GithubOAuthClient.java
  src/main/java/be/codesquad/issuetracker/oauth/JwtFactory.java
  src/main/java/be/codesquad/issuetracker/oauth/LoginController.java
  src/main/java/be/codesquad/issuetracker/oauth/LoginService.java
  src/main/java/be/codesquad/issuetracker/oauth/dto/GithubToken.java
  src/main/java/be/codesquad/issuetracker/oauth/dto/GithubUser.java
  src/main/java/be/codesquad/issuetracker/user/User.java
  src/main/java/be/codesquad/issuetracker/user/UserRepository.java
  src/main/resources/application.yml
  src/test/java/be/codesquad/issuetracker/IssuetrackerApplicationTests.java
Labels: review-BE

#90 [TEAM-28][옐로우 & 난정]1주차 금요일 PR
  FE/.eslintrc.js
  FE/src/App.tsx
  FE/src/GlobalStyles.tsx
  FE/src/assets/icons/Icon.tsx
  FE/src/assets/icons/svgs/index.ts
  FE/src/common/Button.tsx
  FE/src/common/TextInput.tsx
  FE/src/constants/index.ts
  FE/src/login/LoginPage.tsx
  FE/tsconfig.json
  FE/webpack.config.js
Labels: review-FE

#60 [Team-04][Android][Linus_Jay][1주차 금요일 두번째 PR]
  app/build.gradle
  app/src/androidTest/java/com/example/issu_tracker/ExampleInstrumentedTest.kt
  app/src/main/java/com/example/issu_tracker/data/Comment.kt
  app/src/main/java/com/example/issu_tracker/data/FilterCondition.kt
  app/src/main/java/com/example/issu_tracker/data/Issue.kt
  app/src/main/java/com/example/issu_tracker/data/User.kt
  app/src/main/java/com/example/issu_tracker/data/repository/HomeRepository.kt
  app/src/main/java/com/example/issu_tracker/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/issu_tracker/di/RepositoryModule.kt
  app/src/main/java/com/example/issu_tracker/filter/ConditionBar.kt
  app/src/main/java/com/example/issu_tracker/filter/CustomToolbar.kt
  app/src/main/java/com/example/issu_tracker/filter/FilterFragment.kt
  app/src/main/java/com/example/issu_tracker/filter/FilterViewModel.kt
  app/src/main/java/com/example/issu_tracker/filter/SpinnerAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/account/MyAccountFragment.kt
  app/src/main/java/com/example/issu_tracker/ui/common/Constants.kt
  app/src/main/java/com/example/issu_tracker/ui/common/bndingAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/home/HomeActivity.kt
  app/src/main/java/com/example/issu_tracker/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueFragment.kt
  app/src/main/java/com/example/issu_tracker/ui/label/LabelFragment.kt
  app/src/main/java/com/example/issu_tracker/ui/login/LogInActivity.kt
  app/src/main/java/com/example/issu_tracker/ui/mileStone/MileStoneFragment.kt
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/drawable/round_rectangle_background.xml
  app/src/main/res/drawable/spinner_selected_text.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_filter.xml
  app/src/main/res/layout/item_issue.xml
  app/src/main/res/layout/item_spinner.xml
  app/src/main/res/layout/view_filter_condition.xml
  app/src/main/res/menu/toolbar_menu.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/test/java/com/example/issu_tracker/ExampleUnitTest.kt
  app/src/test/java/com/example/issu_tracker/ui/home/HomeViewModelTest.kt
Labels: review-android

#81 [team-32][BE][산토리&포키] IssueTracker 2차 PR
  be/src/main/java/com/codesquad/issuetracker/auth/application/AuthService.java
  be/src/main/java/com/codesquad/issuetracker/auth/application/JwtProvider.java
  be/src/main/java/com/codesquad/issuetracker/auth/presentation/argumentresolver/Auth.java
  be/src/main/java/com/codesquad/issuetracker/auth/presentation/argumentresolver/AuthArgumentResolver.java
  be/src/main/java/com/codesquad/issuetracker/auth/presentation/interceptor/AuthInterceptor.java
  be/src/main/java/com/codesquad/issuetracker/auth/presentation/interceptor/LoginInterceptor.java
  be/src/main/java/com/codesquad/issuetracker/common/config/AuthConfig.java
  be/src/main/java/com/codesquad/issuetracker/exception/dto/ExceptionResponseDto.java
  be/src/main/java/com/codesquad/issuetracker/exception/handler/AuthExceptionHandler.java
  be/src/main/java/com/codesquad/issuetracker/issue/presentation/controller/IssueController.java
  be/src/main/java/com/codesquad/issuetracker/issue/presentation/dto/IssueSaveRequestDto.java
  be/src/main/java/com/codesquad/issuetracker/label/presentation/controller/LabelController.java
  be/src/main/java/com/codesquad/issuetracker/label/presentation/dto/LabelSaveRequestDto.java
  be/src/main/java/com/codesquad/issuetracker/milestone/presentation/controller/MilestoneController.java
  be/src/main/java/com/codesquad/issuetracker/milestone/presentation/dto/MilestoneSaveRequestDto.java
  be/src/main/java/com/codesquad/issuetracker/user/application/OAuthService.java
  be/src/main/java/com/codesquad/issuetracker/user/application/UserService.java
  be/src/main/java/com/codesquad/issuetracker/user/application/dto/GithubUserInformation.java
  be/src/main/java/com/codesquad/issuetracker/user/domain/User.java
  be/src/main/java/com/codesquad/issuetracker/user/domain/UserRepository.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/controller/OAuthController.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/controller/UserController.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/dto/LoginResponseDto.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/dto/UserJoinFormDto.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/dto/UserJoinRequestDto.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/dto/UserLoginRequestDto.java
  be/src/main/resources/application.yml
Labels: review-BE

#65 [team-07] 1주차 PR 피드백 적용및, Network 관련 구조 리팩토링
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Assets.xcassets/NewColorSet/DividedLine.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/Extension/Bundle+.swift
  iOS/IssueTracker/IssueTracker/Extension/UIColor+.swift
  iOS/IssueTracker/IssueTracker/Extension/UIImage+.swift
  iOS/IssueTracker/IssueTracker/LoginScene/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/LoginScene/View/LoginInputView.swift
  iOS/IssueTracker/IssueTracker/LoginScene/View/OAuthLoginButton.swift
  iOS/IssueTracker/IssueTracker/LoginScene/View/OAuthLoginView.swift
  iOS/IssueTracker/IssueTracker/Manager/AppleManager.swift
  iOS/IssueTracker/IssueTracker/Manager/GitHubManager.swift
  iOS/IssueTracker/IssueTracker/Manager/OAuthManageable.swift
  iOS/IssueTracker/IssueTracker/Network/EndPoint.swift
  iOS/IssueTracker/IssueTracker/Network/EndPoint/EndPoint.swift
  iOS/IssueTracker/IssueTracker/Network/EndPoint/Protocol/EndPointable.swift
  iOS/IssueTracker/IssueTracker/Network/EndPoint/Protocol/HTTPPackageable.swift
  iOS/IssueTracker/IssueTracker/Network/NetworkError.swift
  iOS/IssueTracker/IssueTracker/Network/NetworkService.swift
  iOS/IssueTracker/IssueTracker/Network/OauthNetworkManager.swift
  iOS/IssueTracker/IssueTracker/Network/Service/NetworkService.swift
  iOS/IssueTracker/IssueTracker/Network/Service/Protocol/NetworkServiceable.swift
  iOS/IssueTracker/IssueTracker/Network/URLComponent/GitURLConfiguration.swift
  iOS/IssueTracker/IssueTracker/Network/URLComponent/Protocol/Authenticable.swift
  iOS/IssueTracker/IssueTracker/Network/URLComponent/Protocol/URLConfigurable.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
Labels: review-iOS

#68 [team-12][iOS][Mase-Ebony] 1주 금요일 PR
  .gitignore
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/dependency/DependencyInjector.swift
  IssueTracker/IssueTracker/entity/Token.swift
  IssueTracker/IssueTracker/issue/IssueViewController.swift
  IssueTracker/IssueTracker/login/LoginReactor.swift
  IssueTracker/IssueTracker/network/GithubAPI.swift
  IssueTracker/IssueTracker/network/RequestGithubLogin.swift
  IssueTracker/IssueTracker/present/login/LoginReactor.swift
  IssueTracker/IssueTracker/present/login/LoginView.swift
  IssueTracker/IssueTracker/present/login/LoginViewController.swift
  IssueTracker/IssueTracker/present/main_tab/issue/IssueCoordinator.swift
  IssueTracker/IssueTracker/present/main_tab/issue/IssueViewController.swift
  IssueTracker/IssueTracker/scene/AppCoordinator.swift
  IssueTracker/IssueTracker/scene/SceneDelegate.swift
  IssueTracker/IssueTracker/scene/SceneReactor.swift
  IssueTracker/IssueTrackerTests/IssueTrackerTests.swift
Labels: review-iOS

#95 [BE][team-36] sally 2번째 PR
  BE/build.gradle
  BE/src/main/java/com/sh/issuetracker/config/SwaggerConfig.java
  BE/src/main/java/com/sh/issuetracker/milestone/Milestone.java
  BE/src/main/java/com/sh/issuetracker/milestone/MilestoneApiController.java
  BE/src/main/java/com/sh/issuetracker/milestone/MilestoneRepository.java
  BE/src/main/java/com/sh/issuetracker/milestone/MilestoneService.java
  BE/src/main/java/com/sh/issuetracker/milestone/dto/MilestoneRequest.java
  BE/src/main/java/com/sh/issuetracker/milestone/dto/MilestoneResponse.java
  BE/src/main/java/com/sh/issuetracker/project/Project.java
  BE/src/main/java/com/sh/issuetracker/project/ProjectRepository.java
  BE/src/main/java/com/sh/issuetracker/project/ProjectService.java
  BE/src/main/java/com/sh/issuetracker/user/AuthUser.java
  BE/src/test/java/com/sh/issuetracker/milestone/MilestoneRepositoryTest.java
  README.md
Labels: review-BE

#66 [iOS][team-09] IssueView 구현 일부 마무리 및 SignIn 구조 변경
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Model/NetworkManager.swift
  iOS/IssueTracker/IssueTracker/Common/Model/Protocols/NetworkTargetable.swift
  iOS/IssueTracker/IssueTracker/Common/Model/StubURLSession.swift
  iOS/IssueTracker/IssueTracker/Common/Model/UserDefaultManager.swift
  iOS/IssueTracker/IssueTracker/Common/View/PaddingLabel.swift
  iOS/IssueTracker/IssueTracker/Common/View/TabBarController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/IssueItem.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueCollectionHeaderView.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueCollectionView.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Label/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/MileStone/MilestoneViewController.swift
  iOS/IssueTracker/IssueTracker/MyAccount/MyAccountViewController.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SignInManager.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SignInNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SingInStubURLSession.swift
  iOS/IssueTracker/IssueTracker/SignIn/View/SignInViewController.swift
  iOS/IssueTracker/IssueTracker/SignIn/ViewModel/SignInViewModel.swift
  iOS/IssueTracker/IssueTracker/Utility/Extension/UIColor+Extension.swift
Labels: review-iOS

#64 [Team-03] [Android] [1주차 2번째 PR ]라벨 작성페이지, 이슈리스트 화면 아이템 스와이프 처리, 이슈 작성화면 UI , 이슈 작성 내용 마크다운 Preview 변환 적용, 내 계정 화면 UI,
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/issue_tracker/MainActivity.kt
  Android/app/src/main/java/com/example/issue_tracker/common/Constants.kt
  Android/app/src/main/java/com/example/issue_tracker/domain/model/MyAccount.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/common/ImageBindingAdapter.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/common/IssueCountAdapter.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueAdapter.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueHomeFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/ItemHelper.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/write/IssueWriteFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/label/LabelWriteFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/login/LogInActivity.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/milestone/MileStoneWriteFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/myaccount/MyAccountFragment.kt
  Android/app/src/main/res/drawable/btn_black_center.xml
  Android/app/src/main/res/drawable/btn_black_left_radius.xml
  Android/app/src/main/res/drawable/btn_black_right_radius.xml
  Android/app/src/main/res/drawable/ic_arrow_down.xml
  Android/app/src/main/res/drawable/ic_baseline_add_circle_24.xml
  Android/app/src/main/res/drawable/ic_check_on.xml
  Android/app/src/main/res/drawable/ic_close.xml
  Android/app/src/main/res/drawable/ic_filter_list.xml
  Android/app/src/main/res/drawable/ic_issue_close.xml
  Android/app/src/main/res/drawable/ic_search.xml
  Android/app/src/main/res/layout/activity_log_in.xml
  Android/app/src/main/res/layout/fragment_issue_home.xml
  Android/app/src/main/res/layout/fragment_issue_write.xml
  Android/app/src/main/res/layout/fragment_label_write.xml
  Android/app/src/main/res/layout/fragment_my_account.xml
  Android/app/src/main/res/layout/issue_popup_window.xml
  Android/app/src/main/res/layout/item_issues.xml
  Android/app/src/main/res/navigation/navigation_main.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles.xml
Labels: review-android

#107 [team-24][FE][JS&S]1주차 2번째 PR
  .github/workflows/gradle.yml
  .github/workflows/node.js.yml
  FE/issuetracker/src/App.tsx
  FE/issuetracker/src/Router.tsx
  FE/issuetracker/src/assets/fonts/icomoon.eot
  FE/issuetracker/src/assets/fonts/icomoon.svg
  FE/issuetracker/src/assets/fonts/icomoon.ttf
  FE/issuetracker/src/assets/fonts/icomoon.woff
  FE/issuetracker/src/assets/images/UserImageLarge.svg
  FE/issuetracker/src/assets/images/UserImageLarge2.svg
  FE/issuetracker/src/assets/images/UserImageSmall.svg
  FE/issuetracker/src/assets/style.css
  FE/issuetracker/src/components/Issue/InputComment.tsx
  FE/issuetracker/src/components/Issue/IssueComment.tsx
  FE/issuetracker/src/components/Issue/IssueCommentSection.tsx
  FE/issuetracker/src/components/Issue/IssueDetail.tsx
  FE/issuetracker/src/components/Issue/IssueSidebar.tsx
  FE/issuetracker/src/components/Issue/IssueTitle.tsx
  FE/issuetracker/src/components/Issue/TitleButton.tsx
  FE/issuetracker/src/components/Issue/index.tsx
  FE/issuetracker/src/components/Issue/styled.index.js
  FE/issuetracker/src/components/Issue/styled.inputComment.js
  FE/issuetracker/src/components/Issue/styled.issueComment.js
  FE/issuetracker/src/components/Issue/styled.issueCommentSection.js
  FE/issuetracker/src/components/Issue/styled.issueDetail.js
  FE/issuetracker/src/components/Issue/styled.issueSidebar.js
  FE/issuetracker/src/components/Issue/styled.issueTitle.js
  FE/issuetracker/src/components/Issue/styled.titleButton.js
  FE/issuetracker/src/components/IssueList/Issue.tsx
  FE/issuetracker/src/components/IssueList/Issues.tsx
  FE/issuetracker/src/components/IssueList/index.tsx
  FE/issuetracker/src/components/IssueList/styled.index.js
  FE/issuetracker/src/components/IssueList/styled.issue.js
  FE/issuetracker/src/components/IssueList/styled.issues.js
  FE/issuetracker/src/components/LabelPage/LabelItem.tsx
  FE/issuetracker/src/components/LabelPage/LabelList.tsx
  FE/issuetracker/src/components/LabelPage/LabelTop.tsx
  FE/issuetracker/src/components/LabelPage/NewLabelList.tsx
  FE/issuetracker/src/components/LabelPage/index.tsx
  FE/issuetracker/src/components/LabelPage/styled.index.ts
  FE/issuetracker/src/components/LabelPage/styled.labelItem.ts
  FE/issuetracker/src/components/LabelPage/styled.labelList.ts
  FE/issuetracker/src/components/LabelPage/styled.labelTop.ts
  FE/issuetracker/src/components/LabelPage/styled.newLabelList.ts
  FE/issuetracker/src/components/common/Common.tsx
  FE/issuetracker/src/components/common/LabelAndMileStoneBtns/index.tsx
  FE/issuetracker/src/components/common/LabelAndMileStoneBtns/styled.index.tsx
  FE/issuetracker/src/components/header/index.tsx
  FE/issuetracker/src/components/header/styled.index.tsx
  FE/issuetracker/src/components/milestone/Index.tsx
  FE/issuetracker/src/components/milestone/styled.index.tsx
  FE/issuetracker/src/components/newIssue/index.tsx
  FE/issuetracker/src/components/newIssue/styled.index.tsx
  FE/issuetracker/src/design/icons.js
  FE/issuetracker/src/design/theme.js
  FE/issuetracker/src/react-app-env.d.ts
  FE/issuetracker/src/utils/util.ts
Labels: review-FE

#69 [Team-08][iOS] ViewModel 구현 및 의존성 분리
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Application/AppFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Application/AppFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/Flow/LoginFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/Flow/LoginFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/View/LoginView.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/View/LoginViewController.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Common/View/LoginButton.swift
  ios/IssueTracker/Podfile.lock
Labels: review-iOS

#88 [Team 13] Github Secret으로 비밀정보 숨기기, 네트워킹 모듈 구현, PR 목록 View-ViewModel 설계
  .github/workflows/xcode_test.yml
  .gitignore
  PRTracker.xcodeproj/project.pbxproj
  PRTracker/PRTracker.entitlements
  PRTracker/Resource/Assets.xcassets/Colors/Contents.json
  PRTracker/Resource/Assets.xcassets/Colors/CustomBlack.colorset/Contents.json
  PRTracker/Resource/Assets.xcassets/Colors/Gray1.colorset/Contents.json
  PRTracker/Resource/Assets.xcassets/Colors/Separator1.colorset/Contents.json
  PRTracker/Resource/Assets.xcassets/Icons/Contents.json
  PRTracker/Resource/Assets.xcassets/Icons/checkmark.circle.fill.symbolset/Contents.json
  PRTracker/Resource/Assets.xcassets/Icons/checkmark.circle.fill.symbolset/checkmark.circle.fill.svg
  PRTracker/Resource/Assets.xcassets/Icons/checkmark.circle.symbolset/Contents.json
  PRTracker/Resource/Assets.xcassets/Icons/checkmark.circle.symbolset/checkmark.circle.svg
  PRTracker/Resource/Assets.xcassets/Icons/line.3.horizontal.decrease.circle.fill.symbolset/Contents.json
  PRTracker/Resource/Assets.xcassets/Icons/line.3.horizontal.decrease.circle.fill.symbolset/line.3.horizontal.decrease.circle.fill.svg
  PRTracker/Resource/Assets.xcassets/Icons/line.3.horizontal.decrease.circle.symbolset/Contents.json
  PRTracker/Resource/Assets.xcassets/Icons/line.3.horizontal.decrease.circle.symbolset/line.3.horizontal.decrease.circle.svg
  PRTracker/Resource/Base.lproj/Main.storyboard
  PRTracker/Source/Common/KeyChainService.swift
  PRTracker/Source/Common/Logger.swift
  PRTracker/Source/Common/MockDataService.swift
  PRTracker/Source/Common/NSNotification+Extension.swift
  PRTracker/Source/Common/NetworkService.swift
  PRTracker/Source/Login/Model/AppleLoginManager.swift
  PRTracker/Source/Login/Model/GitHubLoginManager.swift
  PRTracker/Source/Login/Model/KeyChainManger.swift
  PRTracker/Source/Login/Model/OAuthManger.swift
  PRTracker/Source/Login/Model/PullManager.swift
  PRTracker/Source/Login/Model/RepoManager.swift
  PRTracker/Source/Login/Model/TokenResponse.swift
  PRTracker/Source/Login/Model/UserManger.swift
  PRTracker/Source/Login/View/ViewController.swift
  PRTracker/Source/PR_Listing/Model/Pull.swift
  PRTracker/Source/PR_Listing/Model/PullListModel.swift
  PRTracker/Source/PR_Listing/Model/Repo.swift
  PRTracker/Source/PR_Listing/View/CustomBarButton .swift
  PRTracker/Source/PR_Listing/View/LabelView.xib
  PRTracker/Source/PR_Listing/View/ListingTableView.swift
  PRTracker/Source/PR_Listing/View/ListingViewController.swift
  PRTracker/Source/PR_Listing/View/PullListTableViewCell.swift
  PRTracker/Source/PR_Listing/View/PullListTableViewController.swift
  PRTracker/Source/PR_Listing/View/PullListViewController.swift
  PRTracker/Source/PR_Listing/ViewModel/ListingViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/PRTableCellViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/PullListViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/PullTableCellViewModel.swift
  PRTracker/Supporting/AppDelegate.swift
  PRTracker/Supporting/SceneDelegate.swift
  create_secrets.rb
Labels: review-iOS

#110 [Team-30] [BE] 2주차 첫 번째 PR
  BE/src/main/java/codesquad/backend/issuetracker/BeApplication.java
  BE/src/main/java/codesquad/backend/issuetracker/common/config/WebConfig.java
  BE/src/main/java/codesquad/backend/issuetracker/exception/AuthException.java
  BE/src/main/java/codesquad/backend/issuetracker/exception/AuthExceptionHandler.java
  BE/src/main/java/codesquad/backend/issuetracker/exception/ErrorCode.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/GithubOAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/JwtFactory.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/OAuthService.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/AuthInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/CommonInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/RefreshInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubLoginUserDto.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubUser.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/TokenType.java
  BE/src/main/java/codesquad/backend/issuetracker/user/domain/User.java
  BE/src/main/java/codesquad/backend/issuetracker/user/infrastructure/UserRepository.java
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/backend/issuetracker/oauth/JwtTest.java
Labels: review-BE

#108 [Team-21][BE][루이1세] 1주차 두번째 PR
  BE/.gitignore
  BE/build.gradle
  BE/gradlew
  BE/gradlew.bat
  BE/src/main/java/louie/hanse/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/louie/hanse/issuetracker/controller/OAuthController.java
  BE/src/main/java/louie/hanse/issuetracker/domain/Comment.java
  BE/src/main/java/louie/hanse/issuetracker/domain/Issue.java
  BE/src/main/java/louie/hanse/issuetracker/domain/IssueLabel.java
  BE/src/main/java/louie/hanse/issuetracker/domain/IssueManager.java
  BE/src/main/java/louie/hanse/issuetracker/domain/Label.java
  BE/src/main/java/louie/hanse/issuetracker/domain/Member.java
  BE/src/main/java/louie/hanse/issuetracker/domain/Milestone.java
  BE/src/main/java/louie/hanse/issuetracker/domain/Status.java
  BE/src/main/java/louie/hanse/issuetracker/exception/MemberNotFoundException.java
  BE/src/main/java/louie/hanse/issuetracker/jwt/JwtProperties.java
  BE/src/main/java/louie/hanse/issuetracker/jwt/JwtProvider.java
  BE/src/main/java/louie/hanse/issuetracker/oauth/GithubAccessToken.java
  BE/src/main/java/louie/hanse/issuetracker/oauth/GithubAccessTokenRequest.java
  BE/src/main/java/louie/hanse/issuetracker/oauth/GithubUser.java
  BE/src/main/java/louie/hanse/issuetracker/oauth/LoginController.java
  BE/src/main/java/louie/hanse/issuetracker/oauth/OAuthProperties.java
  BE/src/main/java/louie/hanse/issuetracker/oauth/OAuthService.java
  BE/src/main/java/louie/hanse/issuetracker/repository/MemberRepository.java
  BE/src/main/java/louie/hanse/issuetracker/service/MemberService.java
  BE/src/main/java/louie/hanse/issuetracker/service/OAuthService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/louie/hanse/issuetracker/IssueTrackerApplicationTests.java
Labels: review-BE

#126 [Team-28][BE][Yan] 2주차 첫번째 PR
  BE/src/main/java/kr/codesquad/issuetracker/auth/GithubOauth.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/annotation/LoginVerify.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/annotation/LoginVerifyResolver.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/dto/AccessTokenRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/service/GithubService.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/utils/OauthUtils.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/utils/Utils.java
  BE/src/main/java/kr/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/BaseTimeEntity.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Status.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/image/Image.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/member/MemberRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/exception/CustomException.java
  BE/src/main/java/kr/codesquad/issuetracker/exception/ErrorMessage.java
  BE/src/main/java/kr/codesquad/issuetracker/exception/ErrorResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/exception/handler/GlobalExceptionHandler.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MemberService.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/MemberController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/UserController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/member/MemberResponseDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/user/UserResponseDto.java
  BE/src/main/resources/application-oauth.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
Labels: review-BE

#130 [team-27][FE] 포키 & 지미 2주차 1번째 PR
  fe/.eslintrc.cjs
  fe/src/App.tsx
  fe/src/components/Icons/DropDown.tsx
  fe/src/components/common/DropDownMenu.tsx
  fe/src/components/common/FilterBar.tsx
  fe/src/components/common/Indicator.tsx
  fe/src/components/common/LargeLabel.tsx
  fe/src/components/common/Panel.tsx
  fe/src/components/common/Panel/Panel.tsx
  fe/src/components/common/Panel/PanelInterface.ts
  fe/src/components/common/Panel/PanelMenuItem.tsx
  fe/src/components/common/ProgressIndicator.tsx
  fe/src/components/common/RadioOptionSelection.tsx
  fe/src/components/common/SmallLabel.tsx
  fe/src/components/common/TextArea.tsx
  fe/src/components/common/Thumbnail.tsx
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/button/RadioButton.tsx
  fe/src/components/common/button/TextButton.tsx
  fe/src/components/common/filterBar/FilterBar.tsx
  fe/src/components/common/filterBar/FilterBarInput.tsx
  fe/src/components/common/filterBar/FilterBarInterface.ts
  fe/src/components/common/label/LargeLabel.tsx
  fe/src/components/common/label/SmallLabel.tsx
  fe/src/components/common/progress/ProgressIndicator.tsx
  fe/src/components/common/progress/ProgressInfo.tsx
  fe/src/components/common/progress/progressInterface.ts
  fe/src/components/common/radioOptionSelection/RadioOption.tsx
  fe/src/components/common/radioOptionSelection/RadioOptionSelection.tsx
  fe/src/constants/buttonStyle.ts
  fe/src/constants/dropDownMenuStyle.ts
  fe/src/constants/filterBarStyle.ts
  fe/src/constants/filterBarText.ts
  fe/src/constants/labelStyle.ts
  fe/src/constants/labelText.ts
  fe/src/constants/progressStyle.ts
  fe/src/constants/radioOptionSelectionStyle.ts
  fe/src/constants/textAreaStyle.ts
  fe/src/styles/boxes.ts
Labels: review-FE

#109 [Team-09][BE][테리&벅픽] 1주차 PR 2번째 - 이슈 API 및 로그인 API 작성
  BE/.gitignore
  BE/build.gradle
  BE/docs/issue_tracker_table_create.sql
  BE/src/main/java/com/team09/issue_tracker/comment/Comment.java
  BE/src/main/java/com/team09/issue_tracker/common/CommonResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/Issue.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueAssigneeRepository.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueRepository.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueService.java
  BE/src/main/java/com/team09/issue_tracker/issue/domain/Issue.java
  BE/src/main/java/com/team09/issue_tracker/issue/domain/IssueAssignee.java
  BE/src/main/java/com/team09/issue_tracker/issue/domain/IssueLabel.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueCreateAndUpdateRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueDetailResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueFindByIdResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueListResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueSaveRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/label/Label.java
  BE/src/main/java/com/team09/issue_tracker/label/dto/LabelSelectResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/login/controller/LoginController.java
  BE/src/main/java/com/team09/issue_tracker/login/controller/dto/LoginResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/login/jwt/JwtConfig.java
  BE/src/main/java/com/team09/issue_tracker/login/jwt/JwtToken.java
  BE/src/main/java/com/team09/issue_tracker/login/jwt/JwtTokenProvider.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/setup/OauthConfiguration.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/setup/OauthProperties.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/setup/OauthProvider.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/setup/OauthProviderInMemoryRepository.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/token/OauthAccessTokenProvider.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/token/OauthAccessTokenResponse.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/user/OauthUserProfile.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/user/OauthUserProfileProvider.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/user/OauthUserProfileType.java
  BE/src/main/java/com/team09/issue_tracker/login/service/LoginService.java
  BE/src/main/java/com/team09/issue_tracker/member/Member.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberController.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberRepository.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberService.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberType.java
  BE/src/main/java/com/team09/issue_tracker/milestone/Milestone.java
  BE/src/main/resources/application.yml
  BE/src/test/java/com/team09/issue_tracker/issue/IssueCreateRepositoryTest.java
  BE/src/test/java/com/team09/issue_tracker/issue/IssueSelectRepositoryTest.java
Labels: review-BE

#149 [team-20][FE] Millie & J 2주차 1번째 PR
  .github/workflows/gradle.yml
  FE/.babelrc
  FE/.eslintrc
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/assets/fonts/index.ts
  FE/src/components/FilterBar/SearchInput.tsx
  FE/src/components/FilterBar/index.tsx
  FE/src/components/FilterBar/style.ts
  FE/src/components/Header/index.tsx
  FE/src/components/Header/style.ts
  FE/src/components/HomeHeader/index.tsx
  FE/src/components/HomeHeader/style.ts
  FE/src/components/SideBar/index.tsx
  FE/src/components/SideBar/style.ts
  FE/src/components/TabLink/index.tsx
  FE/src/components/TabLink/style.ts
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Button/style.ts
  FE/src/components/common/ContentsHeader/index.tsx
  FE/src/components/common/ContentsHeader/style.ts
  FE/src/components/common/DropDown/DetailsMenu.tsx
  FE/src/components/common/DropDown/index.tsx
  FE/src/components/common/DropDown/style.ts
  FE/src/components/common/Input/index.tsx
  FE/src/components/common/Input/style.ts
  FE/src/components/common/TextArea/index.tsx
  FE/src/components/common/TextArea/style.ts
  FE/src/components/common/UserProfile/index.tsx
  FE/src/components/common/UserProfile/style.ts
  FE/src/icons/DropDownArrow.ts
  FE/src/icons/Label.ts
  FE/src/icons/Milestone.ts
  FE/src/icons/Search.ts
  FE/src/icons/Setting.ts
  FE/src/icons/UserProfile.ts
  FE/src/pages/Home/index.tsx
  FE/src/pages/NewIssue/index.tsx
  FE/src/pages/NewIssue/style.ts
  FE/src/pages/NotFound/index.tsx
  FE/src/styles/common.ts
  FE/src/styles/theme.ts
  FE/src/type/button.type.ts
  FE/src/type/dropDown.type.ts
  FE/src/type/input.type.ts
  FE/src/type/userProfile.type.ts
  FE/src/utils/mode.ts
  FE/webpack.config.js
  FE/webpack/common.js
  FE/webpack/development.js
  FE/webpack/production.js
Labels: review-FE

#154 [TEAM-33][bangtae, 이든][FE]2주차 수요일 PR
  Frontend/public/image/user1.jpeg
  Frontend/src/App.tsx
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Button/style.ts
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/components/DropDown/style.ts
  Frontend/src/components/Header/index.tsx
  Frontend/src/components/Header/style.ts
  Frontend/src/components/IssueTable/IssueItem/index.tsx
  Frontend/src/components/IssueTable/IssueItem/style.ts
  Frontend/src/components/IssueTable/IssueList/index.tsx
  Frontend/src/components/IssueTable/IssueList/style.ts
  Frontend/src/components/IssueTable/IssueMenuBar/index.tsx
  Frontend/src/components/IssueTable/IssueMenuBar/style.ts
  Frontend/src/components/IssueTable/index.tsx
  Frontend/src/components/IssueTable/style.ts
  Frontend/src/components/UserImg/index.tsx
  Frontend/src/components/UserImg/style.ts
  Frontend/src/components/common/Button/index.tsx
  Frontend/src/components/common/Button/style.ts
  Frontend/src/components/common/CheckBox/index.tsx
  Frontend/src/index.tsx
  Frontend/src/pages/Loading/index.tsx
  Frontend/src/pages/Loading/style.ts
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Login/style.ts
  Frontend/src/pages/Main/index.tsx
  Frontend/src/pages/Main/style.ts
  Frontend/src/router/index.tsx
  Frontend/src/style/global.ts
  Frontend/src/style/theme.ts
  Frontend/src/types/images.d.ts
  Frontend/webpack.config.js
Labels: review-FE

#114 [team29][BE][제리 & 후] 2주차 첫번째 PR
  BE/build.gradle
  BE/src/main/java/team29/hoorry/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team29/hoorry/issuetracker/config/WebMvcConfig.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/AuthController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/AuthService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthMemberResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthToken.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthTokenRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/common/BaseTimeEntity.java
  BE/src/main/java/team29/hoorry/issuetracker/core/common/embeddable/DateTimeTracker.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/AuthException.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/EmptyTokenException.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/ExceptionMessage.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/GlobalExceptionHandler.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/InvalidTokenException.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/dto/ErrorResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/interceptor/UserValidateInterceptor.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Comment.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Issue.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/IssueLabel.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueFilter.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueStatusUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueTitleUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssuesStatusUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/CommentResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueDetailResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueLabelResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMemberResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMilestoneResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMilestoneSimpleResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssuesResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/ReactionResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/AccessToken.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtConst.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtGenerator.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtParser.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtValidator.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/RefreshToken.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/dto/JwtResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/domain/Member.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/dto/MemberRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/dto/MemberResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/dto/MembersResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/MilestoneMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/domain/Milestone.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneAddRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneDetailResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestonesResponse.java
Labels: review-BE

#159 [team-18][FE] Sonya
  FE/tracker/.gitignore
  FE/tracker/README.md
  FE/tracker/package-lock.json
  FE/tracker/package.json
  FE/tracker/public/index.html
  FE/tracker/src/App.css
  FE/tracker/src/App.test.js
  FE/tracker/src/components/issueList/IssueLIst.types.tsx
  FE/tracker/src/components/issueList/IssueList.function.tsx
  FE/tracker/src/components/issueList/iissueListTable.tsx
  FE/tracker/src/components/issueList/issueList.tsx
  FE/tracker/src/components/issueList/issueListHead.tsx
  FE/tracker/src/components/issueList/issueListToolbar.tsx
  FE/tracker/src/components/signIn/canvas.jsx
  FE/tracker/src/components/signIn/matrix.jsx
  FE/tracker/src/components/signIn/signIn.jsx
  FE/tracker/src/index.css
  FE/tracker/src/index.js
  FE/tracker/src/logo.svg
  FE/tracker/src/mui-style/muiTheme.jsx
  FE/tracker/src/mui-style/theme.jsx
Labels: review-FE

#145 [Team-30][FE] 2주차 1번째 PR
  FE/.babelrc
  FE/.eslintrc.js
  FE/.gitignore
  FE/config/webpack.common.js
  FE/env/.env
  FE/jest.config.js
  FE/package.json
  FE/src/Router.tsx
  FE/src/__tests__/Button/index.test.jsx
  FE/src/__tests__/Issue/index.test.jsx
  FE/src/apis/login.ts
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/Indicator/Loader/index.tsx
  FE/src/components/Indicator/Loader/style.ts
  FE/src/components/Indicator/ProgressBar/index.tsx
  FE/src/components/Indicator/ProgressBar/style.ts
  FE/src/components/Indicator/index.ts
  FE/src/components/Issue/Item/index.tsx
  FE/src/components/Issue/index.tsx
  FE/src/components/MockTheme.tsx
  FE/src/mocks/handlers/index.js
  FE/src/pages/Callback/index.tsx
  FE/src/pages/Login/index.tsx
  FE/src/recoil/atoms/author.ts
  FE/src/recoil/atoms/user.tsx
  FE/yarn.lock
Labels: review-FE

#152 [Team-35][BE][쿠킴] 마일스톤 전체 조회, 특정 마일스톤 생성, 수정, 삭제 기능 구현
  .github/workflows/front-deploy.yaml
  be/build.gradle
  be/src/main/java/dev/kukim/issues/IssuesApplication.java
  be/src/main/java/dev/kukim/issues/common/domain/BaseTimeEntity.java
  be/src/main/java/dev/kukim/issues/common/domain/Status.java
  be/src/main/java/dev/kukim/issues/common/exception/ElementNotFoundException.java
  be/src/main/java/dev/kukim/issues/common/exception/InvalidSearchRequestParamException.java
  be/src/main/java/dev/kukim/issues/config/WebMvcConfig.java
  be/src/main/java/dev/kukim/issues/error/controller/exceptionControllerAdvice.java
  be/src/main/java/dev/kukim/issues/error/controller/response/ErrorResponse.java
  be/src/main/java/dev/kukim/issues/issue/domain/Issue.java
  be/src/main/java/dev/kukim/issues/milestone/controller/MilestoneController.java
  be/src/main/java/dev/kukim/issues/milestone/controller/request/MilestoneCreateRequest.java
  be/src/main/java/dev/kukim/issues/milestone/controller/request/MilestoneUpdateRequest.java
  be/src/main/java/dev/kukim/issues/milestone/controller/response/MilestoneListResponse.java
  be/src/main/java/dev/kukim/issues/milestone/controller/response/MilestoneResponse.java
  be/src/main/java/dev/kukim/issues/milestone/domain/Milestone.java
  be/src/main/java/dev/kukim/issues/milestone/domain/repository/MileStoneRepository.java
  be/src/main/java/dev/kukim/issues/milestone/exception/MilestoneNotFoundException.java
  be/src/main/java/dev/kukim/issues/milestone/service/MilestoneService.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/LoginInterceptor.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/response/GithubUserResponse.java
  be/src/main/java/dev/kukim/issues/user/auth/exception/AuthorizationException.java
  be/src/main/java/dev/kukim/issues/user/auth/property/GithubProperty.java
  be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
  be/src/main/java/dev/kukim/issues/user/auth/service/LoginTokenGenerator.java
  be/src/main/java/dev/kukim/issues/user/user/domain/User.java
  be/src/main/resources/logback-spring.xml
  be/src/test/java/dev/kukim/issues/IssuesApplicationTests.java
  be/src/test/java/dev/kukim/issues/MysqlTestContainer.java
  be/src/test/java/dev/kukim/issues/milestone/service/MilestoneServiceTest.java
  be/src/test/java/dev/kukim/issues/user/auth/controller/LoginAcceptanceTest.java
  be/src/test/java/dev/kukim/issues/user/auth/service/LoginServiceTest.java
  be/src/test/java/dev/kukim/learning/lombok/builder/BuilderTest.java
  be/src/test/java/dev/kukim/learning/lombok/builder/object/TestUser.java
  be/src/test/java/dev/kukim/learning/lombok/builder/object/TestUser2.java
  be/src/test/java/dev/kukim/learning/lombok/builder/object/TestUser3.java
  be/src/test/resources/application.yml
Labels: review-BE

#112 [Team-22 BE] Issue Tracker 프로젝트 2주차(수요일) 리뷰 요청
  be/README.md
  be/src/main/java/codesquad/issuetracker/IssueTrackerApplication.java
  be/src/main/java/codesquad/issuetracker/config/JpaConfig.java
  be/src/main/java/codesquad/issuetracker/config/JwtConfig.java
  be/src/main/java/codesquad/issuetracker/config/MvcConfig.java
  be/src/main/java/codesquad/issuetracker/config/RedisConfig.java
  be/src/main/java/codesquad/issuetracker/controller/AuthController.java
  be/src/main/java/codesquad/issuetracker/controller/ExceptionController.java
  be/src/main/java/codesquad/issuetracker/controller/IssueController.java
  be/src/main/java/codesquad/issuetracker/controller/LabelController.java
  be/src/main/java/codesquad/issuetracker/controller/MemberController.java
  be/src/main/java/codesquad/issuetracker/controller/MileStoneController.java
  be/src/main/java/codesquad/issuetracker/controller/MilestoneController.java
  be/src/main/java/codesquad/issuetracker/domain/BaseTimeEntity.java
  be/src/main/java/codesquad/issuetracker/domain/Image.java
  be/src/main/java/codesquad/issuetracker/domain/Issue.java
  be/src/main/java/codesquad/issuetracker/domain/Member.java
  be/src/main/java/codesquad/issuetracker/domain/Milestone.java
  be/src/main/java/codesquad/issuetracker/dto/ResponseMessage.java
  be/src/main/java/codesquad/issuetracker/dto/auth/AuthMemberInformation.java
  be/src/main/java/codesquad/issuetracker/dto/auth/LoginResponse.java
  be/src/main/java/codesquad/issuetracker/dto/auth/OAuthAccessToken.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueDto.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueDtoList.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueDtos.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueSearchCondition.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueStatusUpdateForm.java
  be/src/main/java/codesquad/issuetracker/dto/label/LabelDtos.java
  be/src/main/java/codesquad/issuetracker/dto/member/MemberDto.java
  be/src/main/java/codesquad/issuetracker/dto/member/MemberDtos.java
  be/src/main/java/codesquad/issuetracker/dto/milestone/MileStoneDtoList.java
  be/src/main/java/codesquad/issuetracker/dto/milestone/MilestoneDto.java
  be/src/main/java/codesquad/issuetracker/dto/milestone/MilestoneDtos.java
  be/src/main/java/codesquad/issuetracker/exception/InvalidTokenException.java
  be/src/main/java/codesquad/issuetracker/interceptor/AuthInterceptor.java
  be/src/main/java/codesquad/issuetracker/jwt/AccessToken.java
  be/src/main/java/codesquad/issuetracker/jwt/AccessTokenProvider.java
  be/src/main/java/codesquad/issuetracker/jwt/RefreshToken.java
  be/src/main/java/codesquad/issuetracker/jwt/RefreshTokenProvider.java
  be/src/main/java/codesquad/issuetracker/jwt/Token.java
  be/src/main/java/codesquad/issuetracker/jwt/TokenManager.java
  be/src/main/java/codesquad/issuetracker/jwt/TokenProvider.java
  be/src/main/java/codesquad/issuetracker/jwt/TokenType.java
  be/src/main/java/codesquad/issuetracker/jwt/TokenUtils.java
  be/src/main/java/codesquad/issuetracker/mapper/LabelMapper.java
  be/src/main/java/codesquad/issuetracker/mapper/MemberMapper.java
  be/src/main/java/codesquad/issuetracker/mapper/MilestoneMapper.java
  be/src/main/java/codesquad/issuetracker/repository/IssueRepository.java
  be/src/main/java/codesquad/issuetracker/repository/LabelRepository.java
  be/src/main/java/codesquad/issuetracker/repository/MemberRepository.java
  be/src/main/java/codesquad/issuetracker/repository/MileStoneRepository.java
  be/src/main/java/codesquad/issuetracker/repository/MilestoneRepository.java
  be/src/main/java/codesquad/issuetracker/service/IssueService.java
  be/src/main/java/codesquad/issuetracker/service/LabelService.java
  be/src/main/java/codesquad/issuetracker/service/MemberService.java
  be/src/main/java/codesquad/issuetracker/service/MileStoneService.java
  be/src/main/java/codesquad/issuetracker/service/MilestoneService.java
  be/src/main/java/codesquad/issuetracker/service/OAuthService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: review-BE

#134 [Team-35][FE][BB, 럼카] 공통 컴포넌트 개발 / 페이지 레이아웃 생성
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/assets/alert-circle.svg
  fe/src/assets/archive.svg
  fe/src/assets/calendar.svg
  fe/src/assets/check-box-active.svg
  fe/src/assets/check-box-disable.svg
  fe/src/assets/check-box-initial.svg
  fe/src/assets/check-off-circle.svg
  fe/src/assets/check-on-circle.svg
  fe/src/assets/down.svg
  fe/src/assets/edit.svg
  fe/src/assets/logo.svg
  fe/src/assets/milestone.svg
  fe/src/assets/paperclip.svg
  fe/src/assets/plus.svg
  fe/src/assets/refresh.svg
  fe/src/assets/search.svg
  fe/src/assets/smile.svg
  fe/src/assets/tag.svg
  fe/src/assets/trash.svg
  fe/src/assets/x-square.svg
  fe/src/components/IssueDetail/IssueLabel.tsx
  fe/src/components/IssueList/Checkbox.tsx
  fe/src/components/IssueList/FilterBar.tsx
  fe/src/components/IssueList/IssueHeader.tsx
  fe/src/components/IssueList/IssueItem.tsx
  fe/src/components/LabelList/LabelItem.tsx
  fe/src/components/MilestoneList/MilestoneHeader.tsx
  fe/src/components/MilestoneList/MilestoneItem.tsx
  fe/src/components/common/Avatar.tsx
  fe/src/components/common/BlankMessage.tsx
  fe/src/components/common/Button/Button.tsx
  fe/src/components/common/Button/ButtonLink.tsx
  fe/src/components/common/Button/button.style.ts
  fe/src/components/common/DropdownBtn.tsx
  fe/src/components/common/Header.tsx
  fe/src/components/common/Icon.tsx
  fe/src/components/common/Input.tsx
  fe/src/components/common/Label.tsx
  fe/src/components/common/LinearGraph.tsx
  fe/src/components/common/ListContainer.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/common/Modal.tsx
  fe/src/components/common/SubNav.tsx
  fe/src/components/common/Tabs.tsx
  fe/src/components/common/Text.tsx
  fe/src/pages/IssueList.tsx
  fe/src/pages/LabelList.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/MilestoneList.tsx
  fe/src/pages/Template.tsx
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/font.ts
  fe/src/styles/mainHeaderStyle.ts
  fe/src/styles/size.ts
  fe/src/styles/zIndex.ts
Labels: review-FE

#136 [team-32][FE][Geon, Dori] 2주차 수요일 PR
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/core.ts
  fe/src/api/issue.ts
  fe/src/api/label.ts
  fe/src/api/milestone.ts
  fe/src/api/user.ts
  fe/src/assets/icons/index.ts
  fe/src/components/Common/Button/index.tsx
  fe/src/components/Common/Button/style.ts
  fe/src/components/Common/Icon/index.tsx
  fe/src/components/Common/TextInput/index.tsx
  fe/src/components/Common/TextInput/style.ts
  fe/src/components/Loader/index.tsx
  fe/src/constant/api.ts
  fe/src/constant/route.ts
  fe/src/custom.d.ts
  fe/src/hooks/useForm.ts
  fe/src/index.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handler.ts
  fe/src/mocks/issue/data.ts
  fe/src/mocks/issue/index.ts
  fe/src/mocks/label/data.ts
  fe/src/mocks/label/index.ts
  fe/src/mocks/milestone/data.ts
  fe/src/mocks/milestone/index.ts
  fe/src/mocks/user/data.ts
  fe/src/mocks/user/index.ts
  fe/src/pages/Buttons/index.tsx
  fe/src/pages/Icons/index.tsx
  fe/src/pages/Issues/index.tsx
  fe/src/pages/Login/LoginForm.tsx
  fe/src/pages/Login/index.tsx
  fe/src/pages/Login/stlye.ts
  fe/src/pages/Login/style.ts
  fe/src/pages/Signup/SignUpForm.tsx
  fe/src/pages/TextInputs/index.tsx
  fe/src/pages/index.ts
  fe/src/stores/atoms/issueDetail.ts
  fe/src/stores/atoms/issueList.ts
  fe/src/stores/atoms/label.ts
  fe/src/stores/atoms/milestone.ts
  fe/src/stores/atoms/user.ts
  fe/src/stores/selector/issueList.ts
  fe/src/styles/GlobalStyles.ts
  fe/src/styles/styled.d.ts
  fe/src/styles/theme/button.ts
  fe/src/styles/theme/color.ts
  fe/src/styles/theme/font.ts
  fe/src/styles/theme/icon.ts
  fe/src/styles/theme/index.ts
  fe/src/styles/theme/textInput.ts
  fe/src/utils/type.ts
  fe/webpack/webpack.common.js
Labels: review-FE

#138 [Team-34][BE] 2주차 수요일 정기 PR
  BE/.gitignore
  BE/src/main/java/org/codesquad/team34/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthCredential.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthProperties.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthProvider.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/OAuthService.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/dto/OAuthLoginUrl.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubOAuthClient.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubOAuthController.java
  BE/src/main/java/org/codesquad/team34/issuetracker/config/JpaConfig.java
  BE/src/main/java/org/codesquad/team34/issuetracker/config/OAuthConfig.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/MemberRepository.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/MemberService.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/dto/MemberResponse.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/application.yml
Labels: review-BE

#133 [TEAM-28][옐로우 & 난정]2주차 수요일 PR
  FE/.babelrc
  FE/.eslintrc
  FE/.eslintrc.js
  FE/README.md
  FE/config/webpack.common.js
  FE/config/webpack.dev.js
  FE/config/webpack.prod.js
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/addIssue/AddIssuePage.tsx
  FE/src/assets/icons/Icon.tsx
  FE/src/assets/icons/svgs/alertCircle.svg
  FE/src/assets/icons/svgs/archive.svg
  FE/src/assets/icons/svgs/checkBoxActive.svg
  FE/src/assets/icons/svgs/checkBoxDisable.svg
  FE/src/assets/icons/svgs/checkBoxInitial.svg
  FE/src/assets/icons/svgs/chevronDown.svg
  FE/src/assets/icons/svgs/index.ts
  FE/src/assets/icons/svgs/milestone.svg
  FE/src/assets/icons/svgs/plus.svg
  FE/src/assets/icons/svgs/search.svg
  FE/src/assets/icons/svgs/tag.svg
  FE/src/common/Button.tsx
  FE/src/common/ButtonSmallStandard.tsx
  FE/src/common/Layout.tsx
  FE/src/common/Tab.tsx
  FE/src/common/TextInput.tsx
  FE/src/constants/colors.ts
  FE/src/constants/greyscale.ts
  FE/src/constants/index.ts
  FE/src/index.tsx
  FE/src/issueDetail/IssueDetailPage.tsx
  FE/src/issueList/CheckBox.tsx
  FE/src/issueList/EmptyIssueItem.tsx
  FE/src/issueList/FilterBar.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueItem.tsx
  FE/src/issueList/IssueListPage.tsx
  FE/src/issueList/IssueMenu.tsx
  FE/src/issueList/IssueTab.tsx
  FE/src/issueList/Label.tsx
  FE/src/issueList/LinkTabs.tsx
  FE/src/labelList/LabelListPage.tsx
  FE/src/login/Login.tsx
  FE/src/login/LoginPage.tsx
  FE/src/milestoneList/MilestoneListPage.tsx
  FE/src/theme.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: review-FE

#122 [team-07] 홈 화면 구현 및 Scene 흐름 연결
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Assets.xcassets/NewColorSet/IssueAddText.colorset/Contents.json
  iOS/IssueTracker/IssueTracker/DataLayer/DTO/IssueCardDTO.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/EndPoint/EndPoint.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/EndPoint/Protocol/EndPointable.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/EndPoint/Protocol/HTTPPackageable.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/EnumTypes/HTTPMethod.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/EnumTypes/NetworkError.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/Service/NetworkService.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/Service/Protocol/NetworkServiceable.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/URLComponent/GitURLConfiguration.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/URLComponent/Protocol/Authenticable.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/URLComponent/Protocol/URLConfigurable.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Entity/IssueAddListEntity.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/OAuthManager/AppleManager.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/OAuthManager/GitHubManager.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/OAuthManager/OAuthManageable.swift
  iOS/IssueTracker/IssueTracker/Extension/Bundle+.swift
  iOS/IssueTracker/IssueTracker/Extension/UIColor+.swift
  iOS/IssueTracker/IssueTracker/Extension/UIFont+.swift
  iOS/IssueTracker/IssueTracker/Manager/GitHubManager.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/HomeScene/View/Component/BadgeLabel.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/HomeScene/View/Component/IssueAddButton.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/HomeScene/View/Component/NavigationButtonItem.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/HomeScene/View/Component/SelectionLabel.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/HomeScene/View/HomeViewController.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/HomeScene/View/IssuseCardCell.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/HomeScene/View/TableViewDataSource.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/IssueAddScene/View/CommentContainerView.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/IssueAddScene/View/Component/CommentTitleContainerView.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/IssueAddScene/View/Component/DividedLineView.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/IssueAddScene/View/IssueAddViewController.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/IssueAddScene/View/ListCell.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/IssueAddScene/View/ListContainerView.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/EnumTypes/OAuthButtonType.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/Component/OAuthLoginButton.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/LoginInputView.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/OAuthButtonDelegate.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/OAuthLoginView.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/TabBar/TabBarViewController.swift
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
Labels: review-iOS

#123 [Team-08][iOS] GitHub OAuth 구현
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Application/AppDelegate.swift
  ios/IssueTracker/IssueTracker/Application/Coordinator/AppFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Application/Coordinator/Coordinator.swift
  ios/IssueTracker/IssueTracker/Application/Coordinator/DeepLink.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/AppFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  ios/IssueTracker/IssueTracker/Info.plist
  ios/IssueTracker/IssueTracker/IssueTracker.entitlements
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/Flow/LoginFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/View/LoginView.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/View/LoginViewController.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  ios/IssueTracker/Repository/LoginRepository.swift
  settings.gradle
  src/main/java/be/codesquad/issuetracker/IssuetrackerApplication.java
  src/test/java/be/codesquad/issuetracker/IssuetrackerApplicationTests.java
Labels: review-iOS

#151 [iOS][team-16] 네트워크 로직 정리 및 첫 화면 보여주는 분기 처리
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker-Alpha.xcscheme
  IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker-Debug.xcscheme
  IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker-Release.xcscheme
  IssueTracker/IssueTracker/Resource/API/Base/BaseTarget.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPAcceptType.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPContentType.swift
  IssueTracker/IssueTracker/Resource/API/Base/HTTPHeader.swift
  IssueTracker/IssueTracker/Resource/API/Base/NetworkError.swift
  IssueTracker/IssueTracker/Resource/API/Base/Provider.swift
  IssueTracker/IssueTracker/Resource/API/DecodeManager.swift
  IssueTracker/IssueTracker/Resource/API/IssueTrackerTarget.swift
  IssueTracker/IssueTracker/Resource/Repository/IssueTrackingRepository.swift
  IssueTracker/IssueTracker/Resource/Repository/LoginRepository.swift
  IssueTracker/IssueTracker/Resource/Repository/RequestRepository.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/Issue.swift
  IssueTracker/IssueTracker/Source/IssueList/Model/IssueState.swift
  IssueTracker/IssueTracker/Source/IssueList/View/IssueCell.swift
  IssueTracker/IssueTracker/Source/IssueList/View/IssueListViewController.swift
  IssueTracker/IssueTracker/Source/IssueList/ViewModel/IssueListViewModel.swift
  IssueTracker/IssueTracker/Source/Login/LoginViewController.swift
  IssueTracker/IssueTracker/Source/Login/LoginViewModel.swift
  IssueTracker/IssueTracker/Source/Support/Eevironment.swift
  IssueTracker/IssueTracker/Source/Support/LoginViewController.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
  IssueTracker/IssueTracker/Source/TabBarViewController.swift
  IssueTracker/MockIssueTest/MockIssueTest.swift
Labels: review-iOS

#142 [Team-10][iOS][dale, sally] issue api 연결
  GitTuul/GitTuul.xcodeproj/project.pbxproj
  GitTuul/GitTuul.xcodeproj/xcshareddata/xcschemes/GitTuul.xcscheme
  GitTuul/GitTuul/Source/Extension/NotificationName+extension.swift
  GitTuul/GitTuul/Source/Extension/UIButton+extension.swift
  GitTuul/GitTuul/Source/Extension/UIColor+extension.swift
  GitTuul/GitTuul/Source/Extension/UIFont+extension.swift
  GitTuul/GitTuul/Source/LifeCycle/AppDelegate.swift
  GitTuul/GitTuul/Source/LifeCycle/SceneDelegate.swift
  GitTuul/GitTuul/Source/Model/API/EndPoint/GithubEndPoint.swift
  GitTuul/GitTuul/Source/Model/API/NetworkManager.swift
  GitTuul/GitTuul/Source/Model/Domain/Issue.swift
  GitTuul/GitTuul/Source/Model/Domain/Label.swift
  GitTuul/GitTuul/Source/Model/Domain/Milestone.swift
  GitTuul/GitTuul/Source/Model/Entity/IssueEntity.swift
  GitTuul/GitTuul/Source/Model/Entity/LabelEntity.swift
  GitTuul/GitTuul/Source/Model/Entity/MilestoneEntity.swift
  GitTuul/GitTuul/Source/Present/Common/PaddingLabel.swift
  GitTuul/GitTuul/Source/Present/GitTuulTabBarController.swift
  GitTuul/GitTuul/Source/Present/IssueView/IssueCell.swift
  GitTuul/GitTuul/Source/Present/IssueView/IssueHeader.swift
  GitTuul/GitTuul/Source/Present/IssueView/IssueViewController.swift
  GitTuul/GitTuul/Source/Present/IssueView/IssueViewDataSource.swift
  GitTuul/GitTuul/Source/Present/IssueView/LabelCollectionViewCell.swift
  GitTuul/GitTuul/Source/Present/IssueView/LabelCollectionViewDataSource.swift
  GitTuul/GitTuul/Source/Present/IssueView/ViewModel/IssueCellViewModel.swift
  GitTuul/GitTuul/Source/Present/IssueView/ViewModel/IssueViewModel.swift
  GitTuul/GitTuul/Source/Present/LoginView/IdView.swift
  GitTuul/GitTuul/Source/Present/LoginView/LoginViewController.swift
  GitTuul/GitTuul/Source/Present/LoginView/ViewModel/LoginViewModel.swift
  GitTuul/GitTuul/Source/Present/Support/LayoutFactory.swift
Labels: review-iOS

#131 [team-12][iOS][Mase-Ebony] 2주 수요일 PR
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker/common/SceneType.swift
  IssueTracker/IssueTracker/dependency/DependencyInjector.swift
  IssueTracker/IssueTracker/entity/Issue.swift
  IssueTracker/IssueTracker/entity/Token.swift
  IssueTracker/IssueTracker/network/GithubAPI.swift
  IssueTracker/IssueTracker/network/GithubIssueRepository.swift
  IssueTracker/IssueTracker/network/GithubTokenRepository.swift
  IssueTracker/IssueTracker/present/main_tab/issue/IssueCoordinator.swift
  IssueTracker/IssueTracker/present/main_tab/issue/IssueReactor.swift
  IssueTracker/IssueTracker/present/main_tab/issue/IssueTableViewCell.swift
  IssueTracker/IssueTracker/present/main_tab/issue/IssueView.swift
  IssueTracker/IssueTracker/present/main_tab/issue/IssueViewController.swift
  IssueTracker/IssueTracker/scene/AppCoordinator.swift
  IssueTracker/IssueTracker/scene/SceneDelegate.swift
  IssueTracker/IssueTracker/scene/SceneReactor.swift
  IssueTracker/IssueTrackerTests/IssueTrackerTests.swift
  IssueTracker/IssueTrackerTests/mock/GithubIssueRepositoryStub.swift
  IssueTracker/IssueTrackerTests/mock/GithubTokenRepositoryStub.swift
  IssueTracker/IssueTrackerTests/provider_test/GithubAPITest.swift
  IssueTracker/IssueTrackerTests/provider_test/GithubTokenExchangeTest.swift
  IssueTracker/IssueTrackerTests/reactor_test/SceneReactorTest.swift
  IssueTracker/IssueTrackerTests/view_test/IssueViewTest.swift
  IssueTracker/MockIssueList.json
Labels: review-iOS

#111 [team-23(BE)] IssueTracker - S3 image 업로드 기능, Querydsl 설정 및 동적쿼리 초안 작성, github actions로 docker image 배포 스크립트 작성
  .github/ISSUE_TEMPLATE/-be-fe--issue-name---x---x----.md
  .github/workflows/gradle.yml
  BE/build.gradle
  BE/src/main/java/com/ron2ader/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/com/ron2ader/issuetracker/auth/jwt/JwtProvider.java
  BE/src/main/java/com/ron2ader/issuetracker/config/JpaConfig.java
  BE/src/main/java/com/ron2ader/issuetracker/config/S3Config.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/S3UploadController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueCondition.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/Issue.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueAssignee.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueCustomRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueLabel.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueRepositoryImpl.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/label/Label.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/reply/Reply.java
  BE/src/main/java/com/ron2ader/issuetracker/s3/S3Properties.java
  BE/src/main/java/com/ron2ader/issuetracker/service/IssueService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/S3UploadService.java
  BE/src/main/resources/application-local.yml
  BE/src/main/resources/application-prod.yml
  BE/src/test/java/com/ron2ader/issuetracker/service/IssueServiceTest.java
Labels: review-BE

#125 [Team-03] [Android] [2주차 1번째 PR ] 검색모드, 필터모드 구현, 필터모드 Spinner 메뉴, 이슈작성화면 Spinner메뉴 정의, 이슈디테일 화면 UI 구현
  Android/app/build.gradle
  Android/app/src/main/java/com/example/issue_tracker/MainActivity.kt
  Android/app/src/main/java/com/example/issue_tracker/common/Constants.kt
  Android/app/src/main/java/com/example/issue_tracker/domain/model/Comment.kt
  Android/app/src/main/java/com/example/issue_tracker/domain/model/IssueDetail.kt
  Android/app/src/main/java/com/example/issue_tracker/domain/model/IssueState.kt
  Android/app/src/main/java/com/example/issue_tracker/domain/model/SpinnerType.kt
  Android/app/src/main/java/com/example/issue_tracker/domain/model/User.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/HomeViewModel.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/common/LogBindingAdapter.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/common/TimeDiffUtil.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/detail/IssueDetailAdapter.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/detail/IssueDetailFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/detail/IssueDetailViewModel.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueAdapter.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueHomeFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueHomeViewModel.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/write/IssueWriteFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/label/LabelWriteFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/milestone/MileStoneWriteFragment.kt
  Android/app/src/main/res/drawable/ic_close.xml
  Android/app/src/main/res/drawable/ic_emoji.xml
  Android/app/src/main/res/drawable/ic_more.xml
  Android/app/src/main/res/drawable/ic_more_grey.xml
  Android/app/src/main/res/drawable/ic_search.xml
  Android/app/src/main/res/layout/fragment_issue_detail.xml
  Android/app/src/main/res/layout/fragment_issue_home.xml
  Android/app/src/main/res/layout/fragment_issue_write.xml
  Android/app/src/main/res/layout/item_comment_myself.xml
  Android/app/src/main/res/layout/item_comment_other.xml
  Android/app/src/main/res/layout/item_issues.xml
  Android/app/src/main/res/layout/item_spinner_filter.xml
  Android/app/src/main/res/layout/item_spinner_menu.xml
  Android/app/src/main/res/navigation/navigation_main.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles.xml
Labels: review-android

#146 [Team-18][BE] Issue Tracker 프로젝트 2주차 1차 리뷰 요청
  BE/build.gradle
  BE/docker/database-local.yml
  BE/src/main/java/codesquad/issuetracker/domain/user/User.java
  BE/src/main/java/codesquad/issuetracker/domain/user/UserRepository.java
  BE/src/main/java/codesquad/issuetracker/service/OAuthService.java
  BE/src/main/java/codesquad/issuetracker/web/OAuthController.java
  BE/src/main/java/codesquad/issuetracker/web/dto/GithubUserInformation.java
  BE/src/main/java/codesquad/issuetracker/web/dto/LoginResponseDto.java
  BE/src/main/java/codesquad/issuetracker/web/interceptor/AuthInterceptor.java
  BE/src/main/java/codesquad/issuetracker/web/jwt/JwtFactory.java
  BE/src/main/resources/application-dev.yml
Labels: review-BE

#113 [Team-11] 설계와 적용
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/AppDelegate.swift
  IssueTracker/IssueTracker/Container.swift
  IssueTracker/IssueTracker/Entity/Issue.swift
  IssueTracker/IssueTracker/Entity/Label.swift
  IssueTracker/IssueTracker/Entity/Milestone.swift
  IssueTracker/IssueTracker/Entity/State.swift
  IssueTracker/IssueTracker/Extension/UICollectionViewCell+Extension.swift
  IssueTracker/IssueTracker/GitHub/GitHubService.swift
  IssueTracker/IssueTracker/GitHub/NetworkHeader.swift
  IssueTracker/IssueTracker/GitHub/QueryParameter.swift
  IssueTracker/IssueTracker/GitHub/RequestURL.swift
  IssueTracker/IssueTracker/Issue/IssueViewController.swift
  IssueTracker/IssueTracker/Issue/Model/IssueModel.swift
  IssueTracker/IssueTracker/Issue/Service/IssueService.swift
  IssueTracker/IssueTracker/Issue/View/Margins.swift
  IssueTracker/IssueTracker/Login/LoginViewController.swift
  IssueTracker/IssueTracker/Login/OAuthService.swift
  IssueTracker/IssueTracker/Network/NetworkManager.swift
Labels: review-iOS

#140 [iOS][team-9] 리팩토링 및 뷰 구현
  iOS/IssueTracker/.swiftLint.yml
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Model/Mock/DummyData.swift
  iOS/IssueTracker/IssueTracker/Common/Model/Mock/SignInStubURLSessionDataTask.swift
  iOS/IssueTracker/IssueTracker/Common/Model/Mock/StubURLSession.swift
  iOS/IssueTracker/IssueTracker/Common/Model/NetworkService.swift
  iOS/IssueTracker/IssueTracker/Common/Model/Protocols/NetworkTargetProtocol.swift
  iOS/IssueTracker/IssueTracker/Common/Model/Protocols/URLSessionProtocol.swift
  iOS/IssueTracker/IssueTracker/Common/Model/StubURLSession.swift
  iOS/IssueTracker/IssueTracker/Common/View/CustomBarButton.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/View/CustomBarButton.swift
  iOS/IssueTracker/IssueTracker/Issue/View/Delegate/EditingIssueTextFieldDelegate.swift
  iOS/IssueTracker/IssueTracker/Issue/View/Delegate/EditingIssueTextViewDelegate.swift
  iOS/IssueTracker/IssueTracker/Issue/View/EditingIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/View/EditingViewComponents/EditingIssueContentViewComponents.swift
  iOS/IssueTracker/IssueTracker/Issue/View/EditingViewComponents/EditingIssueTitleViewComponents.swift
  iOS/IssueTracker/IssueTracker/Issue/View/EditingViewComponents/EditingIssueViewNavigationItems.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueCollectionHeaderView.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueCollectionView.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewNavigationItems.swift
  iOS/IssueTracker/IssueTracker/Issue/ViewModel/EditingIssueViewModel.swift
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/filter.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/filter.imageset/filter.png
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/mic.fill.symbolset/Contents.json
  iOS/IssueTracker/IssueTracker/Resource/Assets.xcassets/mic.fill.symbolset/mic.fill.svg
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SignInManager.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SignInNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/SignIn/View/SignInViewController.swift
  iOS/IssueTracker/IssueTracker/SignIn/ViewModel/SignInViewModel.swift
  iOS/IssueTracker/IssueTracker/Utility/Extension/UIColor+Extension.swift
  iOS/IssueTracker/IssueTracker/Utility/Extension/UIStackView+Extension.swift
  iOS/IssueTracker/IssueTracker/Utility/Extension/URLSession+Extension.swift
  iOS/IssueTracker/IssueTracker/Utility/Observable.swift
  iOS/IssueTracker/IssueTrackerTests/NetworkServiceTests.swift
  iOS/IssueTracker/IssueTrackerTests/SignInManagerTests.swift
  iOS/IssueTracker/IssueTrackerTests/SignInViewModelTests.swift
  iOS/IssueTracker/Podfile
  iOS/IssueTracker/Podfile.lock
Labels: review-iOS

#185 [TEAM-33][bangtae, 이든][FE]2주차 금요일 PR
  .github/workflows/deploy-frontend.yml
  Frontend/.eslintrc.json
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/assets/icons/UserImageLarge.svg
  Frontend/src/assets/icons/UserImageSmall.svg
  Frontend/src/assets/icons/alert-circle.svg
  Frontend/src/assets/icons/archive.svg
  Frontend/src/assets/icons/bottom-arrow.svg
  Frontend/src/assets/icons/calendar.svg
  Frontend/src/assets/icons/check-box-active.svg
  Frontend/src/assets/icons/check-box-disable.svg
  Frontend/src/assets/icons/check-box-initial.svg
  Frontend/src/assets/icons/check-off-circle.svg
  Frontend/src/assets/icons/check-on-circle.svg
  Frontend/src/assets/icons/edit.svg
  Frontend/src/assets/icons/label.svg
  Frontend/src/assets/icons/milestone.svg
  Frontend/src/assets/icons/paperclip.svg
  Frontend/src/assets/icons/plus.svg
  Frontend/src/assets/icons/refresh-ccw.svg
  Frontend/src/assets/icons/search.svg
  Frontend/src/assets/icons/smile.svg
  Frontend/src/assets/icons/tag.svg
  Frontend/src/assets/icons/trash.svg
  Frontend/src/assets/icons/x-square.svg
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Button/style.ts
  Frontend/src/components/DropDown/Icons/index.tsx
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/components/DropDown/style.ts
  Frontend/src/components/Icons/index.tsx
  Frontend/src/components/Label/index.tsx
  Frontend/src/components/Label/style.ts
  Frontend/src/components/Tap/index.tsx
  Frontend/src/components/Tap/style.ts
  Frontend/src/components/UserImg/index.tsx
  Frontend/src/hooks/useMouse.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Login/style.ts
  Frontend/src/pages/Main/index.tsx
  Frontend/src/pages/Main/style.ts
  Frontend/src/router/index.tsx
  Frontend/src/style/global.ts
  Frontend/src/style/theme.ts
  Frontend/src/types/custom.d.ts
  Frontend/src/types/images.d.ts
  Frontend/src/types/styled.d.ts
  Frontend/tsconfig.json
  Frontend/webpack.config.js
Labels: review-FE

#201 [Team-05] [Lee] 이슈트래커 BE 2주차 2번째: 이슈 검색/필터 구현, 댓글 및 라벨 기능 구현, 예외 처리
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetraker/QueryDslConfiguration.java
  BE/src/main/java/kr/codesquad/issuetraker/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetraker/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/Comment.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/IssueRepositoryCustom.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/IssueRepositoryImpl.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/CommentModificationRequestDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/IssueDetailResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/LabelCreationRequestDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/LabelCreationResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/LabelListResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/NewCommentRequestDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/NewCommentResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/SearchFilterDto.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/CommentNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/IssueNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/LabelNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/MilestoneNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/ResourceNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/RuntimeExceptionHandler.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/UserNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetraker/sevice/IssueService.java
  BE/src/main/java/kr/codesquad/issuetraker/sevice/LabelService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
Labels: review-BE

#181 [Team03] 2주차 두 번째 PR 요청드립니다!
  backend/build.gradle
  backend/src/main/java/com/team03/issuetracker/common/component/LoginMember.java
  backend/src/main/java/com/team03/issuetracker/common/config/DataJpaConfig.java
  backend/src/main/java/com/team03/issuetracker/common/config/DomainMapperConfig.java
  backend/src/main/java/com/team03/issuetracker/common/config/SwaggerConfig.java
  backend/src/main/java/com/team03/issuetracker/common/config/WebConfig.java
  backend/src/main/java/com/team03/issuetracker/issue/api/EmojiController.java
  backend/src/main/java/com/team03/issuetracker/issue/api/IssueController.java
  backend/src/main/java/com/team03/issuetracker/issue/application/IssueService.java
  backend/src/main/java/com/team03/issuetracker/issue/application/LabelService.java
  backend/src/main/java/com/team03/issuetracker/issue/application/impl/IssueServiceImpl.java
  backend/src/main/java/com/team03/issuetracker/issue/application/impl/LabelServiceImpl.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/Issue.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/dto/issue/IssueAddRequest.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/dto/issue/IssueModifyRequest.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/dto/issue/IssueResponse.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/dto/label/LabelResponse.java
  backend/src/main/java/com/team03/issuetracker/issue/repository/IssueRepository.java
  backend/src/main/java/com/team03/issuetracker/milestone/application/MilestoneService.java
  backend/src/main/java/com/team03/issuetracker/milestone/application/impl/MilestoneServiceImpl.java
  backend/src/main/java/com/team03/issuetracker/milestone/domain/Milestone.java
  backend/src/main/java/com/team03/issuetracker/milestone/domain/dto/MilestoneCreateRequest.java
  backend/src/main/java/com/team03/issuetracker/milestone/domain/dto/MilestoneResponse.java
  backend/src/main/java/com/team03/issuetracker/milestone/repository/MilestoneRepository.java
  backend/src/main/java/com/team03/issuetracker/oauth/application/LoginService.java
  backend/src/main/java/com/team03/issuetracker/oauth/interceptor/AuthInterceptor.java
  backend/src/main/java/lombok.config
  backend/src/test/java/com/team03/issuetracker/issue/application/CommentServiceTest.java
  backend/src/test/java/com/team03/issuetracker/issue/application/IssueServiceTest.java
  backend/src/test/java/com/team03/issuetracker/issue/application/LabelServiceTest.java
  backend/src/test/java/com/team03/issuetracker/milestone/application/MilestoneServiceTest.java
Labels: review-BE

#170 [team29][BE][제리 & 후] 2주차 두번째 PR
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/team29/hoorry/issuetracker/config/QuerydslConfig.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthMemberResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/common/search/SearchFilter.java
  BE/src/main/java/team29/hoorry/issuetracker/core/common/search/SearchParamParser.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueCustomRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueRepositoryImpl.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Issue.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/IssueAssignee.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/IssueLabel.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/IssueFilter.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueAssigneesUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueFilter.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueLabelsUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueMilestoneUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueStatusUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueTitleUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssuesSaveRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMilestoneResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMilestoneSimpleResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssuesResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtConst.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtParser.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/LabelController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/LabelRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/dto/LabelAddRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/dto/LabelResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/dto/LabelUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/dto/MemberRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/MilestoneController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/MilestoneCustomRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/MilestoneRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/MilestoneRepositoryImpl.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/domain/Milestone.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneAddRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneUpdateRequest.java
  BE/src/test/java/team29/hoorry/issuetracker/core/common/search/SearchParamParserTest.java
  BE/src/test/java/team29/hoorry/issuetracker/core/issue/dto/IssueFilterTest.java
Labels: review-BE

#206 Be dev[Team-35][BE][쿠킴] 이전 PR 리뷰 적용
  .github/workflows/front-deploy.yaml
  be/build.gradle
  be/src/main/java/dev/kukim/issues/IssuesApplication.java
  be/src/main/java/dev/kukim/issues/config/WebMvcConfig.java
  be/src/main/java/dev/kukim/issues/milestone/controller/request/MilestoneCreateRequest.java
  be/src/main/java/dev/kukim/issues/milestone/controller/request/MilestoneUpdateRequest.java
  be/src/main/java/dev/kukim/issues/milestone/controller/response/MilestoneListResponse.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/response/GithubUserResponse.java
  be/src/main/java/dev/kukim/issues/user/auth/service/LoginTokenGenerator.java
  be/src/main/resources/auth/auth.yml
  be/src/test/java/dev/kukim/issues/milestone/service/MilestoneServiceTest.java
  be/src/test/java/dev/kukim/issues/user/auth/service/LoginServiceTest.java
  be/src/test/java/dev/kukim/learning/testcontainers/mysqlcontainer/Basic2MySQLContainer.java
  be/src/test/java/dev/kukim/learning/testcontainers/mysqlcontainer/Basic3MySQLContainer.java
  be/src/test/java/dev/kukim/learning/testcontainers/mysqlcontainer/BasicMySQLContainer.java
  be/src/test/java/dev/kukim/learning/testcontainers/mysqlcontainer/CustomMySQLContainer.java
  be/src/test/resources/application.yml
  be/src/test/resources/learning.testcontainers/custom.conf.d/custom.cnf
  be/src/test/resources/learning.testcontainers/init.sql
  be/src/test/resources/logback-test.xml
Labels: review-BE

#198 [Team-34][BE] 2주차 금요일 정기 PR
  BE/src/main/java/org/codesquad/team34/issuetracker/common/LoginInterceptor.java
  BE/src/main/java/org/codesquad/team34/issuetracker/config/InterceptorConfig.java
Labels: review-BE

#169 [Team-22 BE] Issue Tracker 프로젝트 2주차(금요일) 리뷰 요청
  be/README.md
  be/src/main/java/codesquad/issuetracker/config/JwtConfig.java
  be/src/main/java/codesquad/issuetracker/config/MvcConfig.java
  be/src/main/java/codesquad/issuetracker/controller/AuthController.java
  be/src/main/java/codesquad/issuetracker/controller/ExceptionControllerAdvice.java
  be/src/main/java/codesquad/issuetracker/controller/MemberController.java
  be/src/main/java/codesquad/issuetracker/domain/Issue.java
  be/src/main/java/codesquad/issuetracker/domain/IssueLabel.java
  be/src/main/java/codesquad/issuetracker/domain/Label.java
  be/src/main/java/codesquad/issuetracker/domain/Milestone.java
  be/src/main/java/codesquad/issuetracker/dto/auth/OAuthAccessToken.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueDto.java
  be/src/main/java/codesquad/issuetracker/dto/issue/IssueSearchCondition.java
  be/src/main/java/codesquad/issuetracker/dto/label/LabelDto.java
  be/src/main/java/codesquad/issuetracker/dto/label/LabelDtos.java
  be/src/main/java/codesquad/issuetracker/dto/member/MemberDto.java
  be/src/main/java/codesquad/issuetracker/dto/member/MemberDtos.java
  be/src/main/java/codesquad/issuetracker/dto/milestone/MilestoneDto.java
  be/src/main/java/codesquad/issuetracker/dto/milestone/MilestoneDtos.java
  be/src/main/java/codesquad/issuetracker/interceptor/AuthInterceptor.java
  be/src/main/java/codesquad/issuetracker/jwt/AccessToken.java
  be/src/main/java/codesquad/issuetracker/jwt/AccessTokenProvider.java
  be/src/main/java/codesquad/issuetracker/jwt/RedisRepository.java
  be/src/main/java/codesquad/issuetracker/jwt/RefreshToken.java
  be/src/main/java/codesquad/issuetracker/jwt/RefreshTokenProvider.java
  be/src/main/java/codesquad/issuetracker/jwt/TokenManager.java
  be/src/main/java/codesquad/issuetracker/jwt/TokenUtils.java
  be/src/main/java/codesquad/issuetracker/mapper/LabelMapper.java
  be/src/main/java/codesquad/issuetracker/mapper/MemberMapper.java
  be/src/main/java/codesquad/issuetracker/mapper/MilestoneMapper.java
  be/src/main/java/codesquad/issuetracker/repository/LabelRepository.java
  be/src/main/java/codesquad/issuetracker/repository/MemberRepository.java
  be/src/main/java/codesquad/issuetracker/service/GithubOAuthClient.java
  be/src/main/java/codesquad/issuetracker/service/IssueService.java
  be/src/main/java/codesquad/issuetracker/service/TokenService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: review-BE

#188 [Team-28][BE][Yan] 2주차 두번째 PR
  BE/src/main/java/kr/codesquad/issuetracker/auth/GithubOauth.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/JwtInterceptor.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/annotation/LoginRequired.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/annotation/LoginVerifyResolver.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/utils/Utils.java
  BE/src/main/java/kr/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/BaseTimeEntity.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Status.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/image/Image.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Color.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/repository/LabelRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/member/repository/MemberRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/repository/MilestoneRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/exception/ErrorMessage.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MemberService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestonesService.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/MilestonesController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/label/LabelDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/label/LabelRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/label/LabelResponseDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/milestone/MilestoneDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/milestone/MilestoneEditRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/milestone/MilestoneRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/milestone/MilestoneResponseDto.java
  BE/src/main/resources/data.sql
Labels: review-BE

#189 [Team-36, BE] Sally 2주차 2번째 PR
  BE/build.gradle
  BE/src/main/java/com/sh/issuetracker/exception/InvalidSearchParamException.java
  BE/src/main/java/com/sh/issuetracker/issue/Issue.java
  BE/src/main/java/com/sh/issuetracker/issue/IssueApiController.java
  BE/src/main/java/com/sh/issuetracker/issue/IssueRepository.java
  BE/src/main/java/com/sh/issuetracker/issue/IssueService.java
  BE/src/main/java/com/sh/issuetracker/issue/IssueStatus.java
  BE/src/main/java/com/sh/issuetracker/issue/dto/IssueResponse.java
  BE/src/main/java/com/sh/issuetracker/issue/search/IssueSearchDto.java
  BE/src/main/java/com/sh/issuetracker/issue/search/IssueSearchParam.java
  BE/src/main/java/com/sh/issuetracker/issue/search/IssueSearchRequest.java
  BE/src/main/java/com/sh/issuetracker/issue/search/LabelSearchDto.java
  BE/src/main/java/com/sh/issuetracker/issue/search/SearchKeyType.java
  BE/src/main/java/com/sh/issuetracker/issue/search/SearchWordMap.java
  BE/src/main/java/com/sh/issuetracker/issuelabel/IssueLabel.java
  BE/src/main/java/com/sh/issuetracker/label/Label.java
  BE/src/main/java/com/sh/issuetracker/label/LabelService.java
  BE/src/main/java/com/sh/issuetracker/label/TextColor.java
  BE/src/main/java/com/sh/issuetracker/label/dto/LabelRequest.java
  BE/src/main/java/com/sh/issuetracker/member/Member.java
  BE/src/main/java/com/sh/issuetracker/member/MemberId.java
  BE/src/main/java/com/sh/issuetracker/milestone/Milestone.java
  BE/src/main/java/com/sh/issuetracker/milestone/MilestoneService.java
  BE/src/main/java/com/sh/issuetracker/user/User.java
  BE/src/test/java/com/sh/issuetracker/IssuetrackerApplicationTests.java
  BE/src/test/java/com/sh/issuetracker/issue/IssueRepositoryTest.java
  BE/src/test/java/com/sh/issuetracker/issue/dto/IssueSearchRequestTest.java
  BE/src/test/java/com/sh/issuetracker/label/LabelRepositoryTest.java
  BE/src/test/java/com/sh/issuetracker/member/MemberRepositoryTest.java
Labels: review-BE

#202 [team-34 | dony & hemdi] 2주차 2번째 PR 요청
  FE/src/assets/icons/icon_milestone.svg
  FE/src/components/DropDown/DropDown.stories.tsx
  FE/src/components/DropDown/Panel/Panel.stories.tsx
  FE/src/components/DropDown/Panel/index.tsx
  FE/src/components/DropDown/Panel/style.ts
  FE/src/components/DropDown/Panel/type.ts
  FE/src/components/DropDown/index.tsx
  FE/src/components/DropDown/type.ts
  FE/src/components/FilterBar/FilterBar.stories.tsx
  FE/src/components/FilterBar/index.tsx
  FE/src/components/FilterBar/style.ts
  FE/src/components/FilterBar/type.ts
  FE/src/components/Header/style.ts
  FE/src/components/IssueList/ListHeader/index.tsx
  FE/src/components/IssueList/ListHeader/style.ts
  FE/src/components/IssueList/ListItem/index.tsx
  FE/src/components/IssueList/ListItem/style.ts
  FE/src/components/IssueList/ListItem/type.ts
  FE/src/components/IssueList/index.tsx
  FE/src/components/IssueList/mockData.ts
  FE/src/components/IssueList/style.ts
  FE/src/components/TextInput/index.tsx
  FE/src/components/TextInput/style.ts
  FE/src/components/TextInput/type.ts
  FE/src/components/UserProfile/index.tsx
  FE/src/components/UserProfile/style.ts
  FE/src/components/UserProfile/type.ts
  FE/src/components/button/Button.stories.tsx
  FE/src/components/button/style.ts
  FE/src/components/button/type.ts
  FE/src/layout/style.ts
  FE/src/pages/IssueList/IssueList.stories.tsx
  FE/src/pages/IssueList/Login.stories.tsx
  FE/src/pages/IssueList/index.tsx
  FE/src/pages/IssueList/style.ts
  FE/src/pages/Loading/index.tsx
  FE/src/pages/Login/index.tsx
Labels: review-FE

#207 [Team-29][FE] 도비 & 도토리 2주차 금 PR
  fe/src/Router/index.tsx
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.tsx
  fe/src/components/Atoms/Milestone/Milestone.stories.tsx
  fe/src/components/Atoms/Milestone/index.styles.ts
  fe/src/components/Atoms/Milestone/index.tsx
  fe/src/components/Molecules/AddIssueForm/index.tsx
  fe/src/components/Molecules/FilterBar/index.tsx
  fe/src/components/Molecules/IssueList/index.tsx
  fe/src/components/Molecules/LoginForm/index.tsx
  fe/src/components/Molecules/SideBar/SideBar.stories.tsx
  fe/src/components/Molecules/SideBar/index.tsx
  fe/src/components/Organisms/Header/index.tsx
  fe/src/components/Organisms/LoginAndRegister/index.tsx
  fe/src/components/Organisms/SignUpForm/index.tsx
  fe/src/components/types.ts
  fe/src/helpers/constants/openCloseFilter.ts
  fe/src/helpers/utils/fetchData.ts
  fe/src/hooks/useInput.tsx
  fe/src/pages/AddIssue.tsx
  fe/src/pages/Issues.tsx
  fe/src/pages/Login/Oauth.tsx
  fe/src/pages/Login/SignUp.tsx
  fe/src/pages/Login/index.tsx
Labels: review-FE

#205 [Team-35][FE][BB, 럼카] Errorboundary 생성 / 리팩토링
  fe/package.json
  fe/src/components/ErrorBoundary.tsx
  fe/src/components/IssueList/FilterBar.tsx
  fe/src/components/IssueList/IssueHeader.tsx
  fe/src/components/IssueList/IssueItem.tsx
  fe/src/components/LabelList/LabelItem.tsx
  fe/src/components/MilestoneList/MilestoneHeader.tsx
  fe/src/components/MilestoneList/MilestoneItem.tsx
  fe/src/components/common/Avatar.tsx
  fe/src/components/common/Button/Button.tsx
  fe/src/components/common/Button/ButtonLink.tsx
  fe/src/components/common/Button/TextButton.tsx
  fe/src/components/common/Button/TextButtonLink.tsx
  fe/src/components/common/Button/button.style.ts
  fe/src/components/common/DropdownBtn.tsx
  fe/src/components/common/Input/Input.style.ts
  fe/src/components/common/Input/Input.tsx
  fe/src/components/common/LinearGraph.tsx
  fe/src/components/common/ListContainer.tsx
  fe/src/components/common/SubNav.tsx
  fe/src/components/common/Tabs.tsx
  fe/src/components/common/Text.tsx
  fe/src/pages/IssueList.tsx
  fe/src/pages/LabelList.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/MilestoneList.tsx
  fe/src/pages/Template.tsx
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/commonStyles.ts
  fe/src/styles/mainHeaderStyle.ts
Labels: review-FE

#187 [FE][team-32][Geon, Dori] 2주차 금요일 PR
  fe/src/stores/atoms/issueDetail.ts
  fe/src/stores/atoms/issueList.ts
  fe/src/stores/atoms/label.ts
  fe/src/stores/atoms/milestone.ts
  fe/src/stores/atoms/user.ts
  fe/src/stores/selector/issueList.ts
  fe/src/types/IssueType.ts
  fe/src/types/commentType.ts
  fe/src/types/labelTypes.ts
  fe/src/types/milestoneType.ts
  fe/src/types/userType.ts
Labels: review-FE

#153 [Team-09][BE][테리&벅픽] 2주차 PR 1번째 - 로그인 API 구현 마무리, Issue 저장 API 구현
  BE/build.gradle
  BE/docs/issue_tracker_table_create.sql
  BE/src/main/java/com/team09/issue_tracker/common/ErrorResponse.java
  BE/src/main/java/com/team09/issue_tracker/exception/BusinessException.java
  BE/src/main/java/com/team09/issue_tracker/exception/CustomExceptionHandler.java
  BE/src/main/java/com/team09/issue_tracker/exception/EditorInvalidException.java
  BE/src/main/java/com/team09/issue_tracker/exception/InvalidException.java
  BE/src/main/java/com/team09/issue_tracker/exception/LabelInvalidException.java
  BE/src/main/java/com/team09/issue_tracker/exception/MemberInvalidException.java
  BE/src/main/java/com/team09/issue_tracker/exception/MilestoneInvalidException.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueLabelRepository.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueRepository.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueService.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueValidateService.java
  BE/src/main/java/com/team09/issue_tracker/issue/domain/Issue.java
  BE/src/main/java/com/team09/issue_tracker/issue/domain/IssueAssignee.java
  BE/src/main/java/com/team09/issue_tracker/issue/domain/IssueLabel.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueSaveServiceDto.java
  BE/src/main/java/com/team09/issue_tracker/label/Label.java
  BE/src/main/java/com/team09/issue_tracker/label/LabelRepository.java
  BE/src/main/java/com/team09/issue_tracker/label/LabelService.java
  BE/src/main/java/com/team09/issue_tracker/login/controller/LoginController.java
  BE/src/main/java/com/team09/issue_tracker/login/controller/dto/TokenReissueRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/login/controller/dto/TokenReissueResponseDto.java
  BE/src/main/java/com/team09/issue_tracker/login/filter/FilterConfiguration.java
  BE/src/main/java/com/team09/issue_tracker/login/filter/LoginValidateFilter.java
  BE/src/main/java/com/team09/issue_tracker/login/jwt/JwtConfiguration.java
  BE/src/main/java/com/team09/issue_tracker/login/jwt/JwtToken.java
  BE/src/main/java/com/team09/issue_tracker/login/jwt/JwtTokenProvider.java
  BE/src/main/java/com/team09/issue_tracker/login/oauth/user/OauthUserProfile.java
  BE/src/main/java/com/team09/issue_tracker/login/redis/RedisConfiguration.java
  BE/src/main/java/com/team09/issue_tracker/login/redis/RedisService.java
  BE/src/main/java/com/team09/issue_tracker/login/service/LoginService.java
  BE/src/main/java/com/team09/issue_tracker/member/Member.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberRepository.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberService.java
  BE/src/main/java/com/team09/issue_tracker/member/MemberType.java
  BE/src/main/java/com/team09/issue_tracker/milestone/Milestone.java
  BE/src/main/java/com/team09/issue_tracker/milestone/MilestoneRepository.java
  BE/src/main/java/com/team09/issue_tracker/milestone/MilestoneService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/com/team09/issue_tracker/issue/IssueCreateRepositoryTest.java
  BE/src/test/java/com/team09/issue_tracker/issue/IssueSelectRepositoryTest.java
  BE/src/test/java/com/team09/issue_tracker/issue/studyofjpa/QueryMethodTest.java
Labels: review-BE

#178 [Team-21][FE] jinnie & benny 2주차 두번째 PR
  FE/package-lock.json
  FE/package.json
  FE/public/icons/fileAdd.svg
  FE/public/icons/snbButton.svg
  FE/public/imgs/LogotypeLarge.svg
  FE/public/imgs/LogotypeMedium.svg
  FE/public/imgs/UserImageLarge.svg
  FE/public/mockServiceWorker.js
  FE/src/App.tsx
  FE/src/common/Filter/FilterBar.styled.ts
  FE/src/common/Filter/FilterBar.tsx
  FE/src/common/TextArea/TextArea.styled.ts
  FE/src/common/TextArea/TextArea.tsx
  FE/src/common/global.ts
  FE/src/component/Container/Container.styled.ts
  FE/src/component/Container/Container.tsx
  FE/src/component/Container/index.ts
  FE/src/constants/constants.ts
  FE/src/index.tsx
  FE/src/mocks/browser.js
  FE/src/mocks/handler.ts
  FE/src/pages/Issues/Constants.tsx
  FE/src/pages/Issues/Filter.tsx
  FE/src/pages/Issues/Issue.tsx
  FE/src/pages/Issues/IssueHeader.tsx
  FE/src/pages/Issues/Issues.styled.ts
  FE/src/pages/Issues/Issues.tsx
  FE/src/pages/Login/Login.tsx
  FE/src/pages/NewIssue/NewIssue.styled.ts
  FE/src/pages/NewIssue/NewIssue.tsx
  FE/src/style/IssuePageTitle/IssuePageTitle.styled.ts
  FE/src/style/IssuePageTitle/IssuePageTitle.tsx
  FE/src/style/IssuePageTitle/index.ts
  FE/src/style/NewIssueForm/NewIssueForm.stories.tsx
  FE/src/style/NewIssueForm/NewIssueForm.styled.ts
  FE/src/style/NewIssueForm/NewIssueForm.tsx
  FE/src/style/NewIssueForm/index.ts
  FE/src/style/TextArea/TextArea.styled.ts
  FE/src/style/TextArea/TextArea.tsx
Labels: review-FE

#184 [Team-20][BE][검봉 & 타니] 2주차 두 번째 PR 요청드립니다 !
  .github/workflows/gradle.yml
  BE/.gitignore
  BE/README.md
  BE/src/main/java/team20/issuetracker/config/WebConfig.java
  BE/src/main/java/team20/issuetracker/exception/MyJwtException.java
  BE/src/main/java/team20/issuetracker/exceptionhandler/ErrorResponse.java
  BE/src/main/java/team20/issuetracker/exceptionhandler/GlobalExceptionHandler.java
  BE/src/main/java/team20/issuetracker/home/HomeController.java
  BE/src/main/java/team20/issuetracker/login/interceptor/LoginInterceptor.java
  BE/src/main/java/team20/issuetracker/login/jwt/JwtTokenProvider.java
  BE/src/main/java/team20/issuetracker/login/oauth/OauthConfig.java
  BE/src/main/java/team20/issuetracker/login/oauth/Role.java
  BE/src/main/java/team20/issuetracker/login/oauth/controller/OauthController.java
  BE/src/main/java/team20/issuetracker/login/oauth/service/OauthService.java
  BE/src/main/resources/application-oauth2.yml
  BE/src/main/resources/static/index.html
Labels: review-BE

#213 [Team-30] [BE] 2주차 두 번째 PR
  BE/build.gradle
  BE/src/main/java/codesquad/backend/issuetracker/BeApplication.java
  BE/src/main/java/codesquad/backend/issuetracker/comment/presentation/controller/CommentController.java
  BE/src/main/java/codesquad/backend/issuetracker/comment/presentation/dto/CommentCreateRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/comment/presentation/dto/CommentDto.java
  BE/src/main/java/codesquad/backend/issuetracker/comment/presentation/dto/CommentEditRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/common/config/WebConfig.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/controller/IssueController.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/FilterCondition.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueAssigneeEditRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueCommentDto.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueCreateRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueDetailDto.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueLabelDto.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueLabelEditRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueMilestoneDto.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueStatus.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssuesResponseDto.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/SingleIssueDto.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/UserDto.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/controller/LabelController.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelCountDto.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelCreateRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelDto.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelEditRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelsResponseDto.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/TextColor.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/controller/MilestoneController.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneCountDto.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneCreateRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneDto.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneEditRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestonesResponseDto.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/AuthService.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/GithubAuthService.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/JwtFactory.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/LoginService.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/OAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/config/OAuthProperties.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/AuthInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/CommonInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/RefreshInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubLoginUserDto.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/auth/auth.yml
  BE/src/test/java/codesquad/backend/issuetracker/BeApplicationTests.java
  BE/src/test/java/codesquad/backend/issuetracker/oauth/AuthControllerTest.java
Labels: review-BE

#194 [team-07] [Hwi & 땃쥐] issuetracker 4차 PR
  BE/src/main/java/com/codesquad/issuetracker/IssuetrackerApplication.java
  BE/src/main/java/com/codesquad/issuetracker/domain/BaseTimeEntity.java
  BE/src/main/java/com/codesquad/issuetracker/domain/Comment.java
  BE/src/main/java/com/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/com/codesquad/issuetracker/domain/IssueAssignee.java
  BE/src/main/java/com/codesquad/issuetracker/domain/IssueLabel.java
  BE/src/main/java/com/codesquad/issuetracker/domain/Label.java
  BE/src/main/java/com/codesquad/issuetracker/domain/LabelColor.java
  BE/src/main/java/com/codesquad/issuetracker/domain/Member.java
  BE/src/main/java/com/codesquad/issuetracker/excption/InvalidColorValueRangeException.java
  BE/src/main/java/com/codesquad/issuetracker/excption/InvalidIssueAssigneeAddException.java
  BE/src/main/java/com/codesquad/issuetracker/excption/InvalidIssueLabelAddException.java
  BE/src/main/java/com/codesquad/issuetracker/excption/IssueNotFoundException.java
  BE/src/main/java/com/codesquad/issuetracker/repository/comment/CommentCustomRepository.java
  BE/src/main/java/com/codesquad/issuetracker/repository/comment/CommentRepositoryImpl.java
  BE/src/main/java/com/codesquad/issuetracker/repository/issue/IssueCustomRepository.java
  BE/src/main/java/com/codesquad/issuetracker/repository/issue/IssueRepository.java
  BE/src/main/java/com/codesquad/issuetracker/repository/issue/IssueRepositoryImpl.java
  BE/src/main/java/com/codesquad/issuetracker/service/comment/CommentQueryService.java
  BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueCommandService.java
  BE/src/main/java/com/codesquad/issuetracker/service/issue/IssueQueryService.java
  BE/src/main/java/com/codesquad/issuetracker/service/label/LabelCommandService.java
  BE/src/main/java/com/codesquad/issuetracker/service/label/LabelQueryService.java
  BE/src/main/java/com/codesquad/issuetracker/service/member/MemberQueryService.java
  BE/src/main/java/com/codesquad/issuetracker/service/milestone/MilestoneQueryService.java
  BE/src/main/java/com/codesquad/issuetracker/web/IssueController.java
  BE/src/main/java/com/codesquad/issuetracker/web/LabelController.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/IssueStateChangeResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/LabelDto.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/comment/CommentListElement.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueAssigneeDto.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueCreateRequest.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueCreateResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueDeleteResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueLabelDto.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueListRequest.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueListResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueStateChangeRequest.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueStateChangeResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueUpdateRequest.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/IssueUpdateResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/MultipleIssueStateChangeRequest.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/issue/MultipleIssueStateChangeResponse.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/label/LabelCreateRequest.java
  BE/src/main/java/com/codesquad/issuetracker/web/dto/label/LabelCreateResponse.java
  BE/src/test/java/com/codesquad/issuetracker/IssuetrackerApplicationTests.java
  BE/src/test/java/com/codesquad/issuetracker/basic/HashSetTest.java
  BE/src/test/java/com/codesquad/issuetracker/basic/StringTest.java
  BE/src/test/java/com/codesquad/issuetracker/domain/IssueAssigneeTest.java
  BE/src/test/java/com/codesquad/issuetracker/domain/IssueLabelTest.java
  BE/src/test/java/com/codesquad/issuetracker/domain/IssueTest.java
Labels: review-BE

#190 [team-32][BE][산토리&포키] IssueTracker 4차 PR
  be/src/main/java/com/codesquad/issuetracker/auth/application/AuthService.java
  be/src/main/java/com/codesquad/issuetracker/auth/application/JwtProvider.java
  be/src/main/java/com/codesquad/issuetracker/auth/presentation/argumentresolver/AuthArgumentResolver.java
  be/src/main/java/com/codesquad/issuetracker/auth/presentation/controller/AuthController.java
  be/src/main/java/com/codesquad/issuetracker/auth/presentation/dto/AccessTokenDto.java
  be/src/main/java/com/codesquad/issuetracker/auth/presentation/interceptor/AuthInterceptor.java
  be/src/main/java/com/codesquad/issuetracker/common/config/AuthConfig.java
  be/src/main/java/com/codesquad/issuetracker/common/util/PasswordEncryptor.java
  be/src/main/java/com/codesquad/issuetracker/common/util/TokenParser.java
  be/src/main/java/com/codesquad/issuetracker/exception/domain/type/AuthExceptionType.java
  be/src/main/java/com/codesquad/issuetracker/exception/domain/type/ExceptionType.java
  be/src/main/java/com/codesquad/issuetracker/exception/domain/type/UserExceptionType.java
  be/src/main/java/com/codesquad/issuetracker/exception/dto/ExceptionResponseDto.java
  be/src/main/java/com/codesquad/issuetracker/exception/handler/AuthExceptionHandler.java
  be/src/main/java/com/codesquad/issuetracker/user/application/BasicLoginService.java
  be/src/main/java/com/codesquad/issuetracker/user/application/UserService.java
  be/src/main/java/com/codesquad/issuetracker/user/domain/User.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/controller/LoginController.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/controller/UserController.java
  be/src/main/java/com/codesquad/issuetracker/user/presentation/dto/UserResponseDto.java
  be/src/main/resources/application.yml
Labels: review-BE

#212 [team-31][FE] Maeve & JinJeon 2주차 두 번째 PR
  fe/src/Api/index.ts
  fe/src/Api/issuesApi.ts
  fe/src/Api/labelsApi.ts
  fe/src/Api/milestoneApi.ts
  fe/src/Api/usersApi.ts
  fe/src/Component/FilterBar/index.tsx
  fe/src/Component/OptionTabs/index.tsx
  fe/src/Component/Popup/Popup.styled.tsx
  fe/src/Component/Popup/PopupContent/PopupContent.styled.tsx
  fe/src/Component/Popup/PopupContent/index.tsx
  fe/src/Component/Popup/index.tsx
  fe/src/Component/UserImg/UserImg.styled.tsx
  fe/src/Component/UserImg/index.tsx
  fe/src/Pages/IssueList/FilterCategoryList/FilterCategory.styled.tsx
  fe/src/Pages/IssueList/FilterCategoryList/index.tsx
  fe/src/Pages/IssueList/IssueCell/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/FilterCategoryList/FilterCategory.styled.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/FilterCategoryList/FilterCategory/FilterCategory.styled.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/FilterCategoryList/FilterCategory/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/FilterCategoryList/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/IssueListContentHeader.styled.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/IssueStateEditor/IssueStateEditor.styled.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/IssueStateEditor/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueOption/index.tsx
  fe/src/Pages/IssueList/IssueListContent/index.tsx
  fe/src/Pages/IssueList/IssuesNotification/IssuesNotification.styled.tsx
  fe/src/Pages/IssueList/IssuesNotification/index.tsx
  fe/src/Pages/Main/MainLoading/index.tsx
  fe/src/Pages/NewIssue/NewIssueContent/NewIssueContent.styled.tsx
  fe/src/Pages/NewIssue/NewIssueContent/index.tsx
  fe/src/Styles/Normalize.tsx
  fe/src/Util/Icons.tsx
Labels: review-FE

#160 Revert "[team-18][FE] Sonya"
  FE/tracker/.gitignore
  FE/tracker/README.md
  FE/tracker/package-lock.json
  FE/tracker/package.json
  FE/tracker/public/index.html
  FE/tracker/src/App.css
  FE/tracker/src/App.test.js
  FE/tracker/src/components/issueList/IssueLIst.types.tsx
  FE/tracker/src/components/issueList/IssueList.function.tsx
  FE/tracker/src/components/issueList/iissueListTable.tsx
  FE/tracker/src/components/issueList/issueList.tsx
  FE/tracker/src/components/issueList/issueListHead.tsx
  FE/tracker/src/components/issueList/issueListToolbar.tsx
  FE/tracker/src/components/signIn/canvas.jsx
  FE/tracker/src/components/signIn/matrix.jsx
  FE/tracker/src/components/signIn/signIn.jsx
  FE/tracker/src/index.css
  FE/tracker/src/index.js
  FE/tracker/src/logo.svg
  FE/tracker/src/mui-style/muiTheme.jsx
  FE/tracker/src/mui-style/theme.jsx
Labels: review-FE

#173 [team-23(BE)] IssueTracker - 레이블, 마일스톤 API 기능 구현, 이슈 저장로직 수정
  BE/build.gradle
  BE/src/main/java/com/ron2ader/issuetracker/auth/LoginArgumentResolver.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/AuthController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/IssueController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/LabelController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/MilestoneController.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/authdto/LoginResponse.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueCondition.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueCreateRequest.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssueSimpleResponse.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/issuedto/IssuesResponse.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/labeldto/LabelRequest.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/labeldto/LabelResponse.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/labeldto/LabelsResponse.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/milestonedto/MilestoneRequest.java
  BE/src/main/java/com/ron2ader/issuetracker/controller/milestonedto/MilestoneResponse.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/Issue.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueAssignee.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueAssigneeRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueLabel.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueLabelRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/issue/IssueRepositoryImpl.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/label/Label.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/label/LabelRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/member/Member.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/milestone/MilestoneRepository.java
  BE/src/main/java/com/ron2ader/issuetracker/domain/reply/Reply.java
  BE/src/main/java/com/ron2ader/issuetracker/service/AuthService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/IssueService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/LabelService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/MemberService.java
  BE/src/main/java/com/ron2ader/issuetracker/service/MilestoneService.java
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/auth.yml
  BE/src/test/java/com/ron2ader/issuetracker/service/IssueServiceTest.java
Labels: review-BE

#158 [team-13][Eddy, Selina] 3번째 PR
  PRTracker.xcodeproj/project.pbxproj
  PRTracker/Resource/Base.lproj/Main.storyboard
  PRTracker/Resource/dummyResponseIssues.json
  PRTracker/Resource/dummyResponseUser.json
  PRTracker/Source/Common/BaseURLString.swift
  PRTracker/Source/Common/Logger.swift
  PRTracker/Source/Common/MockDataService.swift
  PRTracker/Source/Common/NSNotification+Extension.swift
  PRTracker/Source/Common/NetworkService.swift
  PRTracker/Source/Common/UIViewController+Alert.swift
  PRTracker/Source/Common/URLRequest+Extension.swift
  PRTracker/Source/Common/View/IntroViewController.swift
  PRTracker/Source/Login/Model/AppleLoginManager.swift
  PRTracker/Source/Login/Model/GitHubLoginManager.swift
  PRTracker/Source/Login/Model/PullManager.swift
  PRTracker/Source/Login/Model/TokenValidationResponse.swift
  PRTracker/Source/Login/View/LoginView.swift
  PRTracker/Source/Login/View/LoginViewController.swift
  PRTracker/Source/Login/View/ViewController.swift
  PRTracker/Source/Login/ViewModel/LoginViewModel.swift
  PRTracker/Source/PR_Listing/Model/Issue.swift
  PRTracker/Source/PR_Listing/Model/IssueManager.swift
  PRTracker/Source/PR_Listing/Model/User.swift
  PRTracker/Source/PR_Listing/Model/UserManager.swift
  PRTracker/Source/PR_Listing/View/PullListTableViewCell.swift
  PRTracker/Source/PR_Listing/View/PullListTableViewController.swift
  PRTracker/Source/PR_Listing/View/PullListViewController.swift
  PRTracker/Source/PR_Listing/ViewModel/IssueListViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/IssueTableCellViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/PullListViewModel.swift
  PRTracker/Supporting/SceneDelegate.swift
  PRTrackerTests/DummyResponse.swift
  PRTrackerTests/GithubLoginManagerTests.swift
  PRTrackerTests/IssueManagerTests.swift
  PRTrackerTests/KeyChainStub.swift
  PRTrackerTests/PRTrackerTests.swift
  PRTrackerTests/UIApplicationStub.swift
  PRTrackerTests/URLProtocolStub.swift
  PRTrackerTests/UserManagerTests.swift
  Podfile.lock
  create_secrets.rb
Labels: review-iOS

#182 [Team16][iOS] 2주차 금요일 Issue-Tracker PR
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Resource/API/Base/HTTPHeader.swift
  IssueTracker/IssueTracker/Resource/Repository/LoginRepository.swift
  IssueTracker/IssueTracker/Source/Network/API/Base/BaseTarget.swift
  IssueTracker/IssueTracker/Source/Network/API/Base/HTTPHeader.swift
  IssueTracker/IssueTracker/Source/Network/API/Base/HTTPMethod.swift
  IssueTracker/IssueTracker/Source/Network/API/Base/NetworkError.swift
  IssueTracker/IssueTracker/Source/Network/API/Base/Provider.swift
  IssueTracker/IssueTracker/Source/Network/API/IssueTrackerTarget.swift
  IssueTracker/IssueTracker/Source/Network/Repository/IssueTrackingRepository.swift
  IssueTracker/IssueTracker/Source/Network/Repository/LoginRepository.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/Model/Issue.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/Model/IssueResponse.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/Model/Milestone.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/Model/Tag.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/View/IssueCell.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/View/IssueListViewController.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/ViewModel/IssueListViewModel.swift
  IssueTracker/IssueTracker/Source/Present/Login/LoginViewController.swift
  IssueTracker/IssueTracker/Source/Present/Login/LoginViewModel.swift
  IssueTracker/IssueTracker/Source/Present/Support/AppDelegate.swift
  IssueTracker/IssueTracker/Source/Present/Support/DecodeManager.swift
  IssueTracker/IssueTracker/Source/Present/Support/SceneDelegate.swift
  IssueTracker/IssueTracker/Source/Present/Window/View/RootWindow.swift
  IssueTracker/IssueTracker/Source/Present/Window/View/TabBarViewController.swift
  IssueTracker/IssueTracker/Source/Present/Window/ViewModel/RootWindowViewModel.swift
  IssueTracker/IssueTracker/Source/Support/SceneDelegate.swift
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/AccentColor.colorset/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/AppIcon.appiconset/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/UserImageIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/UserImageIcon.imageset/User Image Small (1).png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/UserImageIcon.imageset/User Image Small.png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/filterIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/filterIcon.imageset/Icon (1).png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/filterIcon.imageset/Icon.png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/issueIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/issueIcon.imageset/Property 1=alert-circle (2).png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/milestoneIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/milestoneIcon.imageset/Vector (7).png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/milestoneIcon.imageset/Vector (8).png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/selectIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/selectIcon.imageset/Icon (2).png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/selectIcon.imageset/Icon (3).png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/tagIcon.imageset/Contents.json
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/tagIcon.imageset/Vector (5).png
  IssueTracker/IssueTracker/Source/Util/Assets.xcassets/tagIcon.imageset/Vector (6).png
  IssueTracker/IssueTracker/Source/Util/Eevironment.swift
  IssueTracker/IssueTracker/Source/Util/Extension+.swift
  IssueTracker/IssueTracker/Source/Util/Issue.json
Labels: review-iOS

#183 [Team-08][iOS] OAuth 마무리
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  ios/IssueTracker/IssueTracker/Application/Coordinator/AppFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Application/Coordinator/BaseCoordinator.swift
  ios/IssueTracker/IssueTracker/Application/Coordinator/TabBarFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/AccountFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/AppFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/IssueFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/LabelFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/MilestoneFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/TabBarFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  ios/IssueTracker/IssueTracker/Data/Repository/AuthRepository.swift
  ios/IssueTracker/IssueTracker/Data/Service.swift
  ios/IssueTracker/IssueTracker/Data/Storage.swift
  ios/IssueTracker/IssueTracker/Domain/UseCase.swift
  ios/IssueTracker/IssueTracker/Info.plist
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/Flow/LoginFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/Flow/LoginFlowDIContainer.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/View/LoginView.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/View/LoginViewController.swift
  ios/IssueTracker/IssueTracker/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Account/Flow/AccountFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Account/View/AccountViewController.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Issue.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Issue/Flow/IssueFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Issue/View/IssueListCell.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Issue/View/IssueViewController.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Issue/View/TableviewDataSource.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Label/Flow/LabelFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Label/View/LabelViewController.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Milestone/Flow/MilestoneFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Presentation/Tabs/Milestone/View/MilestoneViewController.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Common/View/BadgeLabel.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Common/View/LoginButton.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Common/View/TitleView.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Extensions/UIColor+Extensions.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Extensions/UIImage+Extensions.swift
  ios/IssueTracker/IssueTracker/Presentation/Utils/Extensions/UIView+Extensions.swift
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Color/deepGray.colorset/Contents.json
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Logo/apple.imageset/apple.png
  ios/IssueTracker/IssueTracker/Resources/Assets.xcassets/Logo/git.imageset/git.png
  ios/IssueTracker/Repository/LoginRepository.swift
Labels: review-iOS

#179 [Team-15][iOS] Github OAuth 로그인, Issue List 기본 구조 구현
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15.xcodeproj/xcshareddata/xcschemes/IssueTracker15.xcscheme
  IssueTracker15/IssueTracker15/Container/ContainerWrapper.swift
  IssueTracker15/IssueTracker15/Container/Resolvable.swift
  IssueTracker15/IssueTracker15/Issue/Filter/IssueFilterItemSelectViewController.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/IssueDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/LabelDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/MilestoneDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/PullRequestDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/UserDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListCell.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListFooterReusableView.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListHeaderReusableView.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListViewController.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/ViewModel/IssueViewModel.swift
  IssueTracker15/IssueTracker15/Issue/IssueNavigationController.swift
  IssueTracker15/IssueTracker15/IssueList/ViewModel/IssueViewModel.swift
  IssueTracker15/IssueTracker15/IssueNavigationController.swift
  IssueTracker15/IssueTracker15/Label/LabelNavigationController.swift
  IssueTracker15/IssueTracker15/Login/Model/AppleLoginModel.swift
  IssueTracker15/IssueTracker15/Login/Model/GitHubLoginModel.swift
  IssueTracker15/IssueTracker15/Login/Model/ValidateModel.swift
  IssueTracker15/IssueTracker15/Login/UseCase/AppleLoginUseCase.swift
  IssueTracker15/IssueTracker15/Login/UseCase/GithubLoginUseCase.swift
  IssueTracker15/IssueTracker15/Login/View/OAuthLoginButton.swift
  IssueTracker15/IssueTracker15/Login/View/UserInfoInputStackView.swift
  IssueTracker15/IssueTracker15/Login/View/UserInfoTextField.swift
  IssueTracker15/IssueTracker15/Login/ViewController/LoginViewController.swift
  IssueTracker15/IssueTracker15/Login/ViewModel/LoginViewModel.swift
  IssueTracker15/IssueTracker15/Login/ViewModel/UserInputViewModel.swift
  IssueTracker15/IssueTracker15/Milestone/MilestoneNavigationController.swift
  IssueTracker15/IssueTracker15/SupportingFiles/AccessTokenManager.swift
  IssueTracker15/IssueTracker15/SupportingFiles/AppDelegate.swift
  IssueTracker15/IssueTracker15/SupportingFiles/SceneDelegate.swift
  IssueTracker15/IssueTracker15/Test/UseCases/RequestModel.swift
  IssueTracker15/IssueTracker15/Test/UseCases/TestDecodableType.swift
  IssueTracker15/IssueTracker15/Test/UseCases/TestUseCase.swift
  IssueTracker15/IssueTracker15/Test/UseCases/UseCaseModel.swift
  IssueTracker15/IssueTracker15/Test/ViewModel/TestViewModel.swift
  IssueTracker15/IssueTracker15/Test/ViewTypes/BoldStringAdaptable.swift
  IssueTracker15/IssueTracker15/Test/ViewTypes/LargeStringAdaptable.swift
  IssueTracker15/IssueTracker15/Test/ViewTypes/ViewTextBindable.swift
  IssueTracker15/IssueTracker15/Test/Views/TestButton.swift
  IssueTracker15/IssueTracker15/Test/Views/TestLabel.swift
  IssueTracker15/IssueTracker15/UseCaseInterface/UseCaseContainer.swift
  IssueTracker15/IssueTracker15/UseCaseInterface/UseCaseResponsible.swift
  IssueTracker15/IssueTracker15/ViewBind/CommonViewModel.swift
  IssueTracker15/IssueTracker15/ViewBind/ViewBindable.swift
  IssueTracker15/IssueTracker15/ViewBind/ViewBinding.swift
  IssueTracker15/IssueTracker15/ViewController.swift
  IssueTracker15/ViewModelUnitTest/ViewModelUnitTest.swift
Labels: review-iOS

#174 [team-07] Puko & Kai : PR 피드백 적용 및 MVVM + Clean Architecture 설계
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/DomainLayer/Entity/GrantResource.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Entity/UserInfo.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestGrantCode/DefaultRequestGrantCodeUsecase.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestGrantCode/RequestAppleGrantCodeUseCase.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestGrantCode/RequestGithubGrantCodeUseCase.swift
  iOS/IssueTracker/IssueTracker/Helper/Observable.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/IssueAddScene/View/IssueAddViewController.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/ViewModel/LoginViewModel.swift
Labels: review-iOS

#118 [Team-27 BE][피오] Issue Tracker 2주차 첫 번째 PR입니다.
  .github/workflows/gradle.yml
  backend/Dockerfile
  backend/src/main/java/kr/codesquad/issuetracker/IssueTrackerApplication.java
  backend/src/main/java/kr/codesquad/issuetracker/auth/GitHubUserInfo.java
  backend/src/main/java/kr/codesquad/issuetracker/auth/LoginController.java
  backend/src/main/java/kr/codesquad/issuetracker/auth/LoginInterceptor.java
  backend/src/main/java/kr/codesquad/issuetracker/auth/LoginService.java
  backend/src/main/java/kr/codesquad/issuetracker/auth/jwt/JWTHandler.java
  backend/src/main/java/kr/codesquad/issuetracker/common/BaseTimeEntity.java
  backend/src/main/java/kr/codesquad/issuetracker/config/WebConfig.java
  backend/src/main/java/kr/codesquad/issuetracker/core/issue/Assignee.java
  backend/src/main/java/kr/codesquad/issuetracker/core/issue/AttachedFile.java
  backend/src/main/java/kr/codesquad/issuetracker/core/issue/Comment.java
  backend/src/main/java/kr/codesquad/issuetracker/core/issue/Emoji.java
  backend/src/main/java/kr/codesquad/issuetracker/core/issue/Issue.java
  backend/src/main/java/kr/codesquad/issuetracker/core/label/Label.java
  backend/src/main/java/kr/codesquad/issuetracker/core/milestone/Milestone.java
  backend/src/main/java/kr/codesquad/issuetracker/core/user/User.java
  backend/src/main/java/kr/codesquad/issuetracker/core/user/UserRepository.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/CustomException.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/ErrorCode.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/ErrorResponse.java
  backend/src/main/java/kr/codesquad/issuetracker/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application-deploy.yml
Labels: review-BE

#172 [Team-11] 새로운 이슈 만들기 기능 추가중 & 메모리 순환 참조 해결중
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/AppDelegate.swift
  IssueTracker/IssueTracker/Container.swift
  IssueTracker/IssueTracker/Entity/Issue.swift
  IssueTracker/IssueTracker/Entity/Milestone.swift
  IssueTracker/IssueTracker/Extension/UIView+Extension.swift
  IssueTracker/IssueTracker/GitHub/GitHubService.swift
  IssueTracker/IssueTracker/GitHub/RequestURL.swift
  IssueTracker/IssueTracker/Issue/IssueViewController.swift
  IssueTracker/IssueTracker/Issue/Model/IssueModel.swift
  IssueTracker/IssueTracker/Issue/NewIssueViewController.swift
  IssueTracker/IssueTracker/Issue/OptionSelectViewController.swift
  IssueTracker/IssueTracker/Issue/Service/IssueService.swift
  IssueTracker/IssueTracker/Issue/View/Devider.swift
Labels: review-iOS

#199 [iOS][team-09] MVVM구조 리팩토링 및 테스트 코드 작성
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker.xcodeproj/xcshareddata/xcschemes/IssueTracker.xcscheme
  iOS/IssueTracker/IssueTracker/Common/Model/NetworkService.swift
  iOS/IssueTracker/IssueTracker/Common/Model/Protocols/NetworkTargetProtocol.swift
  iOS/IssueTracker/IssueTracker/Common/View/TabBarController.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/LabelFactory.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/EditingIssueManager.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/EditingIssueNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/IssueItem.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/IssueManager.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/IssueNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/Issue/View/EditingIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewComponents/IssueCollectionView.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewComponents/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewComponents/IssueViewNavigationItems.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/ViewModel/EditingIssueViewModel.swift
  iOS/IssueTracker/IssueTracker/Issue/ViewModel/IssueViewModel.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SignInNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/SignIn/View/SignInViewController.swift
  iOS/IssueTracker/IssueTracker/SignIn/ViewModel/SignInViewModel.swift
  iOS/IssueTracker/IssueTrackerTests/EditingIssueManagerTests.swift
  iOS/IssueTracker/IssueTrackerTests/NetworkServiceTests.swift
  iOS/IssueTracker/IssueTrackerTests/SignInManagerTests.swift
  iOS/IssueTracker/IssueTrackerTests/SignInViewModelTests.swift
Labels: review-iOS

#171 [Team-03] [Android] [2주차 2번째 PR ] 이슈 리스트 롱클릭시 체크박스 등장 로직 구현, 이슈 디테일 화면 더보기 버튼 클릭시 DialogFragment 구현
  Android/app/src/main/java/com/example/issue_tracker/domain/model/Comment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/detail/IssueDetailAdapter.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/detail/IssueDetailFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/detail/IssueDetailMoreDialogFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/detail/IssueDetailViewModel.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueAdapter.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueAdapterEventListener.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueHomeFragment.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/IssueHomeViewModel.kt
  Android/app/src/main/java/com/example/issue_tracker/ui/issue/home/ItemHelper.kt
  Android/app/src/main/res/drawable/ic_close_black.xml
  Android/app/src/main/res/drawable/ic_delete_red.xml
  Android/app/src/main/res/drawable/ic_edit.xml
  Android/app/src/main/res/drawable/ic_trash.xml
  Android/app/src/main/res/drawable/layout_width_border.xml
  Android/app/src/main/res/layout/fragment_issue_detail.xml
  Android/app/src/main/res/layout/fragment_issue_detail_more_dialog.xml
  Android/app/src/main/res/layout/fragment_issue_home.xml
  Android/app/src/main/res/layout/item_comment_myself.xml
  Android/app/src/main/res/layout/item_comment_other.xml
  Android/app/src/main/res/layout/item_issues.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/styles.xml
Labels: review-android

#217 [Team-30] [BE] 3주차 첫 번째 PR
  BE/src/main/java/codesquad/backend/issuetracker/BeApplication.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/domain/Issue.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/controller/IssueController.java
  BE/src/main/java/codesquad/backend/issuetracker/issue/presentation/dto/IssueIdDto.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/infrastructure/MilestoneRepository.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/controller/MilestoneController.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneCountDto.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneDto.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestonesResponseDto.java
Labels: review-BE

#220 [Team-30] [BE] 3주차 두 번째 PR
  BE/src/main/java/codesquad/backend/issuetracker/issue/domain/Issue.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/infrastructure/MilestoneRepository.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/controller/MilestoneController.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneCountDto.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneDto.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/request/MilestoneCreateRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/request/MilestoneEditRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/response/MilestoneCountResponse.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/response/MilestoneIdResponse.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/response/MilestonesResponse.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/AuthInterceptor.java
  BE/src/main/resources/data.sql
Labels: review-BE

#196 [Team-04][Android][Linus_Jay][2주차 금요일 네번째 PR]
  app/src/main/java/com/example/issu_tracker/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/issu_tracker/di/RepositoryModule.kt
  app/src/main/java/com/example/issu_tracker/ui/account/FriendAdapter.kt
Labels: review-android

#240 [TEAM-33][bangtae, 이든][FE]3주차 수요일 PR
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Button/style.ts
  Frontend/src/components/DropDown/Icons/constants.ts
  Frontend/src/components/DropDown/Icons/index.tsx
  Frontend/src/components/DropDown/index.tsx
  Frontend/src/components/DropDown/style.ts
  Frontend/src/components/Filter/index.tsx
  Frontend/src/components/Filter/style.ts
  Frontend/src/components/Header/index.tsx
  Frontend/src/components/Icons/index.tsx
  Frontend/src/components/IssueTable/IssueItem/index.tsx
  Frontend/src/components/IssueTable/IssueList/index.tsx
  Frontend/src/components/IssueTable/IssueMenuBar/index.tsx
  Frontend/src/components/IssueTable/IssueMenuBar/style.ts
  Frontend/src/components/IssueTable/index.tsx
  Frontend/src/components/IssueTable/type.ts
  Frontend/src/components/Label/index.tsx
  Frontend/src/components/Label/style.ts
  Frontend/src/components/Tap/style.ts
  Frontend/src/components/UserImg/index.tsx
  Frontend/src/components/common/Button/index.tsx
  Frontend/src/index.tsx
  Frontend/src/pages/Loading/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Main/index.tsx
  Frontend/src/pages/Main/style.ts
  Frontend/src/router/index.tsx
  Frontend/src/style/theme.ts
  Frontend/webpack.config.js
Labels: review-FE

#241 [team-20][FE] Millie & J 3주차 1번째 PR
  .github/workflows/react.yml
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/components/Comment/index.tsx
  FE/src/components/CommentForm/index.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/IssueList/List.tsx
  FE/src/components/common/Loading/index.tsx
  FE/src/components/common/Loading/style.ts
  FE/src/constants/constants.ts
  FE/src/constants/login.ts
  FE/src/mocks/utils.ts
  FE/src/pages/Home/index.tsx
  FE/src/pages/Login/index.tsx
  FE/src/pages/LoginCallback/index.tsx
  FE/src/stores/atoms/user.ts
  FE/src/utils/cookie.ts
Labels: review-FE

#226 [Team-28][BE][Yan] 3주차 첫번째 PR
  .DS_Store
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetracker/auth/JwtInterceptor.java
  BE/src/main/java/kr/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/Status.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/StringToStatus.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/issue/repository/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/kr/codesquad/issuetracker/exception/ErrorMessage.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueSearchService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MemberService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestonesService.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/MilestonesController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueAddRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueLabelDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueModifyRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueResponseDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/label/LabelDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/milestone/MilestoneDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/milestone/MilestoneEditRequestDto.java
Labels: review-BE

#234 [Team-35][BE][쿠킴] Label 기능 구현과 리팩토링
  be/src/main/java/dev/kukim/issues/error/controller/exceptionControllerAdvice.java
  be/src/main/java/dev/kukim/issues/label/controller/LabelController.java
  be/src/main/java/dev/kukim/issues/label/controller/request/LabelInsertRequest.java
  be/src/main/java/dev/kukim/issues/label/controller/request/LabelUpdateRequest.java
  be/src/main/java/dev/kukim/issues/label/controller/response/LabelListResponse.java
  be/src/main/java/dev/kukim/issues/label/controller/response/LabelResponse.java
  be/src/main/java/dev/kukim/issues/label/domain/BackgroundColor.java
  be/src/main/java/dev/kukim/issues/label/domain/Description.java
  be/src/main/java/dev/kukim/issues/label/domain/Label.java
  be/src/main/java/dev/kukim/issues/label/domain/Title.java
  be/src/main/java/dev/kukim/issues/label/domain/repository/LabelRepository.java
  be/src/main/java/dev/kukim/issues/label/exception/InvalidBackgroudColorException.java
  be/src/main/java/dev/kukim/issues/label/exception/InvalidDescriptionException.java
  be/src/main/java/dev/kukim/issues/label/exception/InvalidTitleException.java
  be/src/main/java/dev/kukim/issues/label/exception/LabelNotFountException.java
  be/src/main/java/dev/kukim/issues/label/service/LabelService.java
  be/src/main/java/dev/kukim/issues/milestone/controller/MilestoneController.java
  be/src/main/java/dev/kukim/issues/milestone/controller/request/MilestoneCreateRequest.java
  be/src/main/java/dev/kukim/issues/milestone/controller/request/MilestoneUpdateRequest.java
  be/src/main/java/dev/kukim/issues/milestone/controller/response/MilestoneListResponse.java
  be/src/main/java/dev/kukim/issues/milestone/domain/Milestone.java
  be/src/main/java/dev/kukim/issues/milestone/domain/repository/MileStoneRepository.java
  be/src/main/java/dev/kukim/issues/milestone/service/MilestoneService.java
  be/src/main/java/dev/kukim/issues/user/user/domain/User.java
  be/src/test/java/dev/kukim/issues/label/domain/BackgroundColorTest.java
  be/src/test/java/dev/kukim/issues/label/domain/DescriptionTest.java
  be/src/test/java/dev/kukim/issues/label/domain/TitleTest.java
  be/src/test/java/dev/kukim/issues/milestone/service/MilestoneServiceTest.java
Labels: review-BE

#229 [Team-27] Jimmy & 포키 3주차 첫번째 pr
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/Icons/CheckArrow.tsx
  fe/src/components/Icons/CheckBoxInitial.tsx
  fe/src/components/Icons/MileStone.tsx
  fe/src/components/Icons/Tag.tsx
  fe/src/components/common/Callback.tsx
  fe/src/components/common/Input.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/common/Tap.tsx
  fe/src/components/common/TextArea.tsx
  fe/src/components/common/button/TextButton.tsx
  fe/src/components/common/filterBar/FilterBar.tsx
  fe/src/components/common/filterBar/FilterBarInput.tsx
  fe/src/components/common/filterBar/FilterBarInterface.ts
  fe/src/components/common/loginPage/LoginPage.tsx
  fe/src/components/issueListPage/IssueListPage.tsx
  fe/src/components/issueListPage/ListFilter.tsx
  fe/src/constants/loginPageText.ts
  fe/src/constants/tabStyle.ts
  fe/src/index.tsx
  fe/src/mocks/issueList.js
  fe/src/styles/globalStyle.js
Labels: review-FE

#251 [TEAM-28][옐로우 & 난정]3주차 수요일 PR
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/assets/icons/Icon.tsx
  FE/src/common/components/Layout.tsx
  FE/src/common/components/Tab.tsx
  FE/src/common/components/TextInput.tsx
  FE/src/common/components/buttons/Button.tsx
  FE/src/common/components/buttons/ButtonSmallStandard.tsx
  FE/src/common/components/dropDown/DropDownCheckBoxItem.tsx
  FE/src/common/components/dropDown/DropDownPanel.tsx
  FE/src/common/constants/colors.ts
  FE/src/common/constants/greyscale.ts
  FE/src/common/constants/index.ts
  FE/src/common/utils/utils.ts
  FE/src/index.tsx
  FE/src/issueList/FilterBar.tsx
  FE/src/issueList/IssueList.tsx
  FE/src/issueList/IssueTab.tsx
  FE/src/issueList/LinkTabs.tsx
  FE/src/issueList/issueListTable/CheckBox.tsx
  FE/src/issueList/issueListTable/IssueList.tsx
  FE/src/issueList/issueListTable/issueHeader/ClickedIssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueMenu.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueTab.tsx
  FE/src/issueList/issueListTable/issueItem/EmptyIssueItem.tsx
  FE/src/issueList/issueListTable/issueItem/IssueItem.tsx
  FE/src/issueList/issueListTable/issueItem/Label.tsx
  FE/src/issueList/stores/IssueListProvider.tsx
  FE/src/issueList/stores/checkReducer.tsx
  FE/src/login/Login.tsx
  FE/src/mocks/handlers.ts
  FE/src/mocks/issueFilterOptions.js
  FE/src/mocks/issueListData.js
  FE/src/pages/AddIssuePage.tsx
  FE/src/pages/IssueDetailPage.tsx
  FE/src/pages/IssueListPage.tsx
  FE/src/pages/LabelListPage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/MilestoneListPage.tsx
  FE/src/utils.ts
Labels: review-FE

#248 [team-13][Eddy, Selina] 3주차 수요일 PR
  PRTracker.xcodeproj/project.pbxproj
  PRTracker.xcodeproj/xcshareddata/xcschemes/PRTracker.xcscheme
  PRTracker/Resource/Base.lproj/Main.storyboard
  PRTracker/Source/Common/Logger.swift
  PRTracker/Source/Common/MockDataService.swift
  PRTracker/Source/Common/NetworkService.swift
  PRTracker/Source/Common/Networking/APIEndpoint.swift
  PRTracker/Source/Common/Networking/APIRequest.swift
  PRTracker/Source/Common/Networking/APIRequestable.swift
  PRTracker/Source/Common/Networking/HTTPMethod.swift
  PRTracker/Source/Common/Networking/NetworkError.swift
  PRTracker/Source/Common/Networking/NetworkService.swift
  PRTracker/Source/Common/Storage.swift
  PRTracker/Source/Common/UIViewController+Alert.swift
  PRTracker/Source/Common/View/IntroViewController.swift
  PRTracker/Source/Filter/FilterViewController.swift
  PRTracker/Source/Filter/View/FilterTableViewCell.swift
  PRTracker/Source/Login/Model/AccessToken.swift
  PRTracker/Source/Login/Model/GetAccessToken.swift
  PRTracker/Source/Login/Model/GitHubLoginManager.swift
  PRTracker/Source/Login/Model/LoginViewModel.swift
  PRTracker/Source/Login/View/LoginViewController.swift
  PRTracker/Source/PR_Listing/Model/GetIssues.swift
  PRTracker/Source/PR_Listing/Model/GetUser.swift
  PRTracker/Source/PR_Listing/Model/Issue.swift
  PRTracker/Source/PR_Listing/Model/IssueManager.swift
  PRTracker/Source/PR_Listing/Model/IssuesParameter.swift
  PRTracker/Source/PR_Listing/Model/ListingManager.swift
  PRTracker/Source/PR_Listing/Model/PullListModel.swift
  PRTracker/Source/PR_Listing/Model/Repository.swift
  PRTracker/Source/PR_Listing/Model/UpdateIssue.swift
  PRTracker/Source/PR_Listing/Model/User.swift
  PRTracker/Source/PR_Listing/Model/UserManager.swift
  PRTracker/Source/PR_Listing/View/PullListTableViewCell.swift
  PRTracker/Source/PR_Listing/View/PullListViewController.swift
  PRTracker/Source/PR_Listing/ViewModel/IssueListViewModel.swift
  PRTracker/Source/PR_Listing/ViewModel/IssueTableCellViewModel.swift
  PRTracker/Supporting/AppDelegate.swift
  PRTracker/Supporting/SceneDelegate.swift
  PRTrackerTests/GithubLoginManagerTests.swift
  PRTrackerTests/IssueListViewModelTests.swift
  PRTrackerTests/IssueManagerTests.swift
  PRTrackerTests/IssueServiceStub.swift
  PRTrackerTests/UIApplicationStub.swift
  PRTrackerTests/URLProtocolStub.swift
  PRTrackerTests/UserManagerTests.swift
  Podfile.lock
Labels: review-iOS

#232 [Team-30][FE] Cola, Muffin 3주차 1번째 PR
  FE/.eslintrc.js
  FE/public/index.html
  FE/src/Router.tsx
  FE/src/apis/issue.ts
  FE/src/apis/label.ts
  FE/src/apis/milestone.ts
  FE/src/apis/user.ts
  FE/src/components/Button/index.tsx
  FE/src/components/Button/style.ts
  FE/src/components/FilterBar/index.tsx
  FE/src/components/FilterBar/style.ts
  FE/src/components/Indicator/Loader/index.tsx
  FE/src/components/Input/index.tsx
  FE/src/components/Issue/Filter/index.tsx
  FE/src/components/Issue/Item/index.tsx
  FE/src/components/Issue/Navigation/index.tsx
  FE/src/components/Issue/index.tsx
  FE/src/components/Label/Form.tsx
  FE/src/components/Label/formStyle.ts
  FE/src/components/Modal/index.tsx
  FE/src/components/Modal/style.ts
  FE/src/components/Popup/Contents.tsx
  FE/src/components/Popup/Item.tsx
  FE/src/components/Popup/type.ts
  FE/src/components/SideBar/AssigneePanel.tsx
  FE/src/components/SideBar/Common.tsx
  FE/src/components/SideBar/LabelPanel.tsx
  FE/src/components/SideBar/MileStonePanel.tsx
  FE/src/components/SideBar/context/AssigneePanel/index.tsx
  FE/src/components/SideBar/context/LabelPanel/index.tsx
  FE/src/components/SideBar/context/MileStonePanel/index.tsx
  FE/src/components/SideBar/context/index.tsx
  FE/src/components/SideBar/index.tsx
  FE/src/components/SideBar/popupStyle.ts
  FE/src/components/SideBar/style.ts
  FE/src/components/UserAvatar/index.tsx
  FE/src/components/UserAvatar/style.ts
  FE/src/constants/default.ts
  FE/src/hooks/useComponentVisible.tsx
  FE/src/hooks/useDebouce.tsx
  FE/src/hooks/useInput.tsx
  FE/src/hooks/usePostIssue.tsx
  FE/src/mocks/handlers/GetLabels.js
  FE/src/mocks/handlers/GetMileStones.js
  FE/src/mocks/handlers/GetUsers.js
  FE/src/mocks/handlers/PostIssue.js
  FE/src/mocks/handlers/index.js
  FE/src/pages/Callback/index.tsx
  FE/src/pages/IssuePage/Detail/Main/index.tsx
  FE/src/pages/IssuePage/Detail/Main/style.ts
  FE/src/pages/LabelPage/index.tsx
  FE/src/pages/LabelPage/style.ts
  FE/src/pages/Verification/index.tsx
  FE/src/recoil/atoms/label.ts
  FE/src/recoil/atoms/milestone.ts
  FE/src/styles/GlobalStyle.tsx
  FE/src/styles/theme.ts
  FE/src/type/label.ts
  FE/src/type/milestone.ts
  FE/src/utils/Compose.tsx
Labels: review-FE

#244 [team-07][ Puko&Kai] MVVM+Clean Architecture 설계 수정 & OAuth 구현부 수정
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/DataLayer/Network/EndPoint/EndPoint.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/EndPoint/EndPointable.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/EnumTypes/NetworkError.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/Service/NetworkService.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/Service/Protocol/NetworkServiceable.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/URLComponent/GitURLConfiguration.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/URLComponent/Protocol/Authenticable.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/URLComponent/Protocol/URLConfigurable.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Network/URLComponent/TokenURLConfiguration.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Repository/DefaultUserInfoRepository/DefaultUserInfoRepository.swift
  iOS/IssueTracker/IssueTracker/DataLayer/Repository/DefaultUserInfoRepository/UserInfoRepository.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Entity/GrantResource.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Entity/TokenInfo.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Entity/UserInfo.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestGrantCode/AppleAuthorizationUsecase.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestGrantCode/DefaultLoginUsecase.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestGrantCode/DefaultRequestGrantCodeUsecase.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestGrantCode/GithubAuthorizationUsecase.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestGrantCode/RequestGithubGrantCodeUseCase.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestUserInfo/DefaultRequestUserInfoUsecase.swift
  iOS/IssueTracker/IssueTracker/DomainLayer/Usecase/DefaultRequestUserInfo/RequestUserInfoUsecase.swift
  iOS/IssueTracker/IssueTracker/Helper/Decoder.swift
  iOS/IssueTracker/IssueTracker/Helper/Encoder.swift
  iOS/IssueTracker/IssueTracker/NotificationCenter.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/IssueAddScene/View/IssueAddViewController.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/EnumTypes/OAuth.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/Component/OAuthLoginButton.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/LoginViewController.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/View/OAuthButtonDelegate.swift
  iOS/IssueTracker/IssueTracker/PresentationLayer/LoginScene/ViewModel/LoginViewModel.swift
Labels: review-iOS

#255 [Team-34][BE] 3주차 수요일 정기 PR
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/dto/LoginResponse.java
  BE/src/main/java/org/codesquad/team34/issuetracker/auth/github/GithubOAuthController.java
  BE/src/main/java/org/codesquad/team34/issuetracker/common/BaseEntity.java
  BE/src/main/java/org/codesquad/team34/issuetracker/common/LoginInterceptor.java
  BE/src/main/java/org/codesquad/team34/issuetracker/common/Status.java
  BE/src/main/java/org/codesquad/team34/issuetracker/common/dto/ListResponse.java
  BE/src/main/java/org/codesquad/team34/issuetracker/common/dto/TotalCountResponse.java
  BE/src/main/java/org/codesquad/team34/issuetracker/config/CorsConfig.java
  BE/src/main/java/org/codesquad/team34/issuetracker/config/InterceptorConfig.java
  BE/src/main/java/org/codesquad/team34/issuetracker/config/SwaggerConfig.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/Comment.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/Issue.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/IssueController.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/IssuePredicateFactory.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/IssueRepository.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/IssueService.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/dto/IssueListElement.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/dto/IssueListResponse.java
  BE/src/main/java/org/codesquad/team34/issuetracker/issue/dto/IssueQueryParams.java
  BE/src/main/java/org/codesquad/team34/issuetracker/label/Label.java
  BE/src/main/java/org/codesquad/team34/issuetracker/label/LabelController.java
  BE/src/main/java/org/codesquad/team34/issuetracker/label/LabelRepository.java
  BE/src/main/java/org/codesquad/team34/issuetracker/label/LabelService.java
  BE/src/main/java/org/codesquad/team34/issuetracker/label/dto/LabelListResponse.java
  BE/src/main/java/org/codesquad/team34/issuetracker/label/dto/LabelResponse.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/Member.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/MemberController.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/MemberService.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/dto/MemberDto.java
  BE/src/main/java/org/codesquad/team34/issuetracker/member/dto/MemberListResponse.java
  BE/src/main/java/org/codesquad/team34/issuetracker/milestone/Milestone.java
  BE/src/main/java/org/codesquad/team34/issuetracker/milestone/MilestoneController.java
  BE/src/main/java/org/codesquad/team34/issuetracker/milestone/MilestoneRepository.java
  BE/src/main/java/org/codesquad/team34/issuetracker/milestone/MilestoneService.java
  BE/src/main/java/org/codesquad/team34/issuetracker/milestone/dto/MilestoneListResponse.java
  BE/src/main/java/org/codesquad/team34/issuetracker/milestone/dto/MilestoneResponse.java
  BE/src/main/resources/application-remote.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/sql/data.sql
  BE/src/main/resources/sql/schema.sql
Labels: review-BE

#238 [Team-05] [Android] 코드 줄간격 수정 및
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/issue_tracker/common/Extensions.kt
  android/app/src/main/java/com/example/issue_tracker/common/ResponseResult.kt
  android/app/src/main/java/com/example/issue_tracker/model/Issue.kt
  android/app/src/main/java/com/example/issue_tracker/model/IssueDTO.kt
  android/app/src/main/java/com/example/issue_tracker/network/APIService.kt
  android/app/src/main/java/com/example/issue_tracker/network/CEHModel.kt
  android/app/src/main/java/com/example/issue_tracker/network/CoroutinException.kt
  android/app/src/main/java/com/example/issue_tracker/network/RetrofitObject.kt
  android/app/src/main/java/com/example/issue_tracker/repository/IssueRepository.kt
  android/app/src/main/java/com/example/issue_tracker/repository/IssueRepositoryImpl.kt
  android/app/src/main/java/com/example/issue_tracker/repository/LabelRepository.kt
  android/app/src/main/java/com/example/issue_tracker/repository/LabelRepositoryImpl.kt
  android/app/src/main/java/com/example/issue_tracker/repository/MileStoneRepositoryImpl.kt
  android/app/src/main/java/com/example/issue_tracker/repository/RepositoryModule.kt
  android/app/src/main/java/com/example/issue_tracker/ui/common/BindingAdapter.kt
  android/app/src/main/java/com/example/issue_tracker/ui/common/SwipeHelperCallback.kt
  android/app/src/main/java/com/example/issue_tracker/ui/common/UserAppClient.kt
  android/app/src/main/java/com/example/issue_tracker/ui/issue/IssueAdapter.kt
  android/app/src/main/java/com/example/issue_tracker/ui/issue/IssueAddFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/issue/IssueDetailFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/issue/IssueDetailViewModel.kt
  android/app/src/main/java/com/example/issue_tracker/ui/issue/IssueFilterFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/issue/IssueFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/issue/IssueSearchFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/issue/IssueViewModel.kt
  android/app/src/main/java/com/example/issue_tracker/ui/label/CustomLabel.kt
  android/app/src/main/java/com/example/issue_tracker/ui/label/LabelAddFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/label/LabelAddViewModel.kt
  android/app/src/main/java/com/example/issue_tracker/ui/label/LabelFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/label/LabelViewModel.kt
  android/app/src/main/java/com/example/issue_tracker/ui/login/LoginCustomButton.kt
  android/app/src/main/java/com/example/issue_tracker/ui/login/LoginFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/login/SignUpFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/milestone/MileStoneAdapter.kt
  android/app/src/main/java/com/example/issue_tracker/ui/milestone/MileStoneAddFragment.kt
  android/app/src/main/java/com/example/issue_tracker/ui/milestone/MileStoneAddViewModel.kt
  android/app/src/main/java/com/example/issue_tracker/ui/milestone/MileStoneViewModel.kt
  android/app/src/main/res/drawable/ic_vector_4.xml
  android/app/src/main/res/drawable/user_image.png
  android/app/src/main/res/layout/fragment_issue.xml
  android/app/src/main/res/layout/fragment_issue_detail.xml
  android/app/src/main/res/layout/item_issue_detail_recycler.xml
  android/app/src/main/res/layout/item_issue_recycler_view.xml
  android/app/src/main/res/values/strings.xml
Labels: review-android

#264 [team-34 | dony & hemdi] 3주차 1번째 PR 요청
  FE/src/api/core.ts
  FE/src/api/githubOauth.ts
  FE/src/api/issueList.ts
  FE/src/api/labels.ts
  FE/src/api/members.ts
  FE/src/api/milestones.ts
  FE/src/api/queryKeys.ts
  FE/src/api/type.ts
  FE/src/components/Header/index.tsx
  FE/src/components/IssueList/FilterBar/index.tsx
  FE/src/components/IssueList/FilterBar/style.ts
  FE/src/components/IssueList/IssueListFilterDropDowns/index.tsx
  FE/src/components/IssueList/IssueListFilterDropDowns/style.ts
  FE/src/components/IssueList/IssueListFilterDropDowns/type.ts
  FE/src/components/IssueList/IssueListTabs/index.tsx
  FE/src/components/IssueList/ListItem/index.tsx
  FE/src/components/IssueList/ListItem/type.ts
  FE/src/components/IssueList/index.tsx
  FE/src/components/IssueList/mockData.ts
  FE/src/components/IssueList/style.ts
  FE/src/components/common/Dropdown/Panel/index.tsx
  FE/src/components/common/Dropdown/Panel/type.ts
  FE/src/components/common/Dropdown/type.ts
  FE/src/components/common/Label/index.tsx
  FE/src/components/common/Label/style.ts
  FE/src/components/common/Label/type.ts
  FE/src/components/common/TextInput/style.ts
  FE/src/contexts/FilterCondition/action.ts
  FE/src/contexts/FilterCondition/index.tsx
  FE/src/contexts/FilterCondition/reducer.ts
  FE/src/contexts/FilterCondition/type.ts
  FE/src/hooks/useIssueListData.tsx
  FE/src/hooks/useLabelListData.tsx
  FE/src/hooks/useMemberListData.tsx
  FE/src/hooks/useMilestoneListData.tsx
  FE/src/index.tsx
  FE/src/layout/index.tsx
  FE/src/layout/style.ts
  FE/src/pages/IssueList/filterBarOptionData.tsx
  FE/src/pages/IssueList/index.tsx
  FE/src/pages/Loading/index.tsx
  FE/src/types/common.ts
  FE/src/utils/user.ts
Labels: review-FE

#258 [team-26][FE] 호이 & 아울 3주차 첫 번째 PR
  .github/workflows/FE-deploy.yml
  frontend/.eslintrc
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/Close.svg
  frontend/src/assets/loading.gif
  frontend/src/common/GlobalStyle.ts
  frontend/src/components/commentArea/CommentHeader.tsx
  frontend/src/components/common/dropdownButton/DropdownButton.tsx
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/icon/Icon.tsx
  frontend/src/components/common/issueAttribute/IssueAttribute.tsx
  frontend/src/components/common/repositoryHeader/RepositoryHeader.tsx
  frontend/src/components/common/repositoryHeader/navArea/NavArea.tsx
  frontend/src/components/issueModal/IssueModal.tsx
  frontend/src/components/issueSideBarForm/IssueSideBarForm.tsx
  frontend/src/components/issues/DropdownButton.styled.ts
  frontend/src/components/issues/DropdownButton.tsx
  frontend/src/components/issues/DropdownMenu.styled.ts
  frontend/src/components/issues/DropdownMenu.tsx
  frontend/src/components/issues/IssuesHeader.tsx
  frontend/src/components/issues/IssuesItem.tsx
  frontend/src/components/issues/IssuesMain.tsx
  frontend/src/components/issues/IssuesToolbar.styled.ts
  frontend/src/components/issues/IssuesToolbar.tsx
  frontend/src/components/login/Login.styled.ts
  frontend/src/components/login/Login.tsx
  frontend/src/constants/constant.ts
  frontend/src/custom.d.ts
  frontend/src/hooks/useOutsideClick.ts
  frontend/src/index.tsx
  frontend/src/modules/clickedTab.ts
  frontend/src/pages/createIssuePage/CreateIssuePage.tsx
  frontend/src/pages/loading/LoadingPage.styled.ts
  frontend/src/pages/loading/LoadingPage.tsx
  frontend/src/pages/login/LoginPage.tsx
  frontend/src/utils/utils.ts
  frontend/yarn.lock
Labels: review-FE

#249 [Team-35][FE][BB, 럼카] 커스텀 훅 생성 / 로그인 기능 구현
  fe/.gitignore
  fe/package.json
  fe/src/App.tsx
  fe/src/components/ErrorBoundary.tsx
  fe/src/components/Login/Anchor.tsx
  fe/src/components/MilestoneList/MilestoneFormField.tsx
  fe/src/components/common/Error.tsx
  fe/src/components/common/FormField.tsx
  fe/src/components/common/Input/Input.style.ts
  fe/src/components/common/Input/Input.tsx
  fe/src/components/common/Loading/Spinner.tsx
  fe/src/components/common/Loading/index.tsx
  fe/src/components/common/SubNav.tsx
  fe/src/components/common/Tabs.tsx
  fe/src/hooks/useFetch.tsx
  fe/src/hooks/useFetchFromIssueTracker.tsx
  fe/src/hooks/useLocalStorage.tsx
  fe/src/index.tsx
  fe/src/pages/Callback.tsx
  fe/src/pages/IssueList.tsx
  fe/src/pages/LabelList.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/MilestoneList.tsx
  fe/src/pages/Template.tsx
Labels: review-FE
