Repository codesquad-members-2022/issue-tracker, pull requests merged in 2022-07, with the labels that each got.

#250 [Team-04][Android][Linus_Jay][2주차 금요일 네번째 PR]
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/issu_tracker/data/Comment.kt
  app/src/main/java/com/example/issu_tracker/data/ConditionType.kt
  app/src/main/java/com/example/issu_tracker/data/Issue.kt
  app/src/main/java/com/example/issu_tracker/data/repository/FilterRepository.kt
  app/src/main/java/com/example/issu_tracker/data/repository/FilterRepositoryImpl.kt
  app/src/main/java/com/example/issu_tracker/data/repository/HomeRepository.kt
  app/src/main/java/com/example/issu_tracker/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/issu_tracker/data/repository/IssueEditorRepository.kt
  app/src/main/java/com/example/issu_tracker/data/repository/IssueEditorRepositoryImpl.kt
  app/src/main/java/com/example/issu_tracker/data/repository/Repository.kt
  app/src/main/java/com/example/issu_tracker/di/RepositoryModule.kt
  app/src/main/java/com/example/issu_tracker/ui/DetailIssueActivity.kt
  app/src/main/java/com/example/issu_tracker/ui/account/AccountViewModel.kt
  app/src/main/java/com/example/issu_tracker/ui/common/Constants.kt
  app/src/main/java/com/example/issu_tracker/ui/common/CustomImageButton.kt
  app/src/main/java/com/example/issu_tracker/ui/common/LabelAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/common/SpinnerAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/common/SpinnerViewModel.kt
  app/src/main/java/com/example/issu_tracker/ui/common/bndingAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/detail/CommentAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/detail/DetailEditDialogFragment.kt
  app/src/main/java/com/example/issu_tracker/ui/detail/DetailIssueActivity.kt
  app/src/main/java/com/example/issu_tracker/ui/filter/FilterFragment.kt
  app/src/main/java/com/example/issu_tracker/ui/filter/FilterViewModel.kt
  app/src/main/java/com/example/issu_tracker/ui/filter/SpinnerAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueEditorFragment.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueEditorViewModel.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueFragment.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueSearchAdapter.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueSearchFragment.kt
  app/src/main/java/com/example/issu_tracker/ui/issue/IssueSearchViewModel.kt
  app/src/main/java/com/example/issu_tracker/ui/login/LogInActivity.kt
  app/src/main/res/drawable/ic_baseline_arrow_back_ios_24.xml
  app/src/main/res/drawable/ic_baseline_delete_24.xml
  app/src/main/res/drawable/ic_baseline_edit_24.xml
  app/src/main/res/drawable/ic_baseline_more_vert_24.xml
  app/src/main/res/drawable/ic_outline_cancel_24.xml
  app/src/main/res/layout/activity_detail_issue.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/custom_image_button.xml
  app/src/main/res/layout/detail_edit_dialog_fragment.xml
  app/src/main/res/layout/fragment_issue_search.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: review-android

#180 [TEAM-25][BE] 2주차 PR
  BE/build.gradle
  BE/src/main/java/team25/issuetracker/JwtTokenProvider.java
  BE/src/main/java/team25/issuetracker/config/WebConfig.java
  BE/src/main/java/team25/issuetracker/controller/LoginResponse.java
  BE/src/main/java/team25/issuetracker/controller/OauthRestController.java
  BE/src/main/java/team25/issuetracker/controller/RequestRefreshToken.java
  BE/src/main/java/team25/issuetracker/controller/ResponseTokenMessage.java
  BE/src/main/java/team25/issuetracker/domain/OauthRefreshToken.java
  BE/src/main/java/team25/issuetracker/repository/MemberRepository.java
  BE/src/main/java/team25/issuetracker/repository/RefreshTokenRepository.java
  BE/src/main/java/team25/issuetracker/service/OauthService.java
  BE/src/main/java/team25/issuetracker/service/RefreshJson.java
  BE/src/main/resources/application.yml
Labels: review-BE

#281 [Team-35][BE][쿠킴] 코드 리뷰 적용과 인사
  be/src/main/java/dev/kukim/issues/error/controller/ExceptionControllerAdvice.java
  be/src/main/java/dev/kukim/issues/label/controller/LabelController.java
  be/src/main/java/dev/kukim/issues/label/controller/request/LabelInsertRequest.java
  be/src/main/java/dev/kukim/issues/label/controller/request/LabelUpdateRequest.java
  be/src/main/java/dev/kukim/issues/label/controller/response/LabelResponse.java
  be/src/main/java/dev/kukim/issues/label/domain/Description.java
  be/src/main/java/dev/kukim/issues/label/domain/Label.java
  be/src/main/java/dev/kukim/issues/label/domain/Title.java
  be/src/main/java/dev/kukim/issues/label/domain/repository/LabelRepository.java
  be/src/main/java/dev/kukim/issues/label/service/LabelService.java
  be/src/main/java/dev/kukim/issues/milestone/controller/MilestoneController.java
  be/src/main/java/dev/kukim/issues/milestone/controller/response/MilestoneResponse.java
  be/src/main/java/dev/kukim/issues/milestone/domain/Milestone.java
  be/src/main/java/dev/kukim/issues/milestone/domain/repository/MileStoneRepository.java
  be/src/main/java/dev/kukim/issues/milestone/service/MilestoneService.java
  be/src/test/java/dev/kukim/issues/milestone/service/MilestoneServiceTest.java
Labels: review-BE

#261 [Team-09][BE][테리&벅픽] 3주차 PR 1번째 - 이슈 필터 검색 API 개발, 코드 전반 리팩토링
  BE/src/main/java/com/team09/issue_tracker/issue/IssueAssigneeRepository.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueAssigneeService.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueController.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueLabelRepository.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueLabelService.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueRepository.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueService.java
  BE/src/main/java/com/team09/issue_tracker/issue/IssueValidateService.java
  BE/src/main/java/com/team09/issue_tracker/issue/domain/Issue.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueSearchRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/issue/dto/IssueUpdateRequestDto.java
  BE/src/main/java/com/team09/issue_tracker/label/LabelService.java
  BE/src/main/java/com/team09/issue_tracker/milestone/MilestoneService.java
Labels: review-BE

#268 # [iOS][team-09] LabelScene 작업 및 MVVM 구조 개선
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/Model/NetworkService.swift
  iOS/IssueTracker/IssueTracker/Common/Model/UserDefaultManager.swift
  iOS/IssueTracker/IssueTracker/Common/View/DeviderView.swift
  iOS/IssueTracker/IssueTracker/Common/View/HamburgerButton.swift
  iOS/IssueTracker/IssueTracker/Common/View/TabBarController.swift
  iOS/IssueTracker/IssueTracker/Common/View/TextFieldWithTitleView.swift
  iOS/IssueTracker/IssueTracker/Issue/IssueCollectionViewDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/EditingIssueManager.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/EditingIssueNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/IssueItem.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/IssueManager.swift
  iOS/IssueTracker/IssueTracker/Issue/Model/IssueNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/Issue/View/DataSource/IssueListDataSource.swift
  iOS/IssueTracker/IssueTracker/Issue/View/Delegate/EditingIssueTextFieldDelegate.swift
  iOS/IssueTracker/IssueTracker/Issue/View/Delegate/EditingIssueTextViewDelegate.swift
  iOS/IssueTracker/IssueTracker/Issue/View/EditingIssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewComponents/IssueCollectionView.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewComponents/IssueCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewComponents/IssueListCell.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewComponents/IssueListView.swift
  iOS/IssueTracker/IssueTracker/Issue/View/IssueViewController.swift
  iOS/IssueTracker/IssueTracker/Issue/ViewModel/EditingIssueViewModel.swift
  iOS/IssueTracker/IssueTracker/Issue/ViewModel/IssueViewModel.swift
  iOS/IssueTracker/IssueTracker/Label/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Label/Model/EditingLabelManager.swift
  iOS/IssueTracker/IssueTracker/Label/Model/LabelItem.swift
  iOS/IssueTracker/IssueTracker/Label/Model/LabelNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/Label/Model/LabelTableDataSource.swift
  iOS/IssueTracker/IssueTracker/Label/Model/labelManager.swift
  iOS/IssueTracker/IssueTracker/Label/View/EditingLabelViewComponents/EditedLabelPreviewView.swift
  iOS/IssueTracker/IssueTracker/Label/View/EditingLabelViewComponents/EditingLabelView.swift
  iOS/IssueTracker/IssueTracker/Label/View/EditingLabelViewComponents/EditingLabelViewNavigationItems.swift
  iOS/IssueTracker/IssueTracker/Label/View/EditingLabelViewComponents/SelectingLabelBackgroundColorView.swift
  iOS/IssueTracker/IssueTracker/Label/View/EditingLabelViewController.swift
  iOS/IssueTracker/IssueTracker/Label/View/LabelViewComponents/LabelTableCell.swift
  iOS/IssueTracker/IssueTracker/Label/View/LabelViewComponents/LabelTableView.swift
  iOS/IssueTracker/IssueTracker/Label/View/LabelViewComponents/LabelViewNavigationItems.swift
  iOS/IssueTracker/IssueTracker/Label/View/LabelViewController.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/EditingLabelViewModel.swift
  iOS/IssueTracker/IssueTracker/Label/ViewModel/LabelViewModel.swift
  iOS/IssueTracker/IssueTracker/Resource/Info.plist
  iOS/IssueTracker/IssueTracker/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SignInInfo.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SignInManager.swift
  iOS/IssueTracker/IssueTracker/SignIn/Model/SignInNetworkTarget.swift
  iOS/IssueTracker/IssueTracker/SignIn/ViewModel/SignInViewModel.swift
  iOS/IssueTracker/IssueTracker/Utility/Extension/UIColor+Extension.swift
  iOS/IssueTracker/IssueTrackerTests/IssueManagerTests.swift
Labels: review-iOS

#266 [Team-22 BE] Issue Tracker 프로젝트 3주차(금요일) 리뷰 요청
  be/README.md
  be/src/main/java/codesquad/issuetracker/argumentresolver/AccessTokenArgumentResolver.java
  be/src/main/java/codesquad/issuetracker/argumentresolver/Login.java
  be/src/main/java/codesquad/issuetracker/argumentresolver/RefreshTokenArgumentResolver.java
  be/src/main/java/codesquad/issuetracker/config/MvcConfig.java
  be/src/main/java/codesquad/issuetracker/controller/AuthController.java
  be/src/main/java/codesquad/issuetracker/controller/IssueController.java
  be/src/main/java/codesquad/issuetracker/controller/LabelController.java
  be/src/main/java/codesquad/issuetracker/controller/MemberController.java
  be/src/main/java/codesquad/issuetracker/controller/MilestoneController.java
  be/src/main/java/codesquad/issuetracker/controller/ReplyController.java
  be/src/main/java/codesquad/issuetracker/domain/Assignee.java
  be/src/main/java/codesquad/issuetracker/domain/Issue.java
  be/src/main/java/codesquad/issuetracker/domain/IssueLabel.java
  be/src/main/java/codesquad/issuetracker/domain/Label.java
  be/src/main/java/codesquad/issuetracker/domain/Member.java
  be/src/main/java/codesquad/issuetracker/domain/Milestone.java
  be/src/main/java/codesquad/issuetracker/domain/Reply.java
  be/src/main/java/codesquad/issuetracker/dto/issue/form/IssueAssigneeUpdateForm.java
  be/src/main/java/codesquad/issuetracker/dto/issue/form/IssueCreateForm.java
  be/src/main/java/codesquad/issuetracker/dto/issue/form/IssueLabelUpdateForm.java
  be/src/main/java/codesquad/issuetracker/dto/issue/form/IssueMilestoneUpdateForm.java
  be/src/main/java/codesquad/issuetracker/dto/issue/form/IssueStatusUpdateForm.java
  be/src/main/java/codesquad/issuetracker/dto/label/LabelForm.java
  be/src/main/java/codesquad/issuetracker/dto/milestone/MilestoneForm.java
  be/src/main/java/codesquad/issuetracker/dto/reply/ReplyForm.java
  be/src/main/java/codesquad/issuetracker/handler/ImageExceptionHandler.java
  be/src/main/java/codesquad/issuetracker/repository/RedisRepository.java
  be/src/main/java/codesquad/issuetracker/service/GithubOAuthService.java
  be/src/main/java/codesquad/issuetracker/service/ImageService.java
  be/src/main/java/codesquad/issuetracker/service/IssueService.java
  be/src/main/java/codesquad/issuetracker/service/LabelService.java
  be/src/main/java/codesquad/issuetracker/service/MemberService.java
  be/src/main/java/codesquad/issuetracker/service/MilestoneService.java
  be/src/main/java/codesquad/issuetracker/service/ReplyService.java
  be/src/main/java/codesquad/issuetracker/service/TokenService.java
  be/src/main/resources/schema.sql
Labels: review-BE

#269 [Team-28][BE][Yan] 마지막 PR
  BE/src/main/java/kr/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/image/Image.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueSearchService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MemberService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MilestonesService.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/IssueController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/comment/CommentResponseDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/DetailRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueAssigneeDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueDetailLabelDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueDetailMemberDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueDetailMilestoneDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/IssueDetailResponse.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/LabelsResponseDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/MembersResponseDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/issue/MilestonesResponseDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/member/MemberResponseDto.java
Labels: review-BE

#287 [Team-05] [Lee] 이슈트래커 BE 3주차 2번째: 로그인 로직 세부수정 및 인터셉터 추가, 리뷰 반영 리팩토링
  BE/build.gradle
  BE/src/main/java/kr/codesquad/issuetraker/config/OauthClientConfiguration.java
  BE/src/main/java/kr/codesquad/issuetraker/config/OauthPropertiesConfiguration.java
  BE/src/main/java/kr/codesquad/issuetraker/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetraker/controller/LoginController.java
  BE/src/main/java/kr/codesquad/issuetraker/controller/UserController.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/issue/IssueRepository.java
  BE/src/main/java/kr/codesquad/issuetraker/domain/user/User.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/GithubAccessTokenResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/IssueListElementDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/KakaoAccessTokenResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/UserListElementDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/UserListResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/dto/UserRegistrationResponseDto.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/ExpiredJwtTokenException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/InvalidJwtTokenException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/JwtException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/ResourceNotFoundException.java
  BE/src/main/java/kr/codesquad/issuetraker/exception/RuntimeExceptionHandler.java
  BE/src/main/java/kr/codesquad/issuetraker/login/LoginInterceptor.java
  BE/src/main/java/kr/codesquad/issuetraker/login/jwt/JwtProvider.java
  BE/src/main/java/kr/codesquad/issuetraker/login/oauth/GithubOauthClient.java
  BE/src/main/java/kr/codesquad/issuetraker/login/oauth/KakaoOauthClient.java
  BE/src/main/java/kr/codesquad/issuetraker/login/oauth/OauthClient.java
  BE/src/main/java/kr/codesquad/issuetraker/login/oauth/OauthProperties.java
  BE/src/main/java/kr/codesquad/issuetraker/sevice/LoginService.java
  BE/src/main/java/kr/codesquad/issuetraker/sevice/UserService.java
  BE/src/main/resources/application.yml
Labels: review-BE

#271 [Team03] 이슈 관리 프로젝트 마지막 PR 요청드립니다!
  backend/src/main/java/com/team03/issuetracker/common/config/WebConfig.java
  backend/src/main/java/com/team03/issuetracker/issue/api/SearchController.java
  backend/src/main/java/com/team03/issuetracker/issue/application/impl/IssueServiceImpl.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/Issue.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/dto/comment/response/CommentSimpleResponse.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/dto/issue/request/IssueSearchCondition.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/dto/issue/response/IssueDetailResponse.java
  backend/src/main/java/com/team03/issuetracker/issue/domain/dto/issue/response/IssueResponse.java
  backend/src/main/java/com/team03/issuetracker/issue/repository/IssueRepository.java
Labels: review-BE

#227 [Team-15][iOS] IssueList TableView Convert & DIContainer Enhancement
  IssueTracker15/ContainerUnitTest/MockContainer.swift
  IssueTracker15/IssueTracker15.xcodeproj/project.pbxproj
  IssueTracker15/IssueTracker15/Container/ContainerWrapper.swift
  IssueTracker15/IssueTracker15/Container/Resolvable.swift
  IssueTracker15/IssueTracker15/Issue/Filter/IssueFilterItemSelectViewController.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/IssueDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/LabelDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/MilestoneDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/DTO/UserDTO.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/Model/IssueListModel.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/Model/IssueUpdateModel.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/UseCase/IssueListUseCase.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/UseCase/IssueModifyUseCase.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListFooterReusableView.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListHeaderReusableView.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListSearchBar.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListTableViewCell.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListTableViewController.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListTableViewDataSource.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListTableViewDelegate.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueListViewController.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/View/IssueTableView.swift
  IssueTracker15/IssueTracker15/Issue/IssueList/ViewModel/IssueViewModel.swift
  IssueTracker15/IssueTracker15/Issue/IssueNavigationController.swift
  IssueTracker15/IssueTracker15/Label/AddLabelViewController.swift
  IssueTracker15/IssueTracker15/Label/IssueLabelDataSource.swift
  IssueTracker15/IssueTracker15/Label/LabelNavigationController.swift
  IssueTracker15/IssueTracker15/Label/LabelViewController.swift
  IssueTracker15/IssueTracker15/Label/View/AddLabelBarButtonItem.swift
  IssueTracker15/IssueTracker15/Label/View/IssueTitleButton.swift
  IssueTracker15/IssueTracker15/Label/View/LabelTableViewCell.swift
  IssueTracker15/IssueTracker15/Login/UseCase/AppleLoginUseCase.swift
  IssueTracker15/IssueTracker15/Login/UseCase/GithubLoginUseCase.swift
  IssueTracker15/IssueTracker15/Login/View/OAuthLoginButton.swift
  IssueTracker15/IssueTracker15/Login/View/UserInfoTextField.swift
  IssueTracker15/IssueTracker15/Login/ViewModel/LoginViewModel.swift
  IssueTracker15/IssueTracker15/MainTabBarController.swift
  IssueTracker15/IssueTracker15/Repository/Network/NetworkService.swift
  IssueTracker15/IssueTracker15/Repository/Persistent/PersistentService.swift
  IssueTracker15/IssueTracker15/Repository/Repository.swift
  IssueTracker15/IssueTracker15/Repository/ServiceContainer.swift
  IssueTracker15/IssueTracker15/Repository/Transferable.swift
  IssueTracker15/IssueTracker15/SupportingFiles/AppDelegate.swift
  IssueTracker15/IssueTracker15/SupportingFiles/SceneDelegate.swift
  IssueTracker15/IssueTracker15/UseCaseInterface/UseCaseContainer.swift
  IssueTracker15/IssueTracker15/UseCaseInterface/UseCaseResponsible.swift
  IssueTracker15/IssueTracker15/ViewBind/ViewBindable.swift
Labels: review-iOS

#260 [team24-BE] 민지노 && 필 3주차 첫번째 PR 요청
  .github/workflows/gradle.yml
  BE/build.gradle
  BE/src/main/java/team24/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team24/issuetracker/common/config/WebMvcConfig.java
  BE/src/main/java/team24/issuetracker/issue/application/IssueService.java
  BE/src/main/java/team24/issuetracker/issue/controller/IssueController.java
  BE/src/main/java/team24/issuetracker/issue/domain/Comment.java
  BE/src/main/java/team24/issuetracker/issue/domain/Issue.java
  BE/src/main/java/team24/issuetracker/issue/domain/dto/IssueListLabelResponse.java
  BE/src/main/java/team24/issuetracker/issue/domain/dto/IssueListMemberResponse.java
  BE/src/main/java/team24/issuetracker/issue/domain/dto/IssueListResponse.java
  BE/src/main/java/team24/issuetracker/issue/domain/dto/IssueListUserResponse.java
  BE/src/main/java/team24/issuetracker/issue/domain/dto/IssueRequest.java
  BE/src/main/java/team24/issuetracker/issue/domain/reference/IssueLabel.java
  BE/src/main/java/team24/issuetracker/issue/domain/reference/IssueMember.java
  BE/src/main/java/team24/issuetracker/issue/domain/reference/IssueUser.java
  BE/src/main/java/team24/issuetracker/issue/exception/IssueNotFoundException.java
  BE/src/main/java/team24/issuetracker/issue/repository/IssueRepository.java
  BE/src/main/java/team24/issuetracker/label/domain/Label.java
  BE/src/main/java/team24/issuetracker/label/domain/dto/LabelListResponse.java
  BE/src/main/java/team24/issuetracker/label/exception/LabelNotFoundException.java
  BE/src/main/java/team24/issuetracker/label/repository/LabelRepository.java
  BE/src/main/java/team24/issuetracker/member/controller/MemberController.java
  BE/src/main/java/team24/issuetracker/member/domain/Member.java
  BE/src/main/java/team24/issuetracker/member/domain/dto/MemberResponse.java
  BE/src/main/java/team24/issuetracker/member/exception/MemberNotFoundException.java
  BE/src/main/java/team24/issuetracker/member/repository/MemberRepository.java
  BE/src/main/java/team24/issuetracker/member/service/MemberService.java
  BE/src/main/java/team24/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/team24/issuetracker/milestone/domain/dto/MilestoneListResponse.java
  BE/src/main/java/team24/issuetracker/milestone/exception/MilestoneNotFoundException.java
  BE/src/main/java/team24/issuetracker/milestone/repository/MilestoneRepository.java
  BE/src/main/java/team24/issuetracker/oauth/controller/OAuthController.java
  BE/src/main/java/team24/issuetracker/oauth/dto/GitHubAccessToken.java
  BE/src/main/java/team24/issuetracker/oauth/dto/GitHubAccessTokenRequest.java
  BE/src/main/java/team24/issuetracker/oauth/dto/GitHubUser.java
  BE/src/main/java/team24/issuetracker/oauth/dto/LoginMemberResponse.java
  BE/src/main/java/team24/issuetracker/oauth/properties/JwtProperties.java
  BE/src/main/java/team24/issuetracker/oauth/properties/OAuthProperties.java
  BE/src/main/java/team24/issuetracker/oauth/provider/JwtProvider.java
  BE/src/main/java/team24/issuetracker/oauth/service/OAuthService.java
  BE/src/main/java/team24/issuetracker/uploadedfile/controller/UploadController.java
  BE/src/main/java/team24/issuetracker/uploadedfile/domain/UploadedFile.java
  BE/src/main/java/team24/issuetracker/uploadedfile/repository/UploadRepository.java
  BE/src/main/java/team24/issuetracker/uploadedfile/service/UploadService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/auth.yml
Labels: review-BE

#276 [Team-36, BE] Sally, IssueTracker 3주차 PR
  BE/build.gradle
  BE/src/main/java/com/sh/issuetracker/assignee/Assignee.java
  BE/src/main/java/com/sh/issuetracker/assignee/AssigneeId.java
  BE/src/main/java/com/sh/issuetracker/common/exception/GlobalControllerAdvice.java
  BE/src/main/java/com/sh/issuetracker/config/AppConfig.java
  BE/src/main/java/com/sh/issuetracker/config/SecurityConfig.java
  BE/src/main/java/com/sh/issuetracker/exception/InvalidSearchParamException.java
  BE/src/main/java/com/sh/issuetracker/exception/NoneSearchParamException.java
  BE/src/main/java/com/sh/issuetracker/issue/Issue.java
  BE/src/main/java/com/sh/issuetracker/issue/IssueApiController.java
  BE/src/main/java/com/sh/issuetracker/issue/IssueRepository.java
  BE/src/main/java/com/sh/issuetracker/issue/IssueService.java
  BE/src/main/java/com/sh/issuetracker/issue/IssueStatus.java
  BE/src/main/java/com/sh/issuetracker/issue/dto/IssueLabelMapper.java
  BE/src/main/java/com/sh/issuetracker/issue/dto/IssueResponse.java
  BE/src/main/java/com/sh/issuetracker/issue/dto/NumberOfIssueStatus.java
  BE/src/main/java/com/sh/issuetracker/issue/dto/NumberOfIssueStatusAndMilestoneDto.java
  BE/src/main/java/com/sh/issuetracker/issue/dto/NumberOfIssueStatusDto.java
  BE/src/main/java/com/sh/issuetracker/issue/search/IssueIdsBySearchDto.java
  BE/src/main/java/com/sh/issuetracker/issue/search/IssueLabelDto.java
  BE/src/main/java/com/sh/issuetracker/issue/search/IssueSearchDto.java
  BE/src/main/java/com/sh/issuetracker/issue/search/IssueSearchParam.java
  BE/src/main/java/com/sh/issuetracker/issue/search/IssueSearchRepository.java
  BE/src/main/java/com/sh/issuetracker/issue/search/SearchKeyType.java
  BE/src/main/java/com/sh/issuetracker/issue/search/SearchWordMap.java
  BE/src/main/java/com/sh/issuetracker/issuelabel/IssueLabel.java
  BE/src/main/java/com/sh/issuetracker/label/LabelService.java
  BE/src/main/java/com/sh/issuetracker/login/jwt/JwtToken.java
  BE/src/main/java/com/sh/issuetracker/login/jwt/OauthJwtUtil.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/ClientRegistration.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/ClientRegistrationRepository.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/ClientScope.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/InMemoryClientRegistrationRepository.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/OAuthProvider.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/OauthLoginApiController.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/OauthLoginService.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/OauthRestTemplate.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/OauthToken.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/TempOauthTokenMemoryRepository.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/dto/OauthTokenParam.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/dto/Response.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/user/AuthUser.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/user/OauthUser.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/user/OauthUserMemoryRepository.java
  BE/src/main/java/com/sh/issuetracker/login/oauth/user/Role.java
  BE/src/main/java/com/sh/issuetracker/member/MemberRepository.java
  BE/src/main/java/com/sh/issuetracker/milestone/MilestoneApiController.java
  BE/src/main/java/com/sh/issuetracker/milestone/MilestoneService.java
  BE/src/main/java/com/sh/issuetracker/milestone/Milestones.java
  BE/src/main/java/com/sh/issuetracker/milestone/dto/MilestoneResponse.java
  BE/src/test/java/com/sh/issuetracker/issue/IssueRepositoryTest.java
  BE/src/test/java/com/sh/issuetracker/issue/dto/IssueSearchRequestTest.java
  BE/src/test/java/com/sh/issuetracker/login/jwt/OauthJwtUtilTest.java
  BE/src/test/java/com/sh/issuetracker/milestone/MilestoneRepositoryTest.java
Labels: review-BE

#288 [TEAM-28][난정 & 옐로우]3주차 수요일 PR
  FE/config/webpack.common.js
  FE/src/App.tsx
  FE/src/common/components/Layout.tsx
  FE/src/common/components/Tab.tsx
  FE/src/common/components/TextInput.tsx
  FE/src/common/components/buttons/Button.tsx
  FE/src/common/components/buttons/ButtonSmallStandard.tsx
  FE/src/common/components/dropDown/DropDownCheckBoxItem.tsx
  FE/src/common/components/dropDown/DropDownPanel.tsx
  FE/src/common/constants/index.ts
  FE/src/common/constants/path.ts
  FE/src/common/utils/index.ts
  FE/src/common/utils/time.ts
  FE/src/issueList/FilterBar.tsx
  FE/src/issueList/LinkTabs.tsx
  FE/src/issueList/issueListTable/CheckBox.tsx
  FE/src/issueList/issueListTable/IssueList.tsx
  FE/src/issueList/issueListTable/issueHeader/ClickedIssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueMenu.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueTab.tsx
  FE/src/issueList/issueListTable/issueHeader/StatusIssueTab.tsx
  FE/src/issueList/issueListTable/issueItem/EmptyIssueItem.tsx
  FE/src/issueList/issueListTable/issueItem/IssueItem.tsx
  FE/src/issueList/stores/checkReducer.tsx
  FE/src/login/Login.tsx
  FE/src/pages/IssueListPage.tsx
  FE/tsconfig.json
Labels: review-FE

#275 [Team-21][FE] jinnie & benny 3주차 두번째 PR
  FE/package-lock.json
  FE/package.json
  FE/public/Icons.svg
  FE/src/App.tsx
  FE/src/common/NewIssueForm/NewIssueForm.stories.tsx
  FE/src/common/NewIssueForm/NewIssueForm.styled.ts
  FE/src/common/NewIssueForm/NewIssueForm.tsx
  FE/src/common/NewIssueForm/index.ts
  FE/src/common/global.ts
  FE/src/component/Container/Container.styled.ts
  FE/src/component/Container/Container.tsx
  FE/src/hooks/useAccessToken.ts
  FE/src/pages/Callback/index.tsx
  FE/src/pages/Issues/Data.tsx
  FE/src/pages/Issues/Issues.tsx
Labels: review-FE

#239 [Team16][iOS] 바인드 방식 변경과 IssueCell UI 작업
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Source/Present/IssueList/Model/Issue.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/Model/Milestone.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/Model/Tag.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/View/IssueCell.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/View/IssueListViewController.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/ViewModel/IssueCellViewModel.swift
  IssueTracker/IssueTracker/Source/Present/IssueList/ViewModel/IssueListViewModel.swift
  IssueTracker/IssueTracker/Source/Present/Support/Observable.swift
  IssueTracker/IssueTracker/Source/Present/Support/SceneDelegate.swift
  IssueTracker/IssueTracker/Source/Present/Window/View/RootWindow.swift
  IssueTracker/IssueTracker/Source/Present/Window/View/TabBarViewController.swift
  IssueTracker/IssueTracker/Source/Present/Window/ViewModel/RootWindowViewModel.swift
Labels: review-iOS
